import type { StudyQuestion } from "../types";

// 핵심 문제와 겹치지 않도록 세부 문법, 계산, 비교 개념을 보강한 확장 문제은행이다.
// 실제 기출문장을 복제하지 않고 출제 범위의 역량을 연습할 수 있게 새로 구성했다.
export const ADDITIONAL_QUESTIONS: StudyQuestion[] = [
  {
    id: "c-switch-02",
    kind: "code",
    topic: "C언어",
    difficulty: "기초",
    tags: ["code", "c", "switch", "제어문"],
    prompt: [
      "다음 C 프로그램의 출력값을 쓰시오.",
      "```c",
      "int n = 2;",
      "switch (n) {",
      "  case 1: printf(\"A\"); break;",
      "  case 2: printf(\"B\");",
      "  case 3: printf(\"C\");",
      "  default: printf(\"D\");",
      "}",
      "```"
    ].join("\n"),
    answer: "BCD",
    hint: "case 2 이후 break가 있는지 확인하세요.",
    explanation: "case 2에서 B를 출력한 뒤 break가 없어 case 3과 default까지 차례로 실행합니다.",
    confusion: "switch는 일치하는 case부터 시작하며 break를 만나기 전까지 아래 case로 계속 진행합니다."
  },
  {
    id: "c-string-02",
    kind: "code",
    topic: "C언어",
    difficulty: "기초",
    tags: ["code", "c", "문자열", "배열"],
    prompt: [
      "다음 C 프로그램의 출력값을 쓰시오.",
      "```c",
      "char s[] = \"KOREA\";",
      "printf(\"%c %zu\", s[2], strlen(s));",
      "```"
    ].join("\n"),
    answer: "R 5",
    hint: "문자열 인덱스는 0부터 시작하고 strlen은 널 문자를 제외합니다.",
    explanation: "s[2]는 세 번째 문자 R이고 문자열 KOREA의 길이는 5입니다.",
    confusion: "배열 공간에는 끝의 널 문자까지 6칸이 필요하지만 strlen의 결과는 5입니다."
  },
  {
    id: "c-pointer-02",
    kind: "code",
    topic: "C언어",
    difficulty: "실전",
    tags: ["code", "c", "포인터", "배열"],
    prompt: [
      "다음 C 프로그램의 출력값을 쓰시오.",
      "```c",
      "int a[] = {3, 6, 9, 12};",
      "int *p = a + 1;",
      "printf(\"%d \", *p);",
      "p += 2;",
      "printf(\"%d\", *p);",
      "```"
    ].join("\n"),
    answer: "6 12",
    hint: "a + 1은 a[1]의 주소입니다.",
    explanation: "처음 p는 a[1]인 6을 가리키고 두 칸 이동한 뒤에는 a[3]인 12를 가리킵니다.",
    confusion: "포인터 덧셈은 바이트가 아니라 가리키는 자료형의 원소 단위로 이동합니다."
  },
  {
    id: "c-static-01",
    kind: "code",
    topic: "C언어",
    difficulty: "실전",
    tags: ["code", "c", "static", "함수"],
    prompt: [
      "다음 C 프로그램의 출력값을 쓰시오.",
      "```c",
      "int f(void) {",
      "  static int x = 0;",
      "  x += 2;",
      "  return x;",
      "}",
      "printf(\"%d \", f());",
      "printf(\"%d \", f());",
      "printf(\"%d\", f());",
      "```"
    ].join("\n"),
    answer: "2 4 6",
    hint: "static 변수의 값은 함수 호출이 끝난 뒤에도 유지됩니다.",
    explanation: "x는 한 번만 초기화되고 호출 사이에 유지되므로 각 호출에서 2, 4, 6을 차례로 반환합니다.",
    confusion: "일반 지역 변수는 호출할 때마다 새로 만들어지지만 static 지역 변수는 프로그램 실행 동안 유지됩니다."
  },
  {
    id: "c-shift-01",
    kind: "code",
    topic: "C언어",
    difficulty: "실전",
    tags: ["code", "c", "비트", "시프트", "calculation"],
    prompt: [
      "다음 C 프로그램의 출력값을 쓰시오.",
      "```c",
      "int x = 5;",
      "printf(\"%d\", (x << 1) | 3);",
      "```"
    ].join("\n"),
    answer: "11",
    hint: "5를 왼쪽으로 한 칸 이동한 값과 3을 OR 연산합니다.",
    explanation: "5는 0101₂이고 왼쪽 시프트하면 1010₂인 10입니다. 10 OR 3은 1011₂로 11입니다.",
    confusion: "왼쪽 시프트는 범위 안의 양수에서 보통 2를 곱한 효과가 있지만 OR는 별도로 비트별 계산해야 합니다."
  },
  {
    id: "c-call-value-01",
    kind: "code",
    topic: "C언어",
    difficulty: "기초",
    tags: ["code", "c", "함수", "매개변수"],
    prompt: [
      "다음 C 프로그램의 출력값을 쓰시오.",
      "```c",
      "void change(int x) { x = 20; }",
      "int n = 10;",
      "change(n);",
      "printf(\"%d\", n);",
      "```"
    ].join("\n"),
    answer: "10",
    hint: "함수에 n의 값이 복사되어 전달됩니다.",
    explanation: "change의 x는 n과 별개의 지역 변수이므로 x를 바꿔도 n은 10으로 유지됩니다.",
    confusion: "호출한 변수 자체를 바꾸려면 주소를 전달하고 포인터로 역참조해야 합니다."
  },
  {
    id: "c-double-pointer-01",
    kind: "code",
    topic: "C언어",
    difficulty: "심화",
    tags: ["code", "c", "포인터", "이중포인터"],
    prompt: [
      "다음 C 프로그램의 출력값을 쓰시오.",
      "```c",
      "int n = 3;",
      "int *p = &n;",
      "int **pp = &p;",
      "**pp += 4;",
      "printf(\"%d\", n);",
      "```"
    ].join("\n"),
    answer: "7",
    hint: "pp를 두 번 역참조하면 어떤 변수에 도달하는지 확인하세요.",
    explanation: "pp는 p의 주소이고 p는 n의 주소이므로 **pp는 n 자체입니다. n에 4를 더해 7이 됩니다.",
    confusion: "*pp는 p이고 **pp는 p가 가리키는 n입니다."
  },
  {
    id: "c-matrix-02",
    kind: "code",
    topic: "C언어",
    difficulty: "실전",
    tags: ["code", "c", "배열", "반복문"],
    prompt: [
      "다음 C 프로그램의 출력값을 쓰시오.",
      "```c",
      "int a[3][3] = {{1,2,3},{4,5,6},{7,8,9}};",
      "int sum = 0;",
      "for (int i = 0; i < 3; i++) sum += a[i][2-i];",
      "printf(\"%d\", sum);",
      "```"
    ].join("\n"),
    answer: "15",
    hint: "열 인덱스가 2, 1, 0 순서로 바뀝니다.",
    explanation: "선택되는 값은 a[0][2]=3, a[1][1]=5, a[2][0]=7이므로 합은 15입니다.",
    confusion: "a[i][i]는 주대각선, a[i][크기-1-i]는 반대 대각선입니다."
  },
  {
    id: "java-constructor-02",
    kind: "code",
    topic: "Java",
    difficulty: "기초",
    tags: ["code", "java", "상속", "생성자"],
    prompt: [
      "다음 Java 프로그램의 출력값을 쓰시오.",
      "```java",
      "class A { A() { System.out.print(\"A\"); } }",
      "class B extends A { B() { System.out.print(\"B\"); } }",
      "new B();",
      "```"
    ].join("\n"),
    answer: "AB",
    hint: "자식 생성자보다 부모 생성자가 먼저 실행됩니다.",
    explanation: "B 생성 시 암시적으로 super()가 먼저 호출되어 A를 출력한 뒤 B 생성자에서 B를 출력합니다.",
    confusion: "생성자 호출 순서는 부모에서 자식 방향이고 종료는 자식에서 부모 방향입니다."
  },
  {
    id: "java-static-02",
    kind: "code",
    topic: "Java",
    difficulty: "기초",
    tags: ["code", "java", "static", "객체"],
    prompt: [
      "다음 Java 프로그램의 출력값을 쓰시오.",
      "```java",
      "class Item {",
      "  static int count = 0;",
      "  Item() { count++; }",
      "}",
      "new Item(); new Item();",
      "System.out.print(Item.count);",
      "```"
    ].join("\n"),
    answer: "2",
    hint: "count는 객체마다 따로 생기지 않습니다.",
    explanation: "static 필드는 클래스에 하나만 존재하며 두 객체의 생성자가 같은 count를 각각 1씩 증가시킵니다.",
    confusion: "인스턴스 필드는 객체별로 존재하지만 static 필드는 클래스 전체가 공유합니다."
  },
  {
    id: "java-overload-02",
    kind: "code",
    topic: "Java",
    difficulty: "실전",
    tags: ["code", "java", "오버로딩", "메서드"],
    prompt: [
      "다음 Java 프로그램의 출력값을 쓰시오.",
      "```java",
      "static void f(int x) { System.out.print(\"I\"); }",
      "static void f(double x) { System.out.print(\"D\"); }",
      "f(3); f(3.0);",
      "```"
    ].join("\n"),
    answer: "ID",
    hint: "인수의 리터럴 자료형과 가장 정확히 일치하는 메서드를 찾으세요.",
    explanation: "정수 리터럴 3은 int 버전, 실수 리터럴 3.0은 double 버전을 호출합니다.",
    confusion: "오버로딩은 컴파일 시 매개변수 타입으로 결정되고 오버라이딩은 실행 시 실제 객체로 결정됩니다."
  },
  {
    id: "java-list-02",
    kind: "code",
    topic: "Java",
    difficulty: "실전",
    tags: ["code", "java", "컬렉션", "list"],
    prompt: [
      "다음 Java 프로그램의 출력값을 쓰시오.",
      "```java",
      "List<Integer> list = new ArrayList<>(List.of(1, 2, 3));",
      "list.remove(1);",
      "System.out.print(list);",
      "```"
    ].join("\n"),
    answer: "[1, 3]",
    hint: "remove에 전달된 1이 인덱스인지 값인지 확인하세요.",
    explanation: "int 인수 1은 인덱스로 해석되어 두 번째 원소 2가 삭제됩니다.",
    confusion: "값 1을 삭제하려면 list.remove(Integer.valueOf(1))처럼 객체를 전달해야 합니다."
  },
  {
    id: "java-builder-01",
    kind: "code",
    topic: "Java",
    difficulty: "기초",
    tags: ["code", "java", "문자열", "stringbuilder"],
    prompt: [
      "다음 Java 프로그램의 출력값을 쓰시오.",
      "```java",
      "StringBuilder sb = new StringBuilder(\"abcd\");",
      "sb.reverse().deleteCharAt(1);",
      "System.out.print(sb);",
      "```"
    ].join("\n"),
    answer: "dba",
    hint: "먼저 문자열을 뒤집은 뒤 인덱스 1의 문자를 삭제합니다.",
    explanation: "abcd를 뒤집으면 dcba이고 인덱스 1의 c를 삭제하면 dba가 됩니다.",
    confusion: "String은 불변이지만 StringBuilder는 같은 객체의 내용을 변경합니다."
  },
  {
    id: "java-finally-return-01",
    kind: "code",
    topic: "Java",
    difficulty: "심화",
    tags: ["code", "java", "예외", "finally"],
    prompt: [
      "다음 Java 메서드에서 f()의 반환값을 쓰시오.",
      "```java",
      "static int f() {",
      "  try { return 1; }",
      "  finally { return 2; }",
      "}",
      "```"
    ].join("\n"),
    answer: "2",
    hint: "try의 return 전에 finally가 실행됩니다.",
    explanation: "finally의 return이 앞서 준비된 try의 반환값을 덮어써 최종적으로 2를 반환합니다.",
    confusion: "finally에서 return을 사용하면 예외나 기존 반환값을 숨길 수 있어 실무에서는 피하는 것이 좋습니다."
  },
  {
    id: "java-abstract-01",
    kind: "code",
    topic: "Java",
    difficulty: "실전",
    tags: ["code", "java", "추상클래스", "다형성"],
    prompt: [
      "다음 Java 프로그램의 출력값을 쓰시오.",
      "```java",
      "abstract class Animal { abstract String sound(); }",
      "class Dog extends Animal { String sound() { return \"멍\"; } }",
      "Animal a = new Dog();",
      "System.out.print(a.sound());",
      "```"
    ].join("\n"),
    answer: "멍",
    hint: "실제 생성된 객체의 오버라이딩 메서드가 호출됩니다.",
    explanation: "참조 타입은 Animal이지만 실제 객체는 Dog이므로 Dog의 sound()가 실행됩니다.",
    confusion: "추상 클래스는 직접 인스턴스화할 수 없지만 하위 클래스 타입을 참조할 수 있습니다."
  },
  {
    id: "python-comprehension-02",
    kind: "code",
    topic: "Python",
    difficulty: "기초",
    tags: ["code", "python", "리스트", "컴프리헨션"],
    prompt: [
      "다음 Python 프로그램의 출력값을 쓰시오.",
      "```python",
      "a = [x * x for x in range(1, 6) if x % 2 == 0]",
      "print(a)",
      "```"
    ].join("\n"),
    answer: "[4, 16]",
    hint: "1부터 5 중 짝수만 고른 뒤 제곱합니다.",
    explanation: "조건을 만족하는 2와 4를 각각 제곱하여 4와 16이 리스트에 들어갑니다.",
    confusion: "range(1, 6)은 끝값 6을 포함하지 않습니다."
  },
  {
    id: "python-dict-get-02",
    kind: "code",
    topic: "Python",
    difficulty: "기초",
    tags: ["code", "python", "딕셔너리", "get"],
    prompt: [
      "다음 Python 프로그램의 출력값을 쓰시오.",
      "```python",
      "d = {'a': 2}",
      "d['b'] = d.get('b', 0) + d['a']",
      "print(d['b'])",
      "```"
    ].join("\n"),
    answer: "2",
    hint: "없는 키를 get으로 조회할 때 지정한 기본값이 사용됩니다.",
    explanation: "b가 없으므로 d.get('b', 0)은 0이고 d['a']의 2를 더해 b에 2가 저장됩니다.",
    confusion: "d['b']로 없는 키를 바로 읽으면 KeyError지만 get은 기본값을 반환할 수 있습니다."
  },
  {
    id: "python-set-02",
    kind: "code",
    topic: "Python",
    difficulty: "기초",
    tags: ["code", "python", "set", "집합"],
    prompt: [
      "다음 Python 프로그램의 출력값을 쓰시오.",
      "```python",
      "a = {1, 2, 3}",
      "b = {2, 3, 4}",
      "print(sorted(a ^ b))",
      "```"
    ].join("\n"),
    answer: "[1, 4]",
    hint: "^는 두 집합의 대칭 차집합입니다.",
    explanation: "한쪽 집합에만 존재하는 원소는 1과 4이며 sorted로 정렬된 리스트가 출력됩니다.",
    confusion: "&는 교집합, |는 합집합, ^는 공통 원소를 제외한 대칭 차집합입니다."
  },
  {
    id: "python-zip-01",
    kind: "code",
    topic: "Python",
    difficulty: "실전",
    tags: ["code", "python", "zip", "반복문"],
    prompt: [
      "다음 Python 프로그램의 출력값을 쓰시오.",
      "```python",
      "a = [1, 2, 3]",
      "b = [4, 5, 6]",
      "print(sum(x * y for x, y in zip(a, b)))",
      "```"
    ].join("\n"),
    answer: "32",
    hint: "같은 위치의 원소끼리 곱한 뒤 모두 더합니다.",
    explanation: "1×4 + 2×5 + 3×6 = 4 + 10 + 18 = 32입니다.",
    confusion: "zip은 가장 짧은 반복 가능 객체의 길이까지만 묶습니다."
  },
  {
    id: "python-class-variable-01",
    kind: "code",
    topic: "Python",
    difficulty: "실전",
    tags: ["code", "python", "클래스", "변수"],
    prompt: [
      "다음 Python 프로그램의 출력값을 쓰시오.",
      "```python",
      "class A:",
      "    x = 1",
      "a = A()",
      "b = A()",
      "a.x = 5",
      "A.x = 3",
      "print(a.x, b.x)",
      "```"
    ].join("\n"),
    answer: "5 3",
    hint: "a에는 인스턴스 변수 x가 새로 생겼습니다.",
    explanation: "a.x=5는 a만의 변수를 만들고 b는 인스턴스 변수가 없어 변경된 클래스 변수 A.x=3을 읽습니다.",
    confusion: "인스턴스 속성이 있으면 클래스 속성보다 먼저 조회됩니다."
  },
  {
    id: "python-slice-02",
    kind: "code",
    topic: "Python",
    difficulty: "기초",
    tags: ["code", "python", "슬라이싱", "리스트"],
    prompt: [
      "다음 Python 프로그램의 출력값을 쓰시오.",
      "```python",
      "a = [1, 2, 3, 4, 5]",
      "print(a[::-2])",
      "```"
    ].join("\n"),
    answer: "[5, 3, 1]",
    hint: "음수 간격은 뒤에서 앞으로 이동합니다.",
    explanation: "마지막 원소 5부터 두 칸씩 거꾸로 선택해 5, 3, 1이 됩니다.",
    confusion: "[::-1]은 전체 역순이고 [::-2]는 역순으로 두 칸 간격입니다."
  },
  {
    id: "python-gcd-01",
    kind: "code",
    topic: "Python",
    difficulty: "실전",
    tags: ["code", "python", "재귀", "알고리즘"],
    prompt: [
      "다음 Python 프로그램의 출력값을 쓰시오.",
      "```python",
      "def gcd(a, b):",
      "    return a if b == 0 else gcd(b, a % b)",
      "print(gcd(48, 18))",
      "```"
    ].join("\n"),
    answer: "6",
    hint: "48과 18에 유클리드 호제법을 적용합니다.",
    explanation: "gcd(48,18) → gcd(18,12) → gcd(12,6) → gcd(6,0)이므로 6입니다.",
    confusion: "재귀 호출에서 두 번째 인수가 0이 되면 첫 번째 인수를 반환합니다."
  },
  {
    id: "sql-count-distinct-02",
    kind: "sql",
    topic: "SQL",
    difficulty: "기초",
    tags: ["sql", "database", "집계", "distinct"],
    prompt: "EMP 테이블에서 중복을 제외한 부서번호(DEPTNO)의 개수를 구하는 SQL문을 쓰시오.",
    answer: "SELECT COUNT(DISTINCT DEPTNO) FROM EMP;",
    hint: "COUNT 안에서 중복 제거 키워드를 사용합니다.",
    explanation: "DISTINCT DEPTNO로 부서번호 중복을 제거한 뒤 COUNT로 개수를 셉니다.",
    confusion: "COUNT(DEPTNO)는 NULL을 제외하지만 중복은 포함하고, COUNT(DISTINCT DEPTNO)는 중복도 제외합니다."
  },
  {
    id: "sql-having-02",
    kind: "sql",
    topic: "SQL",
    difficulty: "실전",
    tags: ["sql", "database", "group by", "having"],
    prompt: "SALES(category, amount)에서 카테고리별 매출 합계가 1000 이상인 category와 합계를 조회하는 SQL문을 쓰시오.",
    answer: "SELECT category, SUM(amount) FROM SALES GROUP BY category HAVING SUM(amount) >= 1000;",
    hint: "그룹의 집계 결과 조건은 WHERE가 아니라 다른 절에 작성합니다.",
    explanation: "category로 그룹화하고 SUM(amount)을 계산한 뒤 HAVING으로 합계가 1000 이상인 그룹만 남깁니다.",
    confusion: "WHERE는 그룹화 전 행 조건, HAVING은 그룹화 후 집계 조건입니다."
  },
  {
    id: "sql-subquery-02",
    kind: "sql",
    topic: "SQL",
    difficulty: "실전",
    tags: ["sql", "database", "서브쿼리", "평균"],
    prompt: "EMP(name, salary)에서 전체 평균 급여보다 급여가 높은 직원의 name을 조회하는 SQL문을 쓰시오.",
    answer: "SELECT name FROM EMP WHERE salary > (SELECT AVG(salary) FROM EMP);",
    hint: "평균 급여를 단일 값을 반환하는 서브쿼리로 계산합니다.",
    explanation: "내부 쿼리가 전체 평균을 구하고 외부 쿼리가 각 직원의 salary와 비교합니다.",
    confusion: "집계값과 개별 행을 비교하려면 보통 집계 쿼리를 서브쿼리로 분리합니다."
  },
  {
    id: "sql-update-02",
    kind: "sql",
    topic: "SQL",
    difficulty: "기초",
    tags: ["sql", "database", "update", "dml"],
    prompt: "EMP 테이블에서 DEPTNO가 10인 직원들의 salary를 10% 인상하는 SQL문을 쓰시오.",
    answer: "UPDATE EMP SET salary = salary * 1.1 WHERE DEPTNO = 10;",
    hint: "현재 salary 값에 1.1을 곱합니다.",
    explanation: "WHERE로 10번 부서만 선택하고 기존 salary의 110%를 새 값으로 저장합니다.",
    confusion: "WHERE를 생략하면 모든 행의 급여가 변경됩니다."
  },
  {
    id: "sql-delete-null-01",
    kind: "sql",
    topic: "SQL",
    difficulty: "기초",
    tags: ["sql", "database", "delete", "null"],
    prompt: "MEMBER 테이블에서 email이 NULL인 행을 삭제하는 SQL문을 쓰시오.",
    answer: "DELETE FROM MEMBER WHERE email IS NULL;",
    hint: "NULL 비교에는 등호를 사용하지 않습니다.",
    explanation: "NULL은 일반 값이 아니므로 IS NULL 조건으로 찾은 뒤 DELETE합니다.",
    confusion: "email = NULL은 참이 되지 않으며 IS NULL 또는 IS NOT NULL을 사용해야 합니다."
  },
  {
    id: "sql-create-fk-01",
    kind: "sql",
    topic: "SQL",
    difficulty: "실전",
    tags: ["sql", "database", "ddl", "외래키"],
    prompt: "DEPT(id)를 참조하는 EMP(dept_id)의 외래키 제약조건을 테이블 생성 시 지정하는 핵심 구문을 쓰시오.",
    answer: "FOREIGN KEY (dept_id) REFERENCES DEPT(id)",
    hint: "참조하는 열과 참조 대상 테이블·열을 함께 적습니다.",
    explanation: "FOREIGN KEY로 EMP의 dept_id를 지정하고 REFERENCES로 DEPT의 id를 참조하게 합니다.",
    confusion: "PRIMARY KEY는 행을 식별하고 FOREIGN KEY는 다른 테이블의 키와 참조 관계를 만듭니다."
  },
  {
    id: "sql-dense-rank-01",
    kind: "sql",
    topic: "SQL",
    difficulty: "심화",
    tags: ["sql", "database", "윈도우함수", "순위", "calculation"],
    prompt: "점수가 90, 90, 80인 세 행에 DENSE_RANK() OVER (ORDER BY score DESC)를 적용했을 때 순위를 순서대로 쓰시오.",
    answer: "1, 1, 2",
    hint: "동점 다음 순위가 건너뛰어지는지 확인하세요.",
    explanation: "90점 두 행은 공동 1위이고 DENSE_RANK는 다음 순위를 건너뛰지 않아 80점이 2위입니다.",
    confusion: "RANK라면 1, 1, 3이고 ROW_NUMBER라면 동점도 1, 2처럼 서로 다른 번호를 가집니다."
  },
  {
    id: "sql-coalesce-01",
    kind: "sql",
    topic: "SQL",
    difficulty: "기초",
    tags: ["sql", "database", "null", "함수"],
    prompt: "BONUS 값이 NULL이면 0으로 표시하도록 조회하는 표준 SQL 표현을 쓰시오.",
    answer: "COALESCE(BONUS, 0)",
    hint: "여러 인수 중 첫 번째 NULL이 아닌 값을 반환하는 함수입니다.",
    explanation: "COALESCE는 BONUS가 NULL이 아니면 BONUS를, NULL이면 다음 인수 0을 반환합니다.",
    confusion: "DBMS별 NVL이나 IFNULL 대신 표준 SQL에서는 COALESCE를 사용할 수 있습니다."
  },
  {
    id: "sql-rollback-01",
    kind: "sql",
    topic: "SQL",
    difficulty: "실전",
    tags: ["sql", "database", "transaction", "rollback"],
    prompt: "COMMIT 이후 UPDATE를 수행했지만 아직 다시 COMMIT하지 않은 상태에서 ROLLBACK을 실행하면 UPDATE 내용은 어떻게 되는지 쓰시오.",
    answer: "마지막 COMMIT 이후의 UPDATE가 취소된다.",
    hint: "ROLLBACK이 되돌리는 기준점은 마지막 확정 시점입니다.",
    explanation: "COMMIT으로 확정된 이전 내용은 유지되고 그 이후 아직 확정되지 않은 변경만 취소됩니다.",
    confusion: "이미 COMMIT된 변경은 일반적인 ROLLBACK으로 되돌릴 수 없습니다."
  },
  {
    id: "sql-between-01",
    kind: "sql",
    topic: "SQL",
    difficulty: "기초",
    tags: ["sql", "database", "between", "조건"],
    prompt: "WHERE score BETWEEN 60 AND 80 조건에 score가 60 또는 80인 행이 포함되는지 쓰시오.",
    answer: "둘 다 포함된다.",
    hint: "BETWEEN의 양쪽 경곗값 포함 여부를 떠올리세요.",
    explanation: "BETWEEN 60 AND 80은 일반적으로 score >= 60 AND score <= 80과 같아 양 끝값을 포함합니다.",
    confusion: "날짜와 시각에서는 종료일의 시간값 때문에 예상과 다른 결과가 날 수 있어 범위를 명시적으로 작성하기도 합니다."
  },
  {
    id: "db-2nf-02",
    kind: "concept",
    topic: "데이터베이스",
    difficulty: "실전",
    tags: ["database", "db", "정규화", "2nf"],
    prompt: "제2정규형(2NF)이 제거하는 함수적 종속의 유형을 쓰시오.",
    answer: "부분 함수 종속",
    hint: "복합 기본키의 일부에만 종속되는 속성을 생각하세요.",
    explanation: "2NF는 기본키가 복합키일 때 일반 속성이 키 전체가 아닌 일부에만 의존하는 부분 함수 종속을 제거합니다.",
    confusion: "3NF는 이행 함수 종속을 제거하고 2NF는 부분 함수 종속을 제거합니다."
  },
  {
    id: "db-bcnf-01",
    kind: "choice",
    topic: "데이터베이스",
    difficulty: "심화",
    tags: ["database", "db", "정규화", "bcnf"],
    prompt: "BCNF를 만족하기 위한 조건으로 가장 알맞은 것을 고르시오.",
    choices: ["① 모든 결정자가 후보키이다", "② 모든 속성이 원자값이다", "③ 이행 종속만 제거한다", "④ 외래키를 제거한다"],
    answer: "① 모든 결정자가 후보키이다",
    hint: "BCNF는 결정자의 자격을 더 엄격하게 봅니다.",
    explanation: "BCNF에서는 모든 의미 있는 함수 종속 X→Y의 결정자 X가 후보키여야 합니다.",
    confusion: "원자값은 1NF 조건이고 이행 종속 제거는 3NF의 핵심 설명입니다."
  },
  {
    id: "db-isolation-01",
    kind: "choice",
    topic: "데이터베이스",
    difficulty: "실전",
    tags: ["database", "db", "transaction", "격리수준"],
    prompt: "다른 트랜잭션이 아직 COMMIT하지 않은 값을 읽는 현상을 고르시오.",
    choices: ["① Dirty Read", "② Lost Update", "③ Phantom Read", "④ Deadlock"],
    answer: "① Dirty Read",
    hint: "확정되지 않아 오염된 값을 읽는다는 의미입니다.",
    explanation: "Dirty Read는 한 트랜잭션이 다른 트랜잭션의 미확정 변경 내용을 읽는 현상입니다.",
    confusion: "Non-repeatable Read는 같은 행을 다시 읽었을 때 값이 달라지는 현상입니다."
  },
  {
    id: "db-anomaly-01",
    kind: "concept",
    topic: "데이터베이스",
    difficulty: "기초",
    tags: ["database", "db", "정규화", "이상현상"],
    prompt: "중복 저장된 같은 정보 중 일부만 변경되어 데이터가 서로 불일치하게 되는 이상 현상을 쓰시오.",
    answer: "갱신 이상(Update Anomaly)",
    hint: "삽입·삭제·갱신 이상 중 변경 작업과 관련됩니다.",
    explanation: "중복 데이터의 일부 행만 수정하면 같은 사실을 나타내는 값이 달라지는 갱신 이상이 발생합니다.",
    confusion: "삽입 이상은 불필요한 정보 없이는 삽입하기 어렵고 삭제 이상은 삭제 시 필요한 정보까지 사라지는 현상입니다."
  },
  {
    id: "db-candidate-key-02",
    kind: "concept",
    topic: "데이터베이스",
    difficulty: "기초",
    tags: ["database", "db", "key", "후보키"],
    prompt: "후보키가 만족해야 하는 두 가지 성질을 쓰시오.",
    answer: "유일성과 최소성",
    hint: "튜플을 하나로 식별할 수 있어야 하며 불필요한 속성이 없어야 합니다.",
    explanation: "후보키는 모든 행을 유일하게 식별하는 유일성과 속성을 더 줄일 수 없는 최소성을 모두 만족합니다.",
    confusion: "슈퍼키는 유일성만 만족해도 되므로 불필요한 속성을 포함할 수 있습니다."
  },
  {
    id: "sec-csrf-01",
    kind: "choice",
    topic: "보안",
    difficulty: "실전",
    tags: ["security", "보안", "csrf", "웹"],
    prompt: "로그인된 사용자의 권한을 이용해 사용자가 의도하지 않은 요청을 보내게 하는 공격을 고르시오.",
    choices: ["① CSRF", "② XSS", "③ SQL Injection", "④ Sniffing"],
    answer: "① CSRF",
    hint: "위조된 요청이 사용자의 인증 상태를 악용합니다.",
    explanation: "CSRF는 공격자가 사용자의 브라우저로 인증된 사이트에 원치 않는 요청을 보내게 합니다.",
    confusion: "XSS는 신뢰한 사이트에 악성 스크립트를 삽입해 사용자의 브라우저에서 실행시키는 공격입니다."
  },
  {
    id: "sec-salt-01",
    kind: "concept",
    topic: "보안",
    difficulty: "기초",
    tags: ["security", "보안", "hash", "salt"],
    prompt: "비밀번호 해시 전에 사용자별 임의 값을 추가하여 같은 비밀번호도 다른 해시가 나오게 하는 값을 쓰시오.",
    answer: "솔트(Salt)",
    hint: "레인보우 테이블 공격을 어렵게 만드는 임의 값입니다.",
    explanation: "솔트는 비밀번호와 함께 해시되어 동일한 비밀번호의 해시를 서로 다르게 만들고 사전 계산 공격을 어렵게 합니다.",
    confusion: "솔트는 숨겨야 하는 암호키라기보다 사용자별로 충분히 무작위인 값이어야 합니다."
  },
  {
    id: "sec-asymmetric-01",
    kind: "choice",
    topic: "보안",
    difficulty: "기초",
    tags: ["security", "보안", "암호", "공개키"],
    prompt: "공개키 암호 방식의 특징으로 가장 알맞은 것을 고르시오.",
    choices: ["① 암호화와 복호화에 서로 다른 키 쌍을 사용한다", "② 항상 대칭키보다 빠르다", "③ 키 배송 문제가 전혀 없다", "④ 해시와 동일한 단방향 함수이다"],
    answer: "① 암호화와 복호화에 서로 다른 키 쌍을 사용한다",
    hint: "공개키와 개인키의 관계를 떠올리세요.",
    explanation: "공개키 방식은 수학적으로 연결된 공개키와 개인키를 사용해 암호화·복호화 또는 서명·검증을 수행합니다.",
    confusion: "대용량 데이터는 빠른 대칭키로 처리하고 공개키 방식은 주로 키 교환과 서명에 함께 사용합니다."
  },
  {
    id: "sec-prepared-01",
    kind: "concept",
    topic: "보안",
    difficulty: "실전",
    tags: ["security", "보안", "sql injection", "secure coding"],
    prompt: "SQL Injection을 막기 위해 SQL 구조와 사용자 입력값을 분리하여 전달하는 대표적인 기법을 쓰시오.",
    answer: "Prepared Statement(매개변수화 쿼리)",
    hint: "입력값을 SQL 문자열에 직접 이어 붙이지 않습니다.",
    explanation: "Prepared Statement는 쿼리 구조를 먼저 확정하고 값은 매개변수로 바인딩하여 입력이 SQL 문법으로 해석되지 않게 합니다.",
    confusion: "입력 길이 제한이나 특수문자 제거만으로는 다양한 우회 공격을 완전히 막기 어렵습니다."
  },
  {
    id: "sec-least-privilege-01",
    kind: "choice",
    topic: "보안",
    difficulty: "기초",
    tags: ["security", "보안", "접근통제", "권한"],
    prompt: "사용자와 프로세스에 업무 수행에 필요한 최소 권한만 부여하는 원칙을 고르시오.",
    choices: ["① 최소 권한 원칙", "② 완전 중재 원칙", "③ 개방 설계 원칙", "④ 직무 순환 원칙"],
    answer: "① 최소 권한 원칙",
    hint: "침해 사고가 나더라도 피해 범위를 줄이는 권한 부여 방식입니다.",
    explanation: "최소 권한 원칙은 필요한 작업 범위에 한정해 권한을 주어 오용과 침해의 영향을 줄입니다.",
    confusion: "직무 분리는 한 사람이 상충하는 중요 업무를 모두 수행하지 못하게 하는 통제입니다."
  },
  {
    id: "net-handshake-01",
    kind: "concept",
    topic: "네트워크",
    difficulty: "기초",
    tags: ["network", "네트워크", "tcp", "연결"],
    prompt: "TCP 3-way handshake에서 교환되는 제어 플래그를 순서대로 쓰시오.",
    answer: "SYN → SYN/ACK → ACK",
    hint: "연결 요청, 요청 수락과 응답, 최종 확인 순서입니다.",
    explanation: "클라이언트가 SYN을 보내고 서버가 SYN과 ACK로 응답한 뒤 클라이언트가 ACK를 보내 연결을 확립합니다.",
    confusion: "연결 종료는 일반적으로 FIN과 ACK를 주고받는 4-way handshake로 설명합니다."
  },
  {
    id: "net-cidr-01",
    kind: "concept",
    topic: "네트워크",
    difficulty: "실전",
    tags: ["network", "네트워크", "ip", "subnet", "calculation"],
    prompt: "IPv4 /27 서브넷에서 네트워크 주소와 브로드캐스트 주소를 제외하고 사용할 수 있는 호스트 주소의 개수를 쓰시오.",
    answer: "30개",
    hint: "호스트 비트는 32-27개입니다.",
    explanation: "호스트 비트가 5개이므로 전체 주소는 2⁵=32개이고 네트워크·브로드캐스트 주소를 빼면 30개입니다.",
    confusion: "일반적인 서브넷 호스트 계산은 2^호스트비트 - 2이지만 /31 등 특수 용도는 예외가 있습니다."
  },
  {
    id: "net-dns-01",
    kind: "choice",
    topic: "네트워크",
    difficulty: "기초",
    tags: ["network", "네트워크", "dns", "port"],
    prompt: "DNS가 기본적으로 사용하는 포트 번호를 고르시오.",
    choices: ["① 22", "② 53", "③ 80", "④ 443"],
    answer: "② 53",
    hint: "도메인 이름을 IP 주소로 해석하는 서비스의 포트입니다.",
    explanation: "DNS는 일반 질의에 UDP 53번을 주로 사용하고 영역 전송이나 큰 응답 등에는 TCP 53번도 사용합니다.",
    confusion: "22는 SSH, 80은 HTTP, 443은 HTTPS의 대표 포트입니다."
  },
  {
    id: "net-arp-01",
    kind: "concept",
    topic: "네트워크",
    difficulty: "기초",
    tags: ["network", "네트워크", "arp", "주소"],
    prompt: "같은 네트워크에서 IPv4 주소에 대응하는 MAC 주소를 알아내는 프로토콜을 쓰시오.",
    answer: "ARP(Address Resolution Protocol)",
    hint: "논리 주소를 물리 주소로 대응시킵니다.",
    explanation: "ARP는 대상 IPv4 주소를 가진 장치의 MAC 주소를 질의하고 응답받아 ARP 캐시에 저장합니다.",
    confusion: "RARP는 반대 방향의 오래된 프로토콜이며 현재 주소 자동 설정에는 DHCP가 널리 사용됩니다."
  },
  {
    id: "os-fcfs-01",
    kind: "concept",
    topic: "운영체제",
    difficulty: "실전",
    tags: ["os", "운영체제", "스케줄링", "fcfs", "calculation"],
    prompt: "모든 프로세스가 동시에 도착하고 실행시간이 P1=3, P2=5, P3=2일 때 FCFS 순서가 P1→P2→P3이면 평균 대기시간을 쓰시오.",
    answer: "11/3 ≈ 3.67",
    hint: "각 대기시간은 0, 앞 프로세스 1개의 실행시간, 앞 프로세스 2개의 실행시간입니다.",
    explanation: "대기시간은 P1=0, P2=3, P3=3+5=8이고 평균은 (0+3+8)/3=11/3입니다.",
    confusion: "반환시간은 대기시간+실행시간이며 평균 대기시간과 다릅니다."
  },
  {
    id: "os-semaphore-01",
    kind: "choice",
    topic: "운영체제",
    difficulty: "기초",
    tags: ["os", "운영체제", "동기화", "세마포어"],
    prompt: "세마포어 값을 감소시키고 자원을 사용할 수 없으면 프로세스를 대기시키는 연산을 고르시오.",
    choices: ["① wait(P)", "② signal(V)", "③ fork", "④ dispatch"],
    answer: "① wait(P)",
    hint: "자원 획득을 요청하는 연산입니다.",
    explanation: "wait 또는 P 연산은 세마포어를 감소시키며 자원이 없을 때 대기하게 합니다. signal 또는 V는 반납을 알립니다.",
    confusion: "wait와 signal은 임계구역 상호배제와 프로세스 동기화에 사용됩니다."
  },
  {
    id: "os-fifo-page-01",
    kind: "concept",
    topic: "운영체제",
    difficulty: "실전",
    tags: ["os", "운영체제", "페이지", "fifo", "calculation"],
    prompt: "페이지 프레임이 3개이고 참조열이 1, 2, 3, 1, 4일 때 FIFO 페이지 교체에서 발생하는 페이지 부재 횟수를 쓰시오.",
    answer: "4회",
    hint: "처음 1, 2, 3은 모두 부재이고 다시 나온 1은 적중입니다.",
    explanation: "1·2·3을 처음 적재할 때 3회, 1은 적중, 4가 들어오며 가장 먼저 들어온 1을 교체해 총 4회입니다.",
    confusion: "FIFO는 최근 사용 시점이 아니라 메모리에 들어온 순서만 봅니다."
  },
  {
    id: "os-state-01",
    kind: "choice",
    topic: "운영체제",
    difficulty: "기초",
    tags: ["os", "운영체제", "프로세스", "상태"],
    prompt: "CPU를 할당받을 준비는 되었지만 아직 실행하지 않는 프로세스 상태를 고르시오.",
    choices: ["① Ready", "② Running", "③ Blocked", "④ Terminated"],
    answer: "① Ready",
    hint: "CPU만 기다리는 상태입니다.",
    explanation: "Ready 상태는 실행에 필요한 준비를 마치고 스케줄러의 CPU 할당을 기다립니다.",
    confusion: "Blocked 또는 Waiting은 입출력 완료나 특정 사건을 기다리는 상태입니다."
  },
  {
    id: "test-decision-02",
    kind: "choice",
    topic: "애플리케이션 테스트",
    difficulty: "실전",
    tags: ["test", "테스트", "coverage", "whitebox"],
    prompt: "각 조건문의 전체 결과가 참과 거짓을 최소 한 번씩 갖도록 테스트하는 커버리지를 고르시오.",
    choices: ["① 문장 커버리지", "② 결정 커버리지", "③ 조건 커버리지", "④ 변경 조건/결정 커버리지"],
    answer: "② 결정 커버리지",
    hint: "분기 전체 결과의 두 방향을 실행합니다.",
    explanation: "결정 커버리지는 각 결정식의 참·거짓 결과를 최소 한 번씩 수행하도록 테스트합니다.",
    confusion: "조건 커버리지는 결정식 내부의 개별 조건이 참·거짓을 갖는지 확인합니다."
  },
  {
    id: "se-factory-01",
    kind: "choice",
    topic: "소프트웨어 공학",
    difficulty: "실전",
    tags: ["software", "설계", "디자인패턴", "factory"],
    prompt: "객체 생성 인터페이스는 상위 타입에 두고 실제 생성할 클래스의 결정은 하위 클래스에 맡기는 패턴을 고르시오.",
    choices: ["① Factory Method", "② Observer", "③ Adapter", "④ Command"],
    answer: "① Factory Method",
    hint: "생성 책임을 서브클래스의 메서드로 위임합니다.",
    explanation: "Factory Method는 객체 생성 메서드를 추상화하고 하위 클래스가 구체 객체의 생성 방식을 결정하게 합니다.",
    confusion: "Abstract Factory는 관련 객체군을 생성하는 인터페이스를 제공하는 별도의 생성 패턴입니다."
  },
  {
    id: "uml-activity-01",
    kind: "concept",
    topic: "소프트웨어 공학",
    difficulty: "기초",
    tags: ["software", "설계", "uml", "activity"],
    prompt: "업무 처리나 알고리즘의 제어 흐름을 시작·종료·분기·병렬 처리 등으로 표현하는 UML 다이어그램을 쓰시오.",
    answer: "액티비티 다이어그램(Activity Diagram)",
    hint: "순서도와 비슷하게 활동의 흐름을 표현합니다.",
    explanation: "액티비티 다이어그램은 활동과 전이, 조건 분기, 병렬 흐름을 사용해 프로세스의 동적 흐름을 나타냅니다.",
    confusion: "시퀀스 다이어그램은 객체 사이 메시지의 시간 순서를 중심으로 표현합니다."
  },
  {
    id: "rest-idempotent-01",
    kind: "choice",
    topic: "인터페이스",
    difficulty: "실전",
    tags: ["software", "interface", "rest", "http"],
    prompt: "같은 요청을 여러 번 수행해도 서버의 최종 상태가 한 번 수행했을 때와 같은 성질을 고르시오.",
    choices: ["① 멱등성", "② 무상태성", "③ 캐시 가능성", "④ 계층화"],
    answer: "① 멱등성",
    hint: "PUT과 DELETE의 대표적인 성질로 설명됩니다.",
    explanation: "멱등성은 동일 요청을 한 번 또는 여러 번 적용해도 의도된 최종 상태가 같다는 성질입니다.",
    confusion: "무상태성은 서버가 요청 사이의 클라이언트 문맥을 저장하지 않는다는 REST 제약입니다."
  },
  {
    id: "se-cohesion-order-02",
    kind: "concept",
    topic: "소프트웨어 공학",
    difficulty: "실전",
    tags: ["software", "설계", "응집도", "모듈"],
    prompt: "모듈 응집도 중 가장 강한 것과 가장 약한 것을 각각 쓰시오.",
    answer: "가장 강함: 기능적 응집도, 가장 약함: 우연적 응집도",
    hint: "하나의 명확한 기능만 수행하는 경우와 관련 없는 기능이 모인 경우를 비교하세요.",
    explanation: "기능적 응집도는 모듈의 모든 요소가 하나의 기능 수행에 기여해 가장 강하고, 우연적 응집도는 관련 없는 요소가 모여 가장 약합니다.",
    confusion: "좋은 설계는 응집도를 높이고 모듈 사이 결합도를 낮추는 방향입니다."
  }
];
