import type { StudyQuestion } from "../types";

export const FUNDAMENTAL_QUESTIONS: StudyQuestion[] = [
  {
    id: "ds-stack-01",
    kind: "choice",
    topic: "자료구조",
    difficulty: "기초",
    tags: ["data-structure", "자료구조", "stack"],
    prompt: "스택(Stack)의 데이터 입출력 원칙을 고르시오.",
    choices: ["① LIFO", "② FIFO", "③ 무작위 접근만 가능", "④ 항상 정렬된 순서"],
    answer: "① LIFO",
    hint: "가장 나중에 들어온 데이터가 가장 먼저 나옵니다.",
    explanation: "스택은 Last In First Out 구조로 push한 데이터 중 가장 최근 데이터를 pop으로 먼저 꺼냅니다.",
    confusion: "큐는 먼저 들어온 데이터가 먼저 나오는 FIFO 구조입니다."
  },
  {
    id: "ds-queue-01",
    kind: "concept",
    topic: "자료구조",
    difficulty: "기초",
    tags: ["data-structure", "자료구조", "queue"],
    prompt: "데이터가 들어온 순서대로 처리되는 First In First Out 자료구조를 쓰시오.",
    answer: "큐(Queue)",
    hint: "대기열처럼 먼저 온 데이터가 먼저 처리됩니다.",
    explanation: "큐는 rear에서 삽입하고 front에서 삭제하여 먼저 들어온 원소가 먼저 나갑니다.",
    confusion: "우선순위 큐는 단순 도착 순서가 아니라 우선순위에 따라 원소를 꺼냅니다."
  },
  {
    id: "ds-tree-traversal-01",
    kind: "concept",
    topic: "자료구조",
    difficulty: "실전",
    tags: ["data-structure", "자료구조", "tree", "calculation"],
    prompt: "루트 A의 왼쪽 자식이 B, 오른쪽 자식이 C일 때 이진트리를 전위 순회한 결과를 쓰시오.",
    answer: "A, B, C",
    hint: "전위 순회는 루트부터 방문합니다.",
    explanation: "전위 순회 순서는 루트→왼쪽 부분트리→오른쪽 부분트리이므로 A, B, C입니다.",
    confusion: "중위 순회는 B, A, C이고 후위 순회는 B, C, A입니다."
  },
  {
    id: "ds-bst-01",
    kind: "choice",
    topic: "자료구조",
    difficulty: "실전",
    tags: ["data-structure", "자료구조", "tree", "bst"],
    prompt: "이진 탐색 트리의 일반적인 저장 규칙으로 가장 알맞은 것을 고르시오.",
    choices: ["① 왼쪽에는 작은 키, 오른쪽에는 큰 키를 둔다", "② 모든 노드는 자식을 정확히 두 개 가져야 한다", "③ 루트가 항상 최솟값이다", "④ 삽입 순서와 관계없이 항상 완전 균형을 이룬다"],
    answer: "① 왼쪽에는 작은 키, 오른쪽에는 큰 키를 둔다",
    hint: "각 노드를 기준으로 키의 대소 관계를 유지합니다.",
    explanation: "이진 탐색 트리는 보통 각 노드보다 작은 키를 왼쪽, 큰 키를 오른쪽 부분트리에 배치합니다.",
    confusion: "일반 이진 탐색 트리는 자동으로 균형을 보장하지 않아 한쪽으로 치우칠 수 있습니다."
  },
  {
    id: "ds-hash-collision-01",
    kind: "concept",
    topic: "자료구조",
    difficulty: "심화",
    tags: ["data-structure", "자료구조", "hash", "algorithm"],
    prompt: "서로 다른 키를 해시 함수에 넣었지만 같은 해시 주소가 계산되는 현상을 쓰시오.",
    answer: "해시 충돌(Hash Collision)",
    hint: "체이닝이나 개방 주소법으로 처리할 수 있습니다.",
    explanation: "해시 충돌은 서로 다른 키가 같은 버킷이나 주소에 매핑되는 현상이며 별도의 충돌 해결 전략이 필요합니다.",
    confusion: "좋은 해시 함수는 충돌 가능성을 줄이지만 유한한 테이블에서는 충돌을 완전히 없애기 어렵습니다."
  },
  {
    id: "ds-graph-bfs-01",
    kind: "choice",
    topic: "자료구조",
    difficulty: "기초",
    tags: ["data-structure", "자료구조", "graph", "algorithm"],
    prompt: "그래프의 너비 우선 탐색(BFS)을 구현할 때 주로 사용하는 자료구조를 고르시오.",
    choices: ["① Queue", "② Stack", "③ Heap만 사용", "④ Hash 함수만 사용"],
    answer: "① Queue",
    hint: "가까운 정점을 먼저 방문한 순서를 유지합니다.",
    explanation: "BFS는 발견한 정점을 큐에 넣고 먼저 발견한 정점부터 꺼내 인접 정점을 탐색합니다.",
    confusion: "DFS는 재귀 호출이나 스택을 이용해 한 경로를 깊게 탐색합니다."
  },
  {
    id: "ds-heap-01",
    kind: "choice",
    topic: "자료구조",
    difficulty: "실전",
    tags: ["data-structure", "자료구조", "heap", "tree"],
    prompt: "최대 힙(Max Heap)의 조건으로 가장 알맞은 것을 고르시오.",
    choices: ["① 부모 키가 자식 키보다 크거나 같다", "② 왼쪽 자식만 가질 수 있다", "③ 중위 순회하면 항상 오름차순이다", "④ 루트가 최솟값이다"],
    answer: "① 부모 키가 자식 키보다 크거나 같다",
    hint: "가장 큰 값이 루트에 위치합니다.",
    explanation: "최대 힙은 완전 이진트리 형태이며 각 부모의 키가 자식 키보다 크거나 같아 루트가 최댓값입니다.",
    confusion: "힙은 형제나 서로 다른 부분트리 사이의 전체 정렬 순서까지 보장하지 않습니다."
  },
  {
    id: "ds-circular-queue-01",
    kind: "concept",
    topic: "자료구조",
    difficulty: "실전",
    tags: ["data-structure", "자료구조", "queue", "circular"],
    prompt: "배열의 마지막 위치 다음을 첫 위치와 연결해 빈 공간을 재사용하는 큐를 쓰시오.",
    answer: "원형 큐(Circular Queue)",
    hint: "front와 rear를 나머지 연산으로 순환시킵니다.",
    explanation: "원형 큐는 배열을 논리적으로 원형으로 연결해 삭제로 생긴 앞부분 공간을 다시 사용합니다.",
    confusion: "선형 큐는 rear가 끝에 도달하면 앞쪽이 비어 있어도 단순 구현에서는 더 삽입하지 못할 수 있습니다."
  },
  {
    id: "ds-postfix-01",
    kind: "concept",
    topic: "자료구조",
    difficulty: "심화",
    tags: ["data-structure", "자료구조", "stack", "calculation"],
    prompt: "후위 표기식 `5 2 + 3 *`의 계산 결과를 쓰시오.",
    answer: "21",
    hint: "5와 2를 더한 결과에 3을 곱합니다.",
    explanation: "5와 2를 스택에서 꺼내 더해 7을 넣고, 다시 7과 3을 곱해 21을 얻습니다.",
    confusion: "후위 표기식에서는 연산자를 만났을 때 피연산자를 꺼내며 괄호가 필요하지 않습니다."
  },
  {
    id: "ds-linked-list-01",
    kind: "choice",
    topic: "자료구조",
    difficulty: "기초",
    tags: ["data-structure", "자료구조", "linked-list"],
    prompt: "연결 리스트의 일반적인 특징으로 가장 알맞은 것을 고르시오.",
    choices: ["① 노드가 다음 노드의 주소를 저장할 수 있다", "② 모든 원소가 반드시 연속된 메모리에 있어야 한다", "③ 임의 위치 접근이 항상 O(1)이다", "④ 포인터나 참조가 필요 없다"],
    answer: "① 노드가 다음 노드의 주소를 저장할 수 있다",
    hint: "데이터와 연결 정보를 가진 노드로 구성됩니다.",
    explanation: "연결 리스트는 각 노드가 데이터와 다른 노드를 가리키는 연결 정보를 저장해 비연속 메모리에서도 순서를 구성합니다.",
    confusion: "배열은 인덱스로 빠르게 접근하지만 연결 리스트는 보통 앞에서부터 순차 탐색해야 합니다."
  },
  {
    id: "algo-bubble-01",
    kind: "concept",
    topic: "알고리즘",
    difficulty: "기초",
    tags: ["algorithm", "알고리즘", "sort", "calculation"],
    prompt: "배열 [4, 2, 3, 1]에 오름차순 버블 정렬의 첫 번째 전체 패스를 수행한 결과를 쓰시오.",
    answer: "[2, 3, 1, 4]",
    hint: "인접한 두 수를 왼쪽부터 비교해 큰 수를 오른쪽으로 이동시킵니다.",
    explanation: "4와 2, 4와 3, 4와 1을 차례로 교환하여 가장 큰 4가 마지막으로 이동합니다.",
    confusion: "첫 패스만으로 전체 배열이 정렬되는 것은 아니며 최댓값 하나의 위치가 확정됩니다."
  },
  {
    id: "algo-binary-search-01",
    kind: "concept",
    topic: "알고리즘",
    difficulty: "실전",
    tags: ["algorithm", "알고리즘", "search", "calculation"],
    prompt: "정렬된 배열 [1, 3, 5, 7, 9, 11, 13]에서 이진 탐색으로 11을 찾을 때 비교되는 값을 순서대로 쓰시오.",
    answer: "7, 11",
    hint: "먼저 가운데 값 7과 비교한 뒤 오른쪽 절반의 가운데를 봅니다.",
    explanation: "가운데 7보다 11이 크므로 오른쪽 구간 [9,11,13]을 선택하고 그 가운데 11을 찾아 종료합니다.",
    confusion: "이진 탐색은 데이터가 정렬되어 있어야 올바르게 범위를 절반씩 줄일 수 있습니다."
  },
  {
    id: "algo-big-o-01",
    kind: "choice",
    topic: "알고리즘",
    difficulty: "기초",
    tags: ["algorithm", "알고리즘", "complexity", "calculation"],
    prompt: "각각 n번 반복되는 두 반복문이 중첩되어 내부 연산이 실행될 때 시간복잡도를 고르시오.",
    choices: ["① O(1)", "② O(log n)", "③ O(n)", "④ O(n²)"],
    answer: "④ O(n²)",
    hint: "바깥 반복 한 번마다 안쪽 반복이 n번 실행됩니다.",
    explanation: "전체 실행 횟수는 n×n에 비례하므로 시간복잡도는 O(n²)입니다.",
    confusion: "서로 이어진 반복문은 보통 실행 횟수를 더하지만 중첩 반복문은 곱합니다."
  },
  {
    id: "algo-quick-01",
    kind: "choice",
    topic: "알고리즘",
    difficulty: "심화",
    tags: ["algorithm", "알고리즘", "sort", "quick-sort"],
    prompt: "퀵 정렬의 핵심 동작으로 가장 알맞은 것을 고르시오.",
    choices: ["① 피벗을 기준으로 작은 값과 큰 값을 분할한다", "② 항상 인접 원소만 한 번 비교한다", "③ 추가 조건 없이 최악에도 항상 O(n log n)이다", "④ 키를 해시 주소로 변환한다"],
    answer: "① 피벗을 기준으로 작은 값과 큰 값을 분할한다",
    hint: "분할 정복과 피벗을 사용합니다.",
    explanation: "퀵 정렬은 피벗을 선택하고 원소를 피벗보다 작은 그룹과 큰 그룹으로 분할한 뒤 재귀적으로 정렬합니다.",
    confusion: "피벗 선택과 입력 상태에 따라 최악의 시간복잡도는 O(n²)가 될 수 있습니다."
  },
  {
    id: "algo-merge-01",
    kind: "concept",
    topic: "알고리즘",
    difficulty: "실전",
    tags: ["algorithm", "알고리즘", "sort", "merge-sort"],
    prompt: "합병 정렬(Merge Sort)의 일반적인 최악 시간복잡도를 쓰시오.",
    answer: "O(n log n)",
    hint: "배열을 절반으로 나누는 단계와 각 단계의 병합 비용을 곱합니다.",
    explanation: "log n개의 분할 단계마다 전체 n개 원소를 병합하므로 최악 시간복잡도도 O(n log n)입니다.",
    confusion: "합병 정렬은 안정 정렬이지만 배열 구현에서는 병합을 위한 추가 메모리가 필요할 수 있습니다."
  },
  {
    id: "algo-dijkstra-01",
    kind: "choice",
    topic: "알고리즘",
    difficulty: "심화",
    tags: ["algorithm", "알고리즘", "graph", "shortest-path"],
    prompt: "일반적인 다익스트라 알고리즘을 그대로 적용하기 어려운 그래프를 고르시오.",
    choices: ["① 음수 가중치 간선이 있는 그래프", "② 모든 가중치가 양수인 그래프", "③ 정점이 하나인 그래프", "④ 무방향 양수 가중치 그래프"],
    answer: "① 음수 가중치 간선이 있는 그래프",
    hint: "한 번 확정한 최단거리가 나중에 더 작아질 가능성을 생각하세요.",
    explanation: "다익스트라는 선택한 최단거리가 확정된다는 가정에 의존하므로 음수 간선이 있으면 일반적으로 올바른 결과를 보장하지 않습니다.",
    confusion: "음수 간선을 다룰 때는 벨만-포드 같은 알고리즘을 고려할 수 있습니다."
  },
  {
    id: "algo-greedy-01",
    kind: "concept",
    topic: "알고리즘",
    difficulty: "실전",
    tags: ["algorithm", "알고리즘", "greedy"],
    prompt: "매 단계에서 현재 상황에 가장 좋아 보이는 선택을 하여 해를 구성하는 알고리즘 기법을 쓰시오.",
    answer: "그리디 알고리즘(Greedy Algorithm, 탐욕법)",
    hint: "지역적으로 최적인 선택을 반복합니다.",
    explanation: "그리디 알고리즘은 각 단계의 최선 선택을 되돌리지 않고 이어가며 문제에 따라 전체 최적해를 얻습니다.",
    confusion: "모든 문제에서 지역 최적 선택이 전역 최적해를 보장하지 않으므로 그리디 선택 속성을 확인해야 합니다."
  },
  {
    id: "algo-recursion-02",
    kind: "code",
    topic: "알고리즘",
    difficulty: "기초",
    tags: ["algorithm", "알고리즘", "recursion", "calculation", "code", "python"],
    prompt: ["다음 Python 코드의 출력값을 쓰시오.", "```python", "def f(n):", "    return 1 if n <= 1 else n * f(n - 1)", "print(f(4))", "```"].join("\n"),
    answer: "24",
    hint: "4×3×2×1을 계산합니다.",
    explanation: "재귀 호출이 f(1)에서 1을 반환하고 2, 3, 4를 차례로 곱해 24가 됩니다.",
    confusion: "재귀 함수에는 호출을 끝내는 기저 조건이 반드시 필요합니다."
  },
  {
    id: "algo-dp-01",
    kind: "choice",
    topic: "알고리즘",
    difficulty: "심화",
    tags: ["algorithm", "알고리즘", "dynamic-programming"],
    prompt: "동적 계획법(DP)의 대표적인 특징으로 가장 알맞은 것을 고르시오.",
    choices: ["① 중복되는 부분 문제의 결과를 저장해 재사용한다", "② 항상 현재의 최선만 선택한다", "③ 정렬되지 않은 배열에는 사용할 수 없다", "④ 재귀를 절대 사용할 수 없다"],
    answer: "① 중복되는 부분 문제의 결과를 저장해 재사용한다",
    hint: "메모이제이션과 테이블 작성 방식을 떠올리세요.",
    explanation: "동적 계획법은 중복 부분 문제와 최적 부분 구조를 이용해 계산 결과를 저장하고 반복 계산을 줄입니다.",
    confusion: "그리디는 각 단계의 최선 선택을 사용하고 DP는 여러 부분 문제의 결과를 비교·조합할 수 있습니다."
  },
  {
    id: "algo-selection-count-01",
    kind: "concept",
    topic: "알고리즘",
    difficulty: "실전",
    tags: ["algorithm", "알고리즘", "sort", "calculation"],
    prompt: "원소가 5개인 배열을 기본 선택 정렬로 정렬할 때 원소 대소 비교 횟수를 쓰시오.",
    answer: "10회",
    hint: "4+3+2+1을 계산합니다.",
    explanation: "첫 위치에서 4회, 다음 위치에서 3회, 이어서 2회와 1회를 비교해 총 10회입니다.",
    confusion: "기본 선택 정렬의 비교 횟수는 입력 순서와 무관하게 n(n-1)/2입니다."
  },
  {
    id: "web-http-get-01",
    kind: "choice",
    topic: "웹/API",
    difficulty: "기초",
    tags: ["web", "api", "http", "method"],
    prompt: "HTTP GET 메서드의 일반적인 용도로 가장 알맞은 것을 고르시오.",
    choices: ["① 자원 조회", "② 자원 전체 교체만 가능", "③ 서버 프로세스 강제 종료", "④ 암호키 생성"],
    answer: "① 자원 조회",
    hint: "서버의 표현을 가져오는 안전한 메서드입니다.",
    explanation: "GET은 지정한 자원의 표현을 조회하는 데 사용하며 일반적으로 서버 상태를 변경하지 않는 안전한 메서드로 설계합니다.",
    confusion: "GET 요청에 부작용을 넣으면 캐시나 재시도 과정에서 예상치 못한 상태 변경이 생길 수 있습니다."
  },
  {
    id: "web-status-01",
    kind: "concept",
    topic: "웹/API",
    difficulty: "기초",
    tags: ["web", "api", "http", "status"],
    prompt: "HTTP에서 요청한 자원을 찾을 수 없음을 나타내는 상태 코드를 쓰시오.",
    answer: "404 Not Found",
    hint: "클라이언트 오류를 나타내는 4xx 코드입니다.",
    explanation: "404는 서버가 요청 URI에 해당하는 자원을 찾지 못했음을 나타냅니다.",
    confusion: "403은 자원은 이해했지만 접근을 거부한 경우이고 500은 서버 내부 오류입니다."
  },
  {
    id: "web-cookie-session-01",
    kind: "choice",
    topic: "웹/API",
    difficulty: "실전",
    tags: ["web", "http", "cookie", "session"],
    prompt: "쿠키와 서버 세션의 관계로 가장 알맞은 것을 고르시오.",
    choices: ["① 브라우저 쿠키에 세션 식별자를 저장할 수 있다", "② 세션 데이터는 반드시 모두 브라우저에 저장한다", "③ 쿠키는 서버가 읽을 수 없다", "④ HTTP는 기본적으로 모든 요청의 상태를 자동 보관한다"],
    answer: "① 브라우저 쿠키에 세션 식별자를 저장할 수 있다",
    hint: "클라이언트는 식별자를 보내고 서버가 해당 세션 데이터를 찾습니다.",
    explanation: "일반적인 서버 세션 방식은 쿠키에 세션 ID를 두고 실제 세션 상태는 서버 저장소에서 관리합니다.",
    confusion: "쿠키와 세션은 반대 개념이 아니라 함께 사용될 수 있으며 민감한 정보를 쿠키에 직접 저장할 때는 보안을 고려해야 합니다."
  },
  {
    id: "web-cors-01",
    kind: "concept",
    topic: "웹/API",
    difficulty: "실전",
    tags: ["web", "api", "http", "cors"],
    prompt: "브라우저가 다른 출처의 자원 요청을 허용할지 서버의 HTTP 헤더를 통해 제어하는 체계를 쓰시오.",
    answer: "CORS(Cross-Origin Resource Sharing)",
    hint: "동일 출처 정책의 예외를 안전하게 허용합니다.",
    explanation: "CORS는 서버가 허용할 출처·메서드·헤더 등을 응답 헤더로 알려 브라우저의 교차 출처 요청을 제어합니다.",
    confusion: "CORS는 브라우저 보안 정책이며 서버 간 직접 요청에는 같은 방식으로 강제되지 않습니다."
  },
  {
    id: "api-rest-resource-01",
    kind: "choice",
    topic: "웹/API",
    difficulty: "기초",
    tags: ["api", "rest", "interface", "web"],
    prompt: "REST API URI 설계 예시로 가장 알맞은 것을 고르시오.",
    choices: ["① GET /users/10", "② GET /getUserById?id=10만 가능", "③ POST /deleteUser/10", "④ URI에 데이터베이스 비밀번호 포함"],
    answer: "① GET /users/10",
    hint: "URI는 자원을 나타내고 행위는 HTTP 메서드로 표현합니다.",
    explanation: "REST 스타일에서는 /users/10처럼 명사형 URI로 자원을 식별하고 GET·POST·PUT·DELETE 등 메서드로 행위를 표현합니다.",
    confusion: "REST는 URI 모양 하나만이 아니라 무상태성, 캐시, 계층화 같은 제약을 함께 포함합니다."
  },
  {
    id: "api-put-patch-01",
    kind: "concept",
    topic: "웹/API",
    difficulty: "실전",
    tags: ["api", "http", "method", "web"],
    prompt: "HTTP에서 자원의 일부 속성만 변경할 때 일반적으로 사용하는 메서드를 쓰시오.",
    answer: "PATCH",
    hint: "PUT은 자원의 전체 표현 교체 의미로 자주 사용됩니다.",
    explanation: "PATCH는 자원의 부분 변경을 표현하는 데 사용하며 PUT은 지정 URI의 자원을 전체 표현으로 교체하는 의미로 설계하는 경우가 많습니다.",
    confusion: "실제 API 계약에 따라 동작이 달라질 수 있으므로 서버 문서를 확인해야 합니다."
  },
  {
    id: "api-jwt-01",
    kind: "concept",
    topic: "웹/API",
    difficulty: "심화",
    tags: ["api", "security", "jwt", "web"],
    prompt: "일반적인 JWT의 세 부분을 순서대로 쓰시오.",
    answer: "Header, Payload, Signature",
    hint: "점(.)으로 구분되는 세 부분입니다.",
    explanation: "JWT는 알고리즘 등의 Header, 클레임을 담는 Payload, 무결성을 검증하는 Signature로 구성됩니다.",
    confusion: "서명된 JWT의 Payload는 기본적으로 암호화된 것이 아니므로 민감정보를 그대로 넣으면 안 됩니다."
  },
  {
    id: "web-websocket-01",
    kind: "choice",
    topic: "웹/API",
    difficulty: "실전",
    tags: ["web", "api", "websocket", "network"],
    prompt: "하나의 연결에서 클라이언트와 서버가 양방향으로 메시지를 주고받는 실시간 통신 기술을 고르시오.",
    choices: ["① WebSocket", "② DNS", "③ ARP", "④ FTP Passive Mode"],
    answer: "① WebSocket",
    hint: "HTTP 연결 업그레이드를 통해 지속적인 양방향 채널을 만들 수 있습니다.",
    explanation: "WebSocket은 연결을 유지하면서 클라이언트와 서버가 필요할 때 서로 메시지를 보낼 수 있는 전이중 통신을 지원합니다.",
    confusion: "일반 HTTP 요청·응답 반복과 달리 연결을 유지하므로 채팅이나 실시간 알림에 적합합니다."
  },
  {
    id: "linux-permission-01",
    kind: "concept",
    topic: "리눅스",
    difficulty: "실전",
    tags: ["linux", "리눅스", "permission", "calculation"],
    prompt: "리눅스 파일 권한 `rwxr-xr--`를 8진수 숫자로 쓰시오.",
    answer: "754",
    hint: "r=4, w=2, x=1을 사용자·그룹·기타 순서로 더합니다.",
    explanation: "소유자는 rwx=7, 그룹은 r-x=5, 기타 사용자는 r--=4이므로 754입니다.",
    confusion: "세 자리 숫자는 각각 소유자, 그룹, 기타 사용자의 권한을 나타냅니다."
  },
  {
    id: "linux-chmod-01",
    kind: "choice",
    topic: "리눅스",
    difficulty: "기초",
    tags: ["linux", "리눅스", "permission", "command"],
    prompt: "리눅스에서 파일 권한을 변경하는 명령어를 고르시오.",
    choices: ["① chmod", "② pwd", "③ ps", "④ grep"],
    answer: "① chmod",
    hint: "change mode의 약어입니다.",
    explanation: "chmod는 숫자 모드나 기호 모드를 사용해 파일과 디렉터리의 접근 권한을 변경합니다.",
    confusion: "chown은 소유자나 그룹을 변경하고 chmod는 권한 비트를 변경합니다."
  },
  {
    id: "linux-grep-01",
    kind: "concept",
    topic: "리눅스",
    difficulty: "기초",
    tags: ["linux", "리눅스", "command", "text"],
    prompt: "텍스트에서 지정한 패턴과 일치하는 행을 검색하는 리눅스 명령어를 쓰시오.",
    answer: "grep",
    hint: "로그에서 특정 단어가 포함된 줄을 찾을 때 자주 사용합니다.",
    explanation: "grep은 파일이나 표준 입력에서 문자열 또는 정규표현식 패턴에 일치하는 행을 출력합니다.",
    confusion: "find는 주로 파일명과 경로·속성으로 파일을 찾고 grep은 파일 내용의 패턴을 검색합니다."
  },
  {
    id: "linux-ps-01",
    kind: "choice",
    topic: "리눅스",
    difficulty: "기초",
    tags: ["linux", "리눅스", "process", "command"],
    prompt: "현재 실행 중인 프로세스 정보를 확인하는 대표 명령어를 고르시오.",
    choices: ["① ps", "② mkdir", "③ cp", "④ tar"],
    answer: "① ps",
    hint: "process status의 약어입니다.",
    explanation: "ps는 현재 프로세스의 PID, 상태, 실행 명령 등의 정보를 표시합니다.",
    confusion: "top은 프로세스와 자원 사용량을 지속적으로 갱신해 보여주는 대화형 도구입니다."
  },
  {
    id: "linux-pipe-01",
    kind: "concept",
    topic: "리눅스",
    difficulty: "기초",
    tags: ["linux", "리눅스", "shell", "pipe"],
    prompt: "앞 명령의 표준 출력을 뒤 명령의 표준 입력으로 연결하는 셸 기호를 쓰시오.",
    answer: "| (파이프)",
    hint: "`ps | grep node`처럼 사용합니다.",
    explanation: "파이프 기호는 한 명령의 출력을 다음 명령의 입력으로 전달해 작은 명령들을 조합할 수 있게 합니다.",
    confusion: ">는 출력을 파일로 덮어쓰고 >>는 파일 끝에 추가합니다."
  },
  {
    id: "linux-redirection-01",
    kind: "choice",
    topic: "리눅스",
    difficulty: "실전",
    tags: ["linux", "리눅스", "shell", "redirection"],
    prompt: "명령의 표준 출력을 기존 파일의 끝에 추가하는 리다이렉션 기호를 고르시오.",
    choices: ["① >", "② >>", "③ <", "④ |"],
    answer: "② >>",
    hint: "파일을 덮어쓰지 않고 이어서 기록합니다.",
    explanation: ">>는 표준 출력을 파일 뒤에 추가하고 >는 파일을 새로 만들거나 기존 내용을 덮어씁니다.",
    confusion: "파이프 |는 파일이 아니라 다른 명령의 표준 입력으로 출력을 전달합니다."
  },
  {
    id: "linux-signal-01",
    kind: "concept",
    topic: "리눅스",
    difficulty: "실전",
    tags: ["linux", "리눅스", "process", "signal"],
    prompt: "프로세스에 정상 종료를 요청하는 기본 `kill PID` 명령이 보내는 대표 시그널을 쓰시오.",
    answer: "SIGTERM(15)",
    hint: "강제 종료 SIGKILL보다 먼저 사용하는 정상 종료 요청입니다.",
    explanation: "인자를 생략한 kill은 일반적으로 SIGTERM을 보내 프로세스가 정리 작업 후 종료할 기회를 줍니다.",
    confusion: "SIGKILL(9)은 프로세스가 처리하거나 무시할 수 없는 강제 종료 신호이므로 마지막 수단으로 사용합니다."
  }
];
