import { PROGRAMMING_QUESTIONS } from "./프로그래밍";
import { DATABASE_SQL_QUESTIONS } from "./데이터베이스-SQL";
import { SOFTWARE_ENGINEERING_TEST_QUESTIONS } from "./소프트웨어공학-테스트";
import { SYSTEM_NETWORK_LINUX_QUESTIONS } from "./운영체제-네트워크-리눅스";
import { DATA_STRUCTURE_ALGORITHM_QUESTIONS } from "./자료구조-알고리즘";
import { WEB_API_INTERFACE_QUESTIONS } from "./웹-API-인터페이스";
import { SECURITY_QUESTIONS } from "./보안";
import { EMERGING_TECHNOLOGY_QUESTIONS } from "./신기술";
import { PRACTICAL_WORD_BANK_QUESTIONS } from "./실기형-보기";

export const INFORMATION_PROCESSING_ENGINEER_QUESTIONS = [
  ...PROGRAMMING_QUESTIONS,
  ...DATABASE_SQL_QUESTIONS,
  ...SOFTWARE_ENGINEERING_TEST_QUESTIONS,
  ...SYSTEM_NETWORK_LINUX_QUESTIONS,
  ...DATA_STRUCTURE_ALGORITHM_QUESTIONS,
  ...WEB_API_INTERFACE_QUESTIONS,
  ...SECURITY_QUESTIONS,
  ...EMERGING_TECHNOLOGY_QUESTIONS,
  ...PRACTICAL_WORD_BANK_QUESTIONS,
];
