import type { StudyQuestion } from "../types";

export const DATABASE_SQL_QUESTIONS: StudyQuestion[] = [
  {
    id: "sql-group-01",
    kind: "sql",
    topic: "SQL",
    difficulty: "실전",
    tags: ["sql", "group by", "having", "집계"],
    prompt: [
      "SALES(dept, amount) 테이블에서 부서별 판매 합계가 1000 이상인 부서와 합계를 조회하는 SQL을 쓰시오.",
      "결과는 합계가 큰 순서로 정렬한다."
    ].join("\n"),
    answer: "SELECT dept, SUM(amount) AS total FROM SALES GROUP BY dept HAVING SUM(amount) >= 1000 ORDER BY total DESC;",
    hint: "그룹을 만든 뒤 집계 결과를 거르는 절은 HAVING입니다.",
    explanation: "GROUP BY로 부서별 그룹을 만들고 SUM으로 합계를 구합니다. 집계 결과 조건은 WHERE가 아니라 HAVING에 작성합니다.",
    confusion: "WHERE는 그룹화 전 행을, HAVING은 그룹화 후 집계 결과를 필터링합니다."
  },
  {
    id: "sql-left-join-01",
    kind: "sql",
    topic: "SQL",
    difficulty: "실전",
    tags: ["sql", "join", "left join"],
    prompt: "DEPT(id, name)의 모든 부서와 EMP(dept_id)의 사원 수를 조회하되 사원이 없는 부서도 0명으로 표시하는 SQL을 쓰시오.",
    answer: "SELECT d.id, d.name, COUNT(e.dept_id) AS emp_count FROM DEPT d LEFT JOIN EMP e ON d.id = e.dept_id GROUP BY d.id, d.name;",
    hint: "기준 테이블의 모든 행을 남기는 외부 조인과 NULL을 세지 않는 COUNT(열)를 사용합니다.",
    explanation: "LEFT JOIN으로 모든 부서를 유지하고, COUNT(e.dept_id)는 일치하는 사원이 없는 NULL을 제외해 0을 반환합니다.",
    confusion: "COUNT(*)를 쓰면 외부 조인으로 남은 행까지 세어 사원 없는 부서가 1로 나올 수 있습니다."
  },
  {
    id: "sql-null-01",
    kind: "sql",
    topic: "SQL",
    difficulty: "실전",
    tags: ["sql", "null", "count", "집계"],
    prompt: [
      "SCORE 테이블의 score 값이 80, NULL, 90일 때 다음 결과를 순서대로 쓰시오.",
      "```sql",
      "SELECT COUNT(*), COUNT(score), AVG(score) FROM SCORE;",
      "```"
    ].join("\n"),
    answer: "3, 2, 85",
    hint: "COUNT(*)와 달리 대부분의 집계 함수는 NULL을 제외합니다.",
    explanation: "전체 행은 3개, NULL이 아닌 score는 2개입니다. 평균도 NULL을 제외해 (80+90)/2=85입니다.",
    confusion: "NULL은 0이 아니라 값이 없거나 알 수 없음을 의미합니다."
  },
  {
    id: "sql-case-01",
    kind: "sql",
    topic: "SQL",
    difficulty: "실전",
    tags: ["sql", "case", "update"],
    prompt: "EMP 테이블에서 grade가 'A'인 직원의 salary는 10%, 나머지는 5% 인상하는 UPDATE문을 CASE를 사용해 쓰시오.",
    answer: "UPDATE EMP SET salary = salary * CASE WHEN grade = 'A' THEN 1.10 ELSE 1.05 END;",
    hint: "SET 절의 새 값을 CASE 표현식으로 계산합니다.",
    explanation: "CASE가 각 행의 grade를 검사해 서로 다른 인상률을 반환하고 기존 salary에 곱합니다.",
    confusion: "CASE는 문장이 아니라 하나의 값을 반환하는 표현식으로 사용할 수 있습니다."
  },
  {
    id: "sql-union-01",
    kind: "choice",
    topic: "SQL",
    difficulty: "기초",
    tags: ["sql", "union", "보기"],
    prompt: "두 SELECT 결과를 합치면서 중복 행도 그대로 유지하려고 한다. 알맞은 연산자를 고르시오.",
    choices: ["① UNION", "② UNION ALL", "③ INTERSECT", "④ DISTINCT"],
    answer: "② UNION ALL",
    hint: "ALL이 붙으면 중복 제거 과정을 수행하지 않습니다.",
    explanation: "UNION은 중복을 제거하고 UNION ALL은 중복을 포함해 모든 행을 합칩니다.",
    confusion: "DISTINCT는 단일 SELECT 결과의 중복 제거에 사용합니다."
  },
  {
    id: "sql-grant-01",
    kind: "sql",
    topic: "SQL",
    difficulty: "기초",
    tags: ["sql", "dcl", "grant"],
    prompt: "사용자 KIM에게 EMP 테이블의 조회 권한을 부여하는 SQL을 쓰시오.",
    answer: "GRANT SELECT ON EMP TO KIM;",
    hint: "권한 부여는 GRANT, 회수는 REVOKE입니다.",
    explanation: "GRANT 뒤에 권한 SELECT, 대상 객체 EMP, 권한을 받을 사용자 KIM을 차례로 씁니다.",
    confusion: "GRANT는 권한 부여이고 REVOKE는 이미 부여한 권한의 회수입니다."
  },
  {
    id: "db-3nf-01",
    kind: "concept",
    topic: "데이터베이스",
    difficulty: "기초",
    tags: ["database", "db", "정규화", "3nf"],
    prompt: "제3정규형(3NF)에서 제거해야 하는 함수 종속의 종류를 쓰시오.",
    answer: "이행적 함수 종속",
    hint: "A→B이고 B→C일 때 A→C가 성립하는 관계입니다.",
    explanation: "3NF는 기본키가 아닌 속성이 다른 비기본 속성에 종속되는 이행적 함수 종속을 제거합니다.",
    confusion: "2NF는 부분 함수 종속, 3NF는 이행적 함수 종속 제거가 핵심입니다."
  },
  {
    id: "db-key-01",
    kind: "choice",
    topic: "데이터베이스",
    difficulty: "기초",
    tags: ["database", "db", "키", "보기"],
    prompt: "튜플을 유일하게 식별할 수 있는 최소 속성 집합을 고르시오.",
    choices: ["① 슈퍼키", "② 후보키", "③ 외래키", "④ 대체키"],
    answer: "② 후보키",
    hint: "유일성과 최소성을 모두 만족해야 합니다.",
    explanation: "후보키는 튜플을 유일하게 식별하는 유일성과 불필요한 속성이 없는 최소성을 만족합니다.",
    confusion: "슈퍼키는 유일성만 만족하며 불필요한 속성을 포함할 수 있습니다."
  },
  {
    id: "db-acid-01",
    kind: "concept",
    topic: "데이터베이스",
    difficulty: "기초",
    tags: ["database", "db", "acid", "트랜잭션"],
    prompt: "트랜잭션의 작업이 전부 수행되거나 전부 취소되어야 한다는 ACID 성질을 쓰시오.",
    answer: "원자성(Atomicity)",
    hint: "더 이상 나눌 수 없는 하나의 작업 단위라는 의미입니다.",
    explanation: "원자성은 트랜잭션의 일부만 반영되는 상태를 허용하지 않고 모두 성공하거나 모두 실패하도록 보장합니다.",
    confusion: "일관성은 제약조건 유지, 격리성은 동시 실행 간 간섭 방지, 지속성은 완료 결과 보존입니다."
  },
  {
    id: "db-integrity-01",
    kind: "choice",
    topic: "데이터베이스",
    difficulty: "기초",
    tags: ["database", "db", "무결성", "외래키", "보기"],
    prompt: "외래키 값은 참조하는 테이블의 기본키 값으로 존재해야 한다는 무결성을 고르시오.",
    choices: ["① 개체 무결성", "② 참조 무결성", "③ 도메인 무결성", "④ 키 무결성"],
    answer: "② 참조 무결성",
    hint: "테이블 사이의 참조 관계를 보호합니다.",
    explanation: "참조 무결성은 외래키가 참조 대상의 기본키 값이거나 NULL이어야 한다는 규칙입니다.",
    confusion: "개체 무결성은 기본키가 NULL이 될 수 없다는 규칙입니다."
  },
  {
    id: "db-index-01",
    kind: "concept",
    topic: "데이터베이스",
    difficulty: "실전",
    tags: ["database", "db", "인덱스", "성능"],
    prompt: "데이터베이스 인덱스의 장점 1가지와 단점 1가지를 쓰시오.",
    answer: "장점: 조회 속도 향상 / 단점: 저장 공간이 필요하고 INSERT·UPDATE·DELETE 성능이 저하될 수 있음",
    hint: "책의 색인이 검색에는 유리하지만 변경할 때 함께 고쳐야 하는 것과 비슷합니다.",
    explanation: "인덱스는 탐색 범위를 줄여 조회를 빠르게 하지만 별도 저장 공간을 사용하고 데이터 변경 때 인덱스도 갱신해야 합니다.",
    confusion: "인덱스를 많이 만들수록 모든 작업이 빨라지는 것은 아닙니다."
  },
  {
    id: "sql-count-distinct-02",
    kind: "sql",
    topic: "SQL",
    difficulty: "기초",
    tags: ["sql", "database", "집계", "distinct"],
    prompt: "EMP 테이블에서 중복을 제외한 부서번호(DEPTNO)의 개수를 구하는 SQL문을 쓰시오.",
    answer: "SELECT COUNT(DISTINCT DEPTNO) FROM EMP;",
    hint: "COUNT 안에서 중복 제거 키워드를 사용합니다.",
    explanation: "DISTINCT DEPTNO로 부서번호 중복을 제거한 뒤 COUNT로 개수를 셉니다.",
    confusion: "COUNT(DEPTNO)는 NULL을 제외하지만 중복은 포함하고, COUNT(DISTINCT DEPTNO)는 중복도 제외합니다."
  },
  {
    id: "sql-having-02",
    kind: "sql",
    topic: "SQL",
    difficulty: "실전",
    tags: ["sql", "database", "group by", "having"],
    prompt: "SALES(category, amount)에서 카테고리별 매출 합계가 1000 이상인 category와 합계를 조회하는 SQL문을 쓰시오.",
    answer: "SELECT category, SUM(amount) FROM SALES GROUP BY category HAVING SUM(amount) >= 1000;",
    hint: "그룹의 집계 결과 조건은 WHERE가 아니라 다른 절에 작성합니다.",
    explanation: "category로 그룹화하고 SUM(amount)을 계산한 뒤 HAVING으로 합계가 1000 이상인 그룹만 남깁니다.",
    confusion: "WHERE는 그룹화 전 행 조건, HAVING은 그룹화 후 집계 조건입니다."
  },
  {
    id: "sql-subquery-02",
    kind: "sql",
    topic: "SQL",
    difficulty: "실전",
    tags: ["sql", "database", "서브쿼리", "평균"],
    prompt: "EMP(name, salary)에서 전체 평균 급여보다 급여가 높은 직원의 name을 조회하는 SQL문을 쓰시오.",
    answer: "SELECT name FROM EMP WHERE salary > (SELECT AVG(salary) FROM EMP);",
    hint: "평균 급여를 단일 값을 반환하는 서브쿼리로 계산합니다.",
    explanation: "내부 쿼리가 전체 평균을 구하고 외부 쿼리가 각 직원의 salary와 비교합니다.",
    confusion: "집계값과 개별 행을 비교하려면 보통 집계 쿼리를 서브쿼리로 분리합니다."
  },
  {
    id: "sql-update-02",
    kind: "sql",
    topic: "SQL",
    difficulty: "기초",
    tags: ["sql", "database", "update", "dml"],
    prompt: "EMP 테이블에서 DEPTNO가 10인 직원들의 salary를 10% 인상하는 SQL문을 쓰시오.",
    answer: "UPDATE EMP SET salary = salary * 1.1 WHERE DEPTNO = 10;",
    hint: "현재 salary 값에 1.1을 곱합니다.",
    explanation: "WHERE로 10번 부서만 선택하고 기존 salary의 110%를 새 값으로 저장합니다.",
    confusion: "WHERE를 생략하면 모든 행의 급여가 변경됩니다."
  },
  {
    id: "sql-delete-null-01",
    kind: "sql",
    topic: "SQL",
    difficulty: "기초",
    tags: ["sql", "database", "delete", "null"],
    prompt: "MEMBER 테이블에서 email이 NULL인 행을 삭제하는 SQL문을 쓰시오.",
    answer: "DELETE FROM MEMBER WHERE email IS NULL;",
    hint: "NULL 비교에는 등호를 사용하지 않습니다.",
    explanation: "NULL은 일반 값이 아니므로 IS NULL 조건으로 찾은 뒤 DELETE합니다.",
    confusion: "email = NULL은 참이 되지 않으며 IS NULL 또는 IS NOT NULL을 사용해야 합니다."
  },
  {
    id: "sql-create-fk-01",
    kind: "sql",
    topic: "SQL",
    difficulty: "실전",
    tags: ["sql", "database", "ddl", "외래키"],
    prompt: "DEPT(id)를 참조하는 EMP(dept_id)의 외래키 제약조건을 테이블 생성 시 지정하는 핵심 구문을 쓰시오.",
    answer: "FOREIGN KEY (dept_id) REFERENCES DEPT(id)",
    hint: "참조하는 열과 참조 대상 테이블·열을 함께 적습니다.",
    explanation: "FOREIGN KEY로 EMP의 dept_id를 지정하고 REFERENCES로 DEPT의 id를 참조하게 합니다.",
    confusion: "PRIMARY KEY는 행을 식별하고 FOREIGN KEY는 다른 테이블의 키와 참조 관계를 만듭니다."
  },
  {
    id: "sql-dense-rank-01",
    kind: "sql",
    topic: "SQL",
    difficulty: "심화",
    tags: ["sql", "database", "윈도우함수", "순위", "calculation"],
    prompt: "점수가 90, 90, 80인 세 행에 DENSE_RANK() OVER (ORDER BY score DESC)를 적용했을 때 순위를 순서대로 쓰시오.",
    answer: "1, 1, 2",
    hint: "동점 다음 순위가 건너뛰어지는지 확인하세요.",
    explanation: "90점 두 행은 공동 1위이고 DENSE_RANK는 다음 순위를 건너뛰지 않아 80점이 2위입니다.",
    confusion: "RANK라면 1, 1, 3이고 ROW_NUMBER라면 동점도 1, 2처럼 서로 다른 번호를 가집니다."
  },
  {
    id: "sql-coalesce-01",
    kind: "sql",
    topic: "SQL",
    difficulty: "기초",
    tags: ["sql", "database", "null", "함수"],
    prompt: "BONUS 값이 NULL이면 0으로 표시하도록 조회하는 표준 SQL 표현을 쓰시오.",
    answer: "COALESCE(BONUS, 0)",
    hint: "여러 인수 중 첫 번째 NULL이 아닌 값을 반환하는 함수입니다.",
    explanation: "COALESCE는 BONUS가 NULL이 아니면 BONUS를, NULL이면 다음 인수 0을 반환합니다.",
    confusion: "DBMS별 NVL이나 IFNULL 대신 표준 SQL에서는 COALESCE를 사용할 수 있습니다."
  },
  {
    id: "sql-rollback-01",
    kind: "sql",
    topic: "SQL",
    difficulty: "실전",
    tags: ["sql", "database", "transaction", "rollback"],
    prompt: "COMMIT 이후 UPDATE를 수행했지만 아직 다시 COMMIT하지 않은 상태에서 ROLLBACK을 실행하면 UPDATE 내용은 어떻게 되는지 쓰시오.",
    answer: "마지막 COMMIT 이후의 UPDATE가 취소된다.",
    hint: "ROLLBACK이 되돌리는 기준점은 마지막 확정 시점입니다.",
    explanation: "COMMIT으로 확정된 이전 내용은 유지되고 그 이후 아직 확정되지 않은 변경만 취소됩니다.",
    confusion: "이미 COMMIT된 변경은 일반적인 ROLLBACK으로 되돌릴 수 없습니다."
  },
  {
    id: "sql-between-01",
    kind: "sql",
    topic: "SQL",
    difficulty: "기초",
    tags: ["sql", "database", "between", "조건"],
    prompt: "WHERE score BETWEEN 60 AND 80 조건에 score가 60 또는 80인 행이 포함되는지 쓰시오.",
    answer: "둘 다 포함된다.",
    hint: "BETWEEN의 양쪽 경곗값 포함 여부를 떠올리세요.",
    explanation: "BETWEEN 60 AND 80은 일반적으로 score >= 60 AND score <= 80과 같아 양 끝값을 포함합니다.",
    confusion: "날짜와 시각에서는 종료일의 시간값 때문에 예상과 다른 결과가 날 수 있어 범위를 명시적으로 작성하기도 합니다."
  },
  {
    id: "db-2nf-02",
    kind: "concept",
    topic: "데이터베이스",
    difficulty: "실전",
    tags: ["database", "db", "정규화", "2nf"],
    prompt: "제2정규형(2NF)이 제거하는 함수적 종속의 유형을 쓰시오.",
    answer: "부분 함수 종속",
    hint: "복합 기본키의 일부에만 종속되는 속성을 생각하세요.",
    explanation: "2NF는 기본키가 복합키일 때 일반 속성이 키 전체가 아닌 일부에만 의존하는 부분 함수 종속을 제거합니다.",
    confusion: "3NF는 이행 함수 종속을 제거하고 2NF는 부분 함수 종속을 제거합니다."
  },
  {
    id: "db-bcnf-01",
    kind: "choice",
    topic: "데이터베이스",
    difficulty: "심화",
    tags: ["database", "db", "정규화", "bcnf"],
    prompt: "BCNF를 만족하기 위한 조건으로 가장 알맞은 것을 고르시오.",
    choices: ["① 모든 결정자가 후보키이다", "② 모든 속성이 원자값이다", "③ 이행 종속만 제거한다", "④ 외래키를 제거한다"],
    answer: "① 모든 결정자가 후보키이다",
    hint: "BCNF는 결정자의 자격을 더 엄격하게 봅니다.",
    explanation: "BCNF에서는 모든 의미 있는 함수 종속 X→Y의 결정자 X가 후보키여야 합니다.",
    confusion: "원자값은 1NF 조건이고 이행 종속 제거는 3NF의 핵심 설명입니다."
  },
  {
    id: "db-isolation-01",
    kind: "choice",
    topic: "데이터베이스",
    difficulty: "실전",
    tags: ["database", "db", "transaction", "격리수준"],
    prompt: "다른 트랜잭션이 아직 COMMIT하지 않은 값을 읽는 현상을 고르시오.",
    choices: ["① Dirty Read", "② Lost Update", "③ Phantom Read", "④ Deadlock"],
    answer: "① Dirty Read",
    hint: "확정되지 않아 오염된 값을 읽는다는 의미입니다.",
    explanation: "Dirty Read는 한 트랜잭션이 다른 트랜잭션의 미확정 변경 내용을 읽는 현상입니다.",
    confusion: "Non-repeatable Read는 같은 행을 다시 읽었을 때 값이 달라지는 현상입니다."
  },
  {
    id: "db-anomaly-01",
    kind: "concept",
    topic: "데이터베이스",
    difficulty: "기초",
    tags: ["database", "db", "정규화", "이상현상"],
    prompt: "중복 저장된 같은 정보 중 일부만 변경되어 데이터가 서로 불일치하게 되는 이상 현상을 쓰시오.",
    answer: "갱신 이상(Update Anomaly)",
    hint: "삽입·삭제·갱신 이상 중 변경 작업과 관련됩니다.",
    explanation: "중복 데이터의 일부 행만 수정하면 같은 사실을 나타내는 값이 달라지는 갱신 이상이 발생합니다.",
    confusion: "삽입 이상은 불필요한 정보 없이는 삽입하기 어렵고 삭제 이상은 삭제 시 필요한 정보까지 사라지는 현상입니다."
  },
  {
    id: "db-candidate-key-02",
    kind: "concept",
    topic: "데이터베이스",
    difficulty: "기초",
    tags: ["database", "db", "key", "후보키"],
    prompt: "후보키가 만족해야 하는 두 가지 성질을 쓰시오.",
    answer: "유일성과 최소성",
    hint: "튜플을 하나로 식별할 수 있어야 하며 불필요한 속성이 없어야 합니다.",
    explanation: "후보키는 모든 행을 유일하게 식별하는 유일성과 속성을 더 줄일 수 없는 최소성을 모두 만족합니다.",
    confusion: "슈퍼키는 유일성만 만족해도 되므로 불필요한 속성을 포함할 수 있습니다."
  }
];
