import type { StudyQuestion } from "../types";

// 실제 기출문장을 복제하지 않고, 실기에서 자주 접하는 '보기에서 골라 쓰기' 형식으로 만든 문제다.
export const PRACTICAL_WORD_BANK_QUESTIONS: StudyQuestion[] = [
  {
    id: "wb-os-state-01",
    kind: "choice",
    topic: "운영체제",
    difficulty: "기초",
    tags: ["os", "운영체제", "프로세스", "보기", "word-bank"],
    prompt: "다음 설명의 (가), (나)에 들어갈 프로세스 상태를 보기에서 골라 쓰시오.\n(가) CPU를 배정받기 위해 준비 큐에서 기다리는 상태\n(나) 입출력 완료 같은 사건을 기다리는 상태",
    choices: ["① Ready", "② Running", "③ Waiting", "④ Terminated"],
    answer: "(가) Ready, (나) Waiting",
    hint: "(가)는 CPU만 기다리고, (나)는 특정 사건이 끝나기를 기다립니다.",
    explanation: "Ready는 실행 준비를 마치고 CPU 할당을 기다리는 상태이며, Waiting은 입출력이나 이벤트 완료를 기다리는 상태입니다.",
    confusion: "Ready는 CPU를 받을 수 있지만 아직 실행하지 않는 상태이고, Running은 실제로 CPU를 사용 중인 상태입니다."
  },
  {
    id: "wb-os-page-01",
    kind: "choice",
    topic: "운영체제",
    difficulty: "실전",
    tags: ["os", "운영체제", "페이지교체", "보기", "word-bank"],
    prompt: "다음 설명의 (가), (나)에 들어갈 페이지 교체 알고리즘을 보기에서 골라 쓰시오.\n(가) 메모리에 가장 먼저 들어온 페이지를 교체한다.\n(나) 가장 오랫동안 사용되지 않은 페이지를 교체한다.",
    choices: ["① FIFO", "② LRU", "③ LFU", "④ OPT"],
    answer: "(가) FIFO, (나) LRU",
    hint: "들어온 순서와 최근 사용 시점을 구분하세요.",
    explanation: "FIFO는 적재 순서가 가장 오래된 페이지를, LRU는 사용 시점이 가장 오래된 페이지를 교체합니다.",
    confusion: "LFU는 사용 횟수가 가장 적은 페이지를 교체하며 LRU와 판단 기준이 다릅니다."
  },
  {
    id: "wb-network-protocol-01",
    kind: "choice",
    topic: "네트워크",
    difficulty: "기초",
    tags: ["network", "네트워크", "tcp", "udp", "보기", "word-bank"],
    prompt: "다음 설명의 (가), (나)에 들어갈 전송 계층 프로토콜을 보기에서 골라 쓰시오.\n(가) 연결형이며 순서 제어와 재전송을 제공한다.\n(나) 비연결형이며 오버헤드가 작고 빠른 전송에 적합하다.",
    choices: ["① IP", "② TCP", "③ UDP", "④ ARP"],
    answer: "(가) TCP, (나) UDP",
    hint: "신뢰성 보장 여부를 기준으로 구분하세요.",
    explanation: "TCP는 연결 설정과 신뢰성 제어를 제공하고, UDP는 연결 과정 없이 데이터그램을 전송합니다.",
    confusion: "IP와 ARP는 전송 계층 프로토콜이 아닙니다."
  },
  {
    id: "wb-network-address-01",
    kind: "choice",
    topic: "네트워크",
    difficulty: "실전",
    tags: ["network", "네트워크", "주소", "dns", "arp", "보기", "word-bank"],
    prompt: "다음 설명의 (가), (나)에 들어갈 프로토콜을 보기에서 골라 쓰시오.\n(가) 도메인 이름을 IP 주소로 변환한다.\n(나) 같은 네트워크에서 IPv4 주소에 대응하는 MAC 주소를 알아낸다.",
    choices: ["① DNS", "② ARP", "③ DHCP", "④ ICMP"],
    answer: "(가) DNS, (나) ARP",
    hint: "이름 해석과 논리 주소·물리 주소 대응을 구분하세요.",
    explanation: "DNS는 이름 해석을 담당하고 ARP는 로컬 네트워크에서 IPv4 주소에 해당하는 MAC 주소를 찾습니다.",
    confusion: "DHCP는 IP 설정 정보를 자동 할당하고 ICMP는 오류 보고와 진단에 사용됩니다."
  },
  {
    id: "wb-db-key-01",
    kind: "choice",
    topic: "데이터베이스",
    difficulty: "기초",
    tags: ["database", "db", "key", "키", "보기", "word-bank"],
    prompt: "다음 설명의 (가), (나)에 들어갈 키를 보기에서 골라 쓰시오.\n(가) 튜플을 유일하게 식별할 수 있는 최소 속성 집합\n(나) 후보키 중 기본 식별자로 선택한 키",
    choices: ["① 슈퍼키", "② 후보키", "③ 기본키", "④ 외래키"],
    answer: "(가) 후보키, (나) 기본키",
    hint: "유일성과 최소성을 모두 만족하는지, 그중 실제 대표로 선택되었는지 구분하세요.",
    explanation: "후보키는 유일성과 최소성을 만족하며, 기본키는 후보키 중 대표로 선택된 키입니다.",
    confusion: "슈퍼키는 유일성은 만족하지만 최소성을 만족하지 않을 수 있습니다."
  },
  {
    id: "wb-db-normalization-01",
    kind: "choice",
    topic: "데이터베이스",
    difficulty: "실전",
    tags: ["database", "db", "정규화", "보기", "word-bank"],
    prompt: "다음 설명의 (가), (나)에 들어갈 정규형을 보기에서 골라 쓰시오.\n(가) 부분 함수 종속을 제거한 정규형\n(나) 이행 함수 종속을 제거한 정규형",
    choices: ["① 제1정규형", "② 제2정규형", "③ 제3정규형", "④ BCNF"],
    answer: "(가) 제2정규형, (나) 제3정규형",
    hint: "부분 종속 제거 다음 단계가 이행 종속 제거입니다.",
    explanation: "제2정규형은 기본키에 대한 부분 함수 종속을 제거하고, 제3정규형은 이행 함수 종속을 제거합니다.",
    confusion: "BCNF는 모든 결정자가 후보키가 되도록 강화한 정규형입니다."
  },
  {
    id: "wb-db-acid-01",
    kind: "choice",
    topic: "데이터베이스",
    difficulty: "기초",
    tags: ["database", "db", "transaction", "acid", "보기", "word-bank"],
    prompt: "다음 설명의 (가), (나)에 들어갈 트랜잭션 성질을 보기에서 골라 쓰시오.\n(가) 작업이 모두 수행되거나 모두 취소되어야 한다.\n(나) 완료된 결과는 장애가 발생해도 보존되어야 한다.",
    choices: ["① 원자성", "② 일관성", "③ 격리성", "④ 지속성"],
    answer: "(가) 원자성, (나) 지속성",
    hint: "All or Nothing과 커밋 결과의 영구 보존을 연결하세요.",
    explanation: "원자성은 트랜잭션의 전부 수행 또는 전부 취소를, 지속성은 커밋 결과의 영구 보존을 뜻합니다.",
    confusion: "격리성은 동시에 실행되는 트랜잭션이 서로의 중간 결과에 영향을 주지 않도록 하는 성질입니다."
  },
  {
    id: "wb-security-web-01",
    kind: "choice",
    topic: "보안",
    difficulty: "실전",
    tags: ["security", "보안", "xss", "csrf", "보기", "word-bank"],
    prompt: "다음 설명의 (가), (나)에 들어갈 공격 기법을 보기에서 골라 쓰시오.\n(가) 악성 스크립트를 웹 페이지에 삽입해 사용자의 브라우저에서 실행한다.\n(나) 로그인된 사용자의 권한으로 원하지 않는 요청을 보내게 한다.",
    choices: ["① XSS", "② CSRF", "③ SQL Injection", "④ Sniffing"],
    answer: "(가) XSS, (나) CSRF",
    hint: "스크립트 실행과 인증 상태를 악용한 요청 위조를 구분하세요.",
    explanation: "XSS는 브라우저에서 악성 스크립트를 실행시키고, CSRF는 사용자의 인증 상태를 악용해 요청을 위조합니다.",
    confusion: "SQL Injection은 입력값을 통해 데이터베이스 질의 구조를 변조하는 공격입니다."
  },
  {
    id: "wb-security-control-01",
    kind: "choice",
    topic: "보안",
    difficulty: "기초",
    tags: ["security", "보안", "접근통제", "보기", "word-bank"],
    prompt: "다음 설명의 (가), (나)에 들어갈 접근통제 모델을 보기에서 골라 쓰시오.\n(가) 자원 소유자가 접근 권한을 재량으로 부여한다.\n(나) 직무나 역할을 기준으로 권한을 부여한다.",
    choices: ["① DAC", "② MAC", "③ RBAC", "④ ABAC"],
    answer: "(가) DAC, (나) RBAC",
    hint: "Discretionary와 Role의 의미를 떠올리세요.",
    explanation: "DAC는 소유자의 재량을, RBAC는 조직의 역할을 중심으로 권한을 관리합니다.",
    confusion: "MAC는 보안 등급과 중앙 정책을 기준으로 접근을 통제합니다."
  },
  {
    id: "wb-security-crypto-01",
    kind: "choice",
    topic: "보안",
    difficulty: "실전",
    tags: ["security", "보안", "암호화", "해시", "보기", "word-bank"],
    prompt: "다음 설명의 (가), (나)에 들어갈 방식을 보기에서 골라 쓰시오.\n(가) 암호화와 복호화에 같은 키를 사용한다.\n(나) 입력을 고정 길이 값으로 바꾸며 원문 복원이 어렵다.",
    choices: ["① 대칭키 암호", "② 공개키 암호", "③ 해시 함수", "④ Base64"],
    answer: "(가) 대칭키 암호, (나) 해시 함수",
    hint: "복호화가 필요한 암호 방식과 단방향 변환을 구분하세요.",
    explanation: "대칭키 암호는 동일한 비밀키로 암·복호화하며, 해시는 일반적으로 복원을 목적으로 하지 않는 단방향 변환입니다.",
    confusion: "Base64는 표현 형식을 바꾸는 인코딩으로 보안 기능을 제공하지 않습니다."
  },
  {
    id: "wb-test-blackbox-01",
    kind: "choice",
    topic: "애플리케이션 테스트",
    difficulty: "기초",
    tags: ["test", "테스트", "블랙박스", "보기", "word-bank"],
    prompt: "다음 설명의 (가), (나)에 들어갈 테스트 기법을 보기에서 골라 쓰시오.\n(가) 입력 영역을 같은 동작이 예상되는 집합으로 나눈다.\n(나) 입력 범위의 최소·최대와 그 주변 값을 검사한다.",
    choices: ["① 동등 분할", "② 경계값 분석", "③ 문장 커버리지", "④ 조건 커버리지"],
    answer: "(가) 동등 분할, (나) 경계값 분석",
    hint: "입력 집합 분할과 범위의 끝부분 검사를 구분하세요.",
    explanation: "동등 분할은 대표값을 뽑을 입력 집합을 만들고, 경계값 분석은 오류가 잦은 경계 주변에 집중합니다.",
    confusion: "문장·조건 커버리지는 내부 논리 구조를 확인하는 화이트박스 테스트 기준입니다."
  },
  {
    id: "wb-test-coverage-01",
    kind: "choice",
    topic: "애플리케이션 테스트",
    difficulty: "실전",
    tags: ["test", "테스트", "화이트박스", "coverage", "보기", "word-bank"],
    prompt: "다음 설명의 (가), (나)에 들어갈 커버리지를 보기에서 골라 쓰시오.\n(가) 모든 실행문이 최소 한 번 실행된다.\n(나) 각 결정식의 참과 거짓 결과가 최소 한 번 실행된다.",
    choices: ["① 문장 커버리지", "② 결정 커버리지", "③ 조건 커버리지", "④ 경로 커버리지"],
    answer: "(가) 문장 커버리지, (나) 결정 커버리지",
    hint: "실행문 자체와 분기 결과의 양쪽을 구분하세요.",
    explanation: "문장 커버리지는 모든 문장 실행을, 결정 커버리지는 각 결정의 참·거짓 분기 실행을 요구합니다.",
    confusion: "조건 커버리지는 결정식 내부의 개별 조건이 참과 거짓을 갖도록 합니다."
  },
  {
    id: "wb-uml-diagram-01",
    kind: "choice",
    topic: "소프트웨어 공학",
    difficulty: "기초",
    tags: ["software", "uml", "설계", "보기", "word-bank"],
    prompt: "다음 설명의 (가), (나)에 들어갈 UML 다이어그램을 보기에서 골라 쓰시오.\n(가) 객체 사이 메시지를 시간 순서대로 표현한다.\n(나) 시스템의 정적 구조와 클래스 관계를 표현한다.",
    choices: ["① 시퀀스", "② 클래스", "③ 액티비티", "④ 상태"],
    answer: "(가) 시퀀스 다이어그램, (나) 클래스 다이어그램",
    hint: "시간 흐름이 있는 상호작용과 정적 구조를 구분하세요.",
    explanation: "시퀀스 다이어그램은 생명선과 메시지 순서를, 클래스 다이어그램은 클래스의 속성·연산·관계를 나타냅니다.",
    confusion: "액티비티 다이어그램은 업무나 알고리즘의 제어 흐름을 표현합니다."
  },
  {
    id: "wb-design-pattern-01",
    kind: "choice",
    topic: "소프트웨어 공학",
    difficulty: "실전",
    tags: ["software", "설계", "디자인패턴", "보기", "word-bank"],
    prompt: "다음 설명의 (가), (나)에 들어갈 디자인 패턴을 보기에서 골라 쓰시오.\n(가) 호환되지 않는 인터페이스를 사용 가능한 형태로 변환한다.\n(나) 한 객체의 상태 변경을 의존 객체들에게 자동 통지한다.",
    choices: ["① Adapter", "② Observer", "③ Strategy", "④ Factory Method"],
    answer: "(가) Adapter, (나) Observer",
    hint: "인터페이스 변환과 일대다 상태 통지를 구분하세요.",
    explanation: "Adapter는 인터페이스를 변환하고 Observer는 주제의 상태 변경을 여러 관찰자에게 알립니다.",
    confusion: "Strategy는 교체 가능한 알고리즘을 캡슐화합니다."
  },
  {
    id: "wb-module-quality-01",
    kind: "choice",
    topic: "소프트웨어 공학",
    difficulty: "실전",
    tags: ["software", "설계", "응집도", "결합도", "보기", "word-bank"],
    prompt: "다음 설명의 (가), (나)에 들어갈 용어를 보기에서 골라 쓰시오.\n좋은 모듈 설계는 모듈 내부의 (가)를 높이고, 모듈 사이의 (나)를 낮추는 방향을 지향한다.",
    choices: ["① 응집도", "② 결합도", "③ 복잡도", "④ 중복도"],
    answer: "(가) 응집도, (나) 결합도",
    hint: "모듈 내부는 한 기능에 집중하고 외부 의존성은 줄여야 합니다.",
    explanation: "높은 응집도는 모듈 내부 책임의 집중을, 낮은 결합도는 모듈 간 의존성 감소를 뜻합니다.",
    confusion: "응집도와 결합도의 좋고 나쁜 방향을 반대로 외우지 않도록 주의하세요."
  },
  {
    id: "wb-data-structure-01",
    kind: "choice",
    topic: "자료구조",
    difficulty: "기초",
    tags: ["data-structure", "자료구조", "stack", "queue", "보기", "word-bank"],
    prompt: "다음 설명의 (가), (나)에 들어갈 자료구조를 보기에서 골라 쓰시오.\n(가) 나중에 삽입한 데이터가 먼저 삭제된다.\n(나) 먼저 삽입한 데이터가 먼저 삭제된다.",
    choices: ["① Stack", "② Queue", "③ Tree", "④ Graph"],
    answer: "(가) Stack, (나) Queue",
    hint: "LIFO와 FIFO를 각각 연결하세요.",
    explanation: "Stack은 LIFO, Queue는 FIFO 방식으로 데이터를 처리합니다.",
    confusion: "우선순위 큐는 삽입 순서가 아니라 우선순위를 기준으로 삭제됩니다."
  },
  {
    id: "wb-tree-search-01",
    kind: "choice",
    topic: "자료구조",
    difficulty: "실전",
    tags: ["data-structure", "자료구조", "tree", "search", "보기", "word-bank"],
    prompt: "다음 설명의 (가), (나)에 들어갈 탐색 방법을 보기에서 골라 쓰시오.\n(가) 큐를 사용해 가까운 정점부터 탐색한다.\n(나) 스택 또는 재귀를 사용해 한 경로를 깊게 탐색한다.",
    choices: ["① BFS", "② DFS", "③ Binary Search", "④ Hash Search"],
    answer: "(가) BFS, (나) DFS",
    hint: "너비 우선은 큐, 깊이 우선은 스택과 연결됩니다.",
    explanation: "BFS는 레벨 순서로 탐색해 큐를 사용하고, DFS는 한 경로를 깊게 진행해 스택이나 재귀를 사용합니다.",
    confusion: "Binary Search는 정렬된 선형 자료에서 탐색 범위를 절반씩 줄이는 방법입니다."
  },
  {
    id: "wb-web-method-01",
    kind: "choice",
    topic: "웹/API",
    difficulty: "기초",
    tags: ["web", "웹", "http", "api", "rest", "보기", "word-bank"],
    prompt: "다음 설명의 (가), (나)에 들어갈 HTTP 메서드를 보기에서 골라 쓰시오.\n(가) 자원을 조회한다.\n(나) 자원의 전체 표현을 대체하며 일반적으로 멱등성을 가진다.",
    choices: ["① GET", "② POST", "③ PUT", "④ PATCH"],
    answer: "(가) GET, (나) PUT",
    hint: "조회와 전체 대체를 구분하세요.",
    explanation: "GET은 자원 조회, PUT은 지정한 자원의 전체 표현 대체에 사용됩니다.",
    confusion: "PATCH는 자원의 일부 변경에 주로 사용하고 POST는 보통 새 처리나 생성을 요청합니다."
  },
  {
    id: "wb-web-status-01",
    kind: "choice",
    topic: "웹/API",
    difficulty: "기초",
    tags: ["web", "웹", "http", "status", "보기", "word-bank"],
    prompt: "다음 설명의 (가), (나)에 들어갈 HTTP 상태 코드를 보기에서 골라 쓰시오.\n(가) 요청한 자원을 찾을 수 없다.\n(나) 서버 내부 오류로 요청을 처리하지 못했다.",
    choices: ["① 200", "② 400", "③ 404", "④ 500"],
    answer: "(가) 404, (나) 500",
    hint: "클라이언트 측 자원 부재와 서버 내부 오류를 구분하세요.",
    explanation: "404는 요청한 자원을 찾지 못했음을, 500은 서버 내부 오류가 발생했음을 뜻합니다.",
    confusion: "400은 요청 문법이나 값이 잘못된 경우에 사용하는 클라이언트 오류입니다."
  },
  {
    id: "wb-cloud-service-01",
    kind: "choice",
    topic: "신기술",
    difficulty: "기초",
    tags: ["emerging", "신기술", "cloud", "보기", "word-bank"],
    prompt: "다음 설명의 (가), (나)에 들어갈 클라우드 서비스 모델을 보기에서 골라 쓰시오.\n(가) 가상 서버·스토리지·네트워크 같은 인프라를 제공한다.\n(나) 애플리케이션 실행 환경과 개발 플랫폼까지 제공한다.",
    choices: ["① IaaS", "② PaaS", "③ SaaS", "④ On-premise"],
    answer: "(가) IaaS, (나) PaaS",
    hint: "Infrastructure와 Platform의 범위를 비교하세요.",
    explanation: "IaaS는 기반 인프라를, PaaS는 애플리케이션 개발·실행 플랫폼을 서비스로 제공합니다.",
    confusion: "SaaS는 완성된 소프트웨어 기능을 사용자가 서비스 형태로 이용하는 모델입니다."
  },
  {
    id: "wb-emerging-architecture-01",
    kind: "choice",
    topic: "신기술",
    difficulty: "실전",
    tags: ["emerging", "신기술", "architecture", "container", "보기", "word-bank"],
    prompt: "다음 설명의 (가), (나)에 들어갈 기술을 보기에서 골라 쓰시오.\n(가) 애플리케이션과 의존성을 격리하되 호스트 운영체제 커널을 공유한다.\n(나) 기능을 작고 독립적인 서비스로 나누어 배포한다.",
    choices: ["① 컨테이너", "② 가상 머신", "③ 마이크로서비스", "④ 모놀리식"],
    answer: "(가) 컨테이너, (나) 마이크로서비스",
    hint: "실행 격리 방식과 서비스 분할 아키텍처를 구분하세요.",
    explanation: "컨테이너는 호스트 커널을 공유하는 경량 격리 기술이고, 마이크로서비스는 시스템을 독립 배포 가능한 작은 서비스로 나눕니다.",
    confusion: "가상 머신은 일반적으로 각 인스턴스가 별도의 게스트 운영체제를 포함합니다."
  }
];
