import type { StudyQuestion } from "../types";

export const SYSTEM_NETWORK_LINUX_QUESTIONS: StudyQuestion[] = [
  {
    id: "net-osi-01",
    kind: "choice",
    topic: "네트워크",
    difficulty: "기초",
    tags: ["network", "네트워크", "osi", "tcp", "udp", "보기"],
    prompt: "OSI 7계층에서 TCP와 UDP가 동작하는 계층을 고르시오.",
    choices: ["① 네트워크 계층", "② 전송 계층", "③ 세션 계층", "④ 응용 계층"],
    answer: "② 전송 계층",
    hint: "종단 간 연결과 포트 번호를 담당합니다.",
    explanation: "TCP와 UDP는 종단 간 데이터 전달을 담당하는 전송 계층 프로토콜입니다.",
    confusion: "IP는 네트워크 계층, HTTP는 응용 계층에 해당합니다."
  },
  {
    id: "net-tcp-udp-01",
    kind: "concept",
    topic: "네트워크",
    difficulty: "기초",
    tags: ["network", "네트워크", "tcp", "udp"],
    prompt: "TCP와 UDP의 차이를 연결 방식과 신뢰성 관점에서 쓰시오.",
    answer: "TCP는 연결형이며 순서·재전송 등 신뢰성을 제공하고, UDP는 비연결형이며 신뢰성 보장 없이 빠르게 전송한다.",
    hint: "연결 설정 여부와 오류·순서 보장 여부를 비교하세요.",
    explanation: "TCP는 연결을 맺고 흐름·혼잡 제어와 재전송을 수행합니다. UDP는 오버헤드가 작지만 전달과 순서를 보장하지 않습니다.",
    confusion: "UDP도 체크섬은 사용할 수 있지만 TCP와 같은 재전송·순서 보장은 제공하지 않습니다."
  },
  {
    id: "os-deadlock-01",
    kind: "concept",
    topic: "운영체제",
    difficulty: "실전",
    tags: ["os", "운영체제", "deadlock", "교착상태"],
    prompt: "교착상태 발생의 필요조건 4가지를 쓰시오.",
    answer: "상호 배제, 점유와 대기, 비선점, 환형 대기",
    hint: "자원 하나를 독점하고, 가진 채 기다리고, 빼앗을 수 없고, 원형으로 기다리는 상황입니다.",
    explanation: "네 조건이 동시에 성립할 때 교착상태가 발생할 수 있습니다. 하나라도 깨면 예방할 수 있습니다.",
    confusion: "네 조건은 교착상태가 반드시 발생한다는 충분조건이 아니라 발생 가능성을 만드는 필요조건입니다."
  },
  {
    id: "os-lru-01",
    kind: "code",
    topic: "운영체제",
    difficulty: "실전",
    tags: ["os", "운영체제", "페이지교체", "lru", "계산"],
    prompt: "페이지 프레임이 3개이고 참조열이 `1, 2, 3, 1, 4`일 때 LRU 알고리즘의 페이지 부재 횟수를 쓰시오. 처음 프레임은 비어 있다.",
    answer: "4회",
    hint: "1, 2, 3을 적재한 뒤 1은 적중하고, 4가 들어올 때 가장 오래 쓰지 않은 페이지를 교체합니다.",
    explanation: "1, 2, 3에서 각각 부재 3회, 다시 1은 적중, 4는 가장 오래 사용하지 않은 2를 교체해 부재 1회가 추가됩니다.",
    confusion: "LRU는 가장 먼저 들어온 페이지가 아니라 가장 오랫동안 사용되지 않은 페이지를 교체합니다."
  },
  {
    id: "os-rr-01",
    kind: "concept",
    topic: "운영체제",
    difficulty: "기초",
    tags: ["os", "운영체제", "스케줄링", "round robin"],
    prompt: "각 프로세스에 동일한 시간 할당량을 주고 순환하며 CPU를 배정하는 선점형 스케줄링 기법을 쓰시오.",
    answer: "라운드 로빈(Round Robin)",
    hint: "준비 큐를 원형으로 순회합니다.",
    explanation: "라운드 로빈은 타임 퀀텀이 끝나면 실행 중인 프로세스를 준비 큐 뒤로 보내 다음 프로세스에 CPU를 줍니다.",
    confusion: "타임 퀀텀이 너무 크면 FCFS와 비슷해지고 너무 작으면 문맥 교환 오버헤드가 커집니다."
  },
  {
    id: "net-handshake-01",
    kind: "concept",
    topic: "네트워크",
    difficulty: "기초",
    tags: ["network", "네트워크", "tcp", "연결"],
    prompt: "TCP 3-way handshake에서 교환되는 제어 플래그를 순서대로 쓰시오.",
    answer: "SYN → SYN/ACK → ACK",
    hint: "연결 요청, 요청 수락과 응답, 최종 확인 순서입니다.",
    explanation: "클라이언트가 SYN을 보내고 서버가 SYN과 ACK로 응답한 뒤 클라이언트가 ACK를 보내 연결을 확립합니다.",
    confusion: "연결 종료는 일반적으로 FIN과 ACK를 주고받는 4-way handshake로 설명합니다."
  },
  {
    id: "net-cidr-01",
    kind: "concept",
    topic: "네트워크",
    difficulty: "실전",
    tags: ["network", "네트워크", "ip", "subnet", "calculation"],
    prompt: "IPv4 /27 서브넷에서 네트워크 주소와 브로드캐스트 주소를 제외하고 사용할 수 있는 호스트 주소의 개수를 쓰시오.",
    answer: "30개",
    hint: "호스트 비트는 32-27개입니다.",
    explanation: "호스트 비트가 5개이므로 전체 주소는 2⁵=32개이고 네트워크·브로드캐스트 주소를 빼면 30개입니다.",
    confusion: "일반적인 서브넷 호스트 계산은 2^호스트비트 - 2이지만 /31 등 특수 용도는 예외가 있습니다."
  },
  {
    id: "net-dns-01",
    kind: "choice",
    topic: "네트워크",
    difficulty: "기초",
    tags: ["network", "네트워크", "dns", "port"],
    prompt: "DNS가 기본적으로 사용하는 포트 번호를 고르시오.",
    choices: ["① 22", "② 53", "③ 80", "④ 443"],
    answer: "② 53",
    hint: "도메인 이름을 IP 주소로 해석하는 서비스의 포트입니다.",
    explanation: "DNS는 일반 질의에 UDP 53번을 주로 사용하고 영역 전송이나 큰 응답 등에는 TCP 53번도 사용합니다.",
    confusion: "22는 SSH, 80은 HTTP, 443은 HTTPS의 대표 포트입니다."
  },
  {
    id: "net-arp-01",
    kind: "concept",
    topic: "네트워크",
    difficulty: "기초",
    tags: ["network", "네트워크", "arp", "주소"],
    prompt: "같은 네트워크에서 IPv4 주소에 대응하는 MAC 주소를 알아내는 프로토콜을 쓰시오.",
    answer: "ARP(Address Resolution Protocol)",
    hint: "논리 주소를 물리 주소로 대응시킵니다.",
    explanation: "ARP는 대상 IPv4 주소를 가진 장치의 MAC 주소를 질의하고 응답받아 ARP 캐시에 저장합니다.",
    confusion: "RARP는 반대 방향의 오래된 프로토콜이며 현재 주소 자동 설정에는 DHCP가 널리 사용됩니다."
  },
  {
    id: "os-fcfs-01",
    kind: "concept",
    topic: "운영체제",
    difficulty: "실전",
    tags: ["os", "운영체제", "스케줄링", "fcfs", "calculation"],
    prompt: "모든 프로세스가 동시에 도착하고 실행시간이 P1=3, P2=5, P3=2일 때 FCFS 순서가 P1→P2→P3이면 평균 대기시간을 쓰시오.",
    answer: "11/3 ≈ 3.67",
    hint: "각 대기시간은 0, 앞 프로세스 1개의 실행시간, 앞 프로세스 2개의 실행시간입니다.",
    explanation: "대기시간은 P1=0, P2=3, P3=3+5=8이고 평균은 (0+3+8)/3=11/3입니다.",
    confusion: "반환시간은 대기시간+실행시간이며 평균 대기시간과 다릅니다."
  },
  {
    id: "os-semaphore-01",
    kind: "choice",
    topic: "운영체제",
    difficulty: "기초",
    tags: ["os", "운영체제", "동기화", "세마포어"],
    prompt: "세마포어 값을 감소시키고 자원을 사용할 수 없으면 프로세스를 대기시키는 연산을 고르시오.",
    choices: ["① wait(P)", "② signal(V)", "③ fork", "④ dispatch"],
    answer: "① wait(P)",
    hint: "자원 획득을 요청하는 연산입니다.",
    explanation: "wait 또는 P 연산은 세마포어를 감소시키며 자원이 없을 때 대기하게 합니다. signal 또는 V는 반납을 알립니다.",
    confusion: "wait와 signal은 임계구역 상호배제와 프로세스 동기화에 사용됩니다."
  },
  {
    id: "os-fifo-page-01",
    kind: "concept",
    topic: "운영체제",
    difficulty: "실전",
    tags: ["os", "운영체제", "페이지", "fifo", "calculation"],
    prompt: "페이지 프레임이 3개이고 참조열이 1, 2, 3, 1, 4일 때 FIFO 페이지 교체에서 발생하는 페이지 부재 횟수를 쓰시오.",
    answer: "4회",
    hint: "처음 1, 2, 3은 모두 부재이고 다시 나온 1은 적중입니다.",
    explanation: "1·2·3을 처음 적재할 때 3회, 1은 적중, 4가 들어오며 가장 먼저 들어온 1을 교체해 총 4회입니다.",
    confusion: "FIFO는 최근 사용 시점이 아니라 메모리에 들어온 순서만 봅니다."
  },
  {
    id: "os-state-01",
    kind: "choice",
    topic: "운영체제",
    difficulty: "기초",
    tags: ["os", "운영체제", "프로세스", "상태"],
    prompt: "CPU를 할당받을 준비는 되었지만 아직 실행하지 않는 프로세스 상태를 고르시오.",
    choices: ["① Ready", "② Running", "③ Blocked", "④ Terminated"],
    answer: "① Ready",
    hint: "CPU만 기다리는 상태입니다.",
    explanation: "Ready 상태는 실행에 필요한 준비를 마치고 스케줄러의 CPU 할당을 기다립니다.",
    confusion: "Blocked 또는 Waiting은 입출력 완료나 특정 사건을 기다리는 상태입니다."
  },
  {
    id: "linux-permission-01",
    kind: "concept",
    topic: "리눅스",
    difficulty: "실전",
    tags: ["linux", "리눅스", "permission", "calculation"],
    prompt: "리눅스 파일 권한 `rwxr-xr--`를 8진수 숫자로 쓰시오.",
    answer: "754",
    hint: "r=4, w=2, x=1을 사용자·그룹·기타 순서로 더합니다.",
    explanation: "소유자는 rwx=7, 그룹은 r-x=5, 기타 사용자는 r--=4이므로 754입니다.",
    confusion: "세 자리 숫자는 각각 소유자, 그룹, 기타 사용자의 권한을 나타냅니다."
  },
  {
    id: "linux-chmod-01",
    kind: "choice",
    topic: "리눅스",
    difficulty: "기초",
    tags: ["linux", "리눅스", "permission", "command"],
    prompt: "리눅스에서 파일 권한을 변경하는 명령어를 고르시오.",
    choices: ["① chmod", "② pwd", "③ ps", "④ grep"],
    answer: "① chmod",
    hint: "change mode의 약어입니다.",
    explanation: "chmod는 숫자 모드나 기호 모드를 사용해 파일과 디렉터리의 접근 권한을 변경합니다.",
    confusion: "chown은 소유자나 그룹을 변경하고 chmod는 권한 비트를 변경합니다."
  },
  {
    id: "linux-grep-01",
    kind: "concept",
    topic: "리눅스",
    difficulty: "기초",
    tags: ["linux", "리눅스", "command", "text"],
    prompt: "텍스트에서 지정한 패턴과 일치하는 행을 검색하는 리눅스 명령어를 쓰시오.",
    answer: "grep",
    hint: "로그에서 특정 단어가 포함된 줄을 찾을 때 자주 사용합니다.",
    explanation: "grep은 파일이나 표준 입력에서 문자열 또는 정규표현식 패턴에 일치하는 행을 출력합니다.",
    confusion: "find는 주로 파일명과 경로·속성으로 파일을 찾고 grep은 파일 내용의 패턴을 검색합니다."
  },
  {
    id: "linux-ps-01",
    kind: "choice",
    topic: "리눅스",
    difficulty: "기초",
    tags: ["linux", "리눅스", "process", "command"],
    prompt: "현재 실행 중인 프로세스 정보를 확인하는 대표 명령어를 고르시오.",
    choices: ["① ps", "② mkdir", "③ cp", "④ tar"],
    answer: "① ps",
    hint: "process status의 약어입니다.",
    explanation: "ps는 현재 프로세스의 PID, 상태, 실행 명령 등의 정보를 표시합니다.",
    confusion: "top은 프로세스와 자원 사용량을 지속적으로 갱신해 보여주는 대화형 도구입니다."
  },
  {
    id: "linux-pipe-01",
    kind: "concept",
    topic: "리눅스",
    difficulty: "기초",
    tags: ["linux", "리눅스", "shell", "pipe"],
    prompt: "앞 명령의 표준 출력을 뒤 명령의 표준 입력으로 연결하는 셸 기호를 쓰시오.",
    answer: "| (파이프)",
    hint: "`ps | grep node`처럼 사용합니다.",
    explanation: "파이프 기호는 한 명령의 출력을 다음 명령의 입력으로 전달해 작은 명령들을 조합할 수 있게 합니다.",
    confusion: ">는 출력을 파일로 덮어쓰고 >>는 파일 끝에 추가합니다."
  },
  {
    id: "linux-redirection-01",
    kind: "choice",
    topic: "리눅스",
    difficulty: "실전",
    tags: ["linux", "리눅스", "shell", "redirection"],
    prompt: "명령의 표준 출력을 기존 파일의 끝에 추가하는 리다이렉션 기호를 고르시오.",
    choices: ["① >", "② >>", "③ <", "④ |"],
    answer: "② >>",
    hint: "파일을 덮어쓰지 않고 이어서 기록합니다.",
    explanation: ">>는 표준 출력을 파일 뒤에 추가하고 >는 파일을 새로 만들거나 기존 내용을 덮어씁니다.",
    confusion: "파이프 |는 파일이 아니라 다른 명령의 표준 입력으로 출력을 전달합니다."
  },
  {
    id: "linux-signal-01",
    kind: "concept",
    topic: "리눅스",
    difficulty: "실전",
    tags: ["linux", "리눅스", "process", "signal"],
    prompt: "프로세스에 정상 종료를 요청하는 기본 `kill PID` 명령이 보내는 대표 시그널을 쓰시오.",
    answer: "SIGTERM(15)",
    hint: "강제 종료 SIGKILL보다 먼저 사용하는 정상 종료 요청입니다.",
    explanation: "인자를 생략한 kill은 일반적으로 SIGTERM을 보내 프로세스가 정리 작업 후 종료할 기회를 줍니다.",
    confusion: "SIGKILL(9)은 프로세스가 처리하거나 무시할 수 없는 강제 종료 신호이므로 마지막 수단으로 사용합니다."
  }
];
