import type { StudyQuestion } from "../types";

export const DATA_STRUCTURE_ALGORITHM_QUESTIONS: StudyQuestion[] = [
  {
    id: "ds-stack-01",
    kind: "choice",
    topic: "자료구조",
    difficulty: "기초",
    tags: ["data-structure", "자료구조", "stack"],
    prompt: "스택(Stack)의 데이터 입출력 원칙을 고르시오.",
    choices: ["① LIFO", "② FIFO", "③ 무작위 접근만 가능", "④ 항상 정렬된 순서"],
    answer: "① LIFO",
    hint: "가장 나중에 들어온 데이터가 가장 먼저 나옵니다.",
    explanation: "스택은 Last In First Out 구조로 push한 데이터 중 가장 최근 데이터를 pop으로 먼저 꺼냅니다.",
    confusion: "큐는 먼저 들어온 데이터가 먼저 나오는 FIFO 구조입니다."
  },
  {
    id: "ds-queue-01",
    kind: "concept",
    topic: "자료구조",
    difficulty: "기초",
    tags: ["data-structure", "자료구조", "queue"],
    prompt: "데이터가 들어온 순서대로 처리되는 First In First Out 자료구조를 쓰시오.",
    answer: "큐(Queue)",
    hint: "대기열처럼 먼저 온 데이터가 먼저 처리됩니다.",
    explanation: "큐는 rear에서 삽입하고 front에서 삭제하여 먼저 들어온 원소가 먼저 나갑니다.",
    confusion: "우선순위 큐는 단순 도착 순서가 아니라 우선순위에 따라 원소를 꺼냅니다."
  },
  {
    id: "ds-tree-traversal-01",
    kind: "concept",
    topic: "자료구조",
    difficulty: "실전",
    tags: ["data-structure", "자료구조", "tree", "calculation"],
    prompt: "루트 A의 왼쪽 자식이 B, 오른쪽 자식이 C일 때 이진트리를 전위 순회한 결과를 쓰시오.",
    answer: "A, B, C",
    hint: "전위 순회는 루트부터 방문합니다.",
    explanation: "전위 순회 순서는 루트→왼쪽 부분트리→오른쪽 부분트리이므로 A, B, C입니다.",
    confusion: "중위 순회는 B, A, C이고 후위 순회는 B, C, A입니다."
  },
  {
    id: "ds-bst-01",
    kind: "choice",
    topic: "자료구조",
    difficulty: "실전",
    tags: ["data-structure", "자료구조", "tree", "bst"],
    prompt: "이진 탐색 트리의 일반적인 저장 규칙으로 가장 알맞은 것을 고르시오.",
    choices: ["① 왼쪽에는 작은 키, 오른쪽에는 큰 키를 둔다", "② 모든 노드는 자식을 정확히 두 개 가져야 한다", "③ 루트가 항상 최솟값이다", "④ 삽입 순서와 관계없이 항상 완전 균형을 이룬다"],
    answer: "① 왼쪽에는 작은 키, 오른쪽에는 큰 키를 둔다",
    hint: "각 노드를 기준으로 키의 대소 관계를 유지합니다.",
    explanation: "이진 탐색 트리는 보통 각 노드보다 작은 키를 왼쪽, 큰 키를 오른쪽 부분트리에 배치합니다.",
    confusion: "일반 이진 탐색 트리는 자동으로 균형을 보장하지 않아 한쪽으로 치우칠 수 있습니다."
  },
  {
    id: "ds-hash-collision-01",
    kind: "concept",
    topic: "자료구조",
    difficulty: "심화",
    tags: ["data-structure", "자료구조", "hash", "algorithm"],
    prompt: "서로 다른 키를 해시 함수에 넣었지만 같은 해시 주소가 계산되는 현상을 쓰시오.",
    answer: "해시 충돌(Hash Collision)",
    hint: "체이닝이나 개방 주소법으로 처리할 수 있습니다.",
    explanation: "해시 충돌은 서로 다른 키가 같은 버킷이나 주소에 매핑되는 현상이며 별도의 충돌 해결 전략이 필요합니다.",
    confusion: "좋은 해시 함수는 충돌 가능성을 줄이지만 유한한 테이블에서는 충돌을 완전히 없애기 어렵습니다."
  },
  {
    id: "ds-graph-bfs-01",
    kind: "choice",
    topic: "자료구조",
    difficulty: "기초",
    tags: ["data-structure", "자료구조", "graph", "algorithm"],
    prompt: "그래프의 너비 우선 탐색(BFS)을 구현할 때 주로 사용하는 자료구조를 고르시오.",
    choices: ["① Queue", "② Stack", "③ Heap만 사용", "④ Hash 함수만 사용"],
    answer: "① Queue",
    hint: "가까운 정점을 먼저 방문한 순서를 유지합니다.",
    explanation: "BFS는 발견한 정점을 큐에 넣고 먼저 발견한 정점부터 꺼내 인접 정점을 탐색합니다.",
    confusion: "DFS는 재귀 호출이나 스택을 이용해 한 경로를 깊게 탐색합니다."
  },
  {
    id: "ds-heap-01",
    kind: "choice",
    topic: "자료구조",
    difficulty: "실전",
    tags: ["data-structure", "자료구조", "heap", "tree"],
    prompt: "최대 힙(Max Heap)의 조건으로 가장 알맞은 것을 고르시오.",
    choices: ["① 부모 키가 자식 키보다 크거나 같다", "② 왼쪽 자식만 가질 수 있다", "③ 중위 순회하면 항상 오름차순이다", "④ 루트가 최솟값이다"],
    answer: "① 부모 키가 자식 키보다 크거나 같다",
    hint: "가장 큰 값이 루트에 위치합니다.",
    explanation: "최대 힙은 완전 이진트리 형태이며 각 부모의 키가 자식 키보다 크거나 같아 루트가 최댓값입니다.",
    confusion: "힙은 형제나 서로 다른 부분트리 사이의 전체 정렬 순서까지 보장하지 않습니다."
  },
  {
    id: "ds-circular-queue-01",
    kind: "concept",
    topic: "자료구조",
    difficulty: "실전",
    tags: ["data-structure", "자료구조", "queue", "circular"],
    prompt: "배열의 마지막 위치 다음을 첫 위치와 연결해 빈 공간을 재사용하는 큐를 쓰시오.",
    answer: "원형 큐(Circular Queue)",
    hint: "front와 rear를 나머지 연산으로 순환시킵니다.",
    explanation: "원형 큐는 배열을 논리적으로 원형으로 연결해 삭제로 생긴 앞부분 공간을 다시 사용합니다.",
    confusion: "선형 큐는 rear가 끝에 도달하면 앞쪽이 비어 있어도 단순 구현에서는 더 삽입하지 못할 수 있습니다."
  },
  {
    id: "ds-postfix-01",
    kind: "concept",
    topic: "자료구조",
    difficulty: "심화",
    tags: ["data-structure", "자료구조", "stack", "calculation"],
    prompt: "후위 표기식 `5 2 + 3 *`의 계산 결과를 쓰시오.",
    answer: "21",
    hint: "5와 2를 더한 결과에 3을 곱합니다.",
    explanation: "5와 2를 스택에서 꺼내 더해 7을 넣고, 다시 7과 3을 곱해 21을 얻습니다.",
    confusion: "후위 표기식에서는 연산자를 만났을 때 피연산자를 꺼내며 괄호가 필요하지 않습니다."
  },
  {
    id: "ds-linked-list-01",
    kind: "choice",
    topic: "자료구조",
    difficulty: "기초",
    tags: ["data-structure", "자료구조", "linked-list"],
    prompt: "연결 리스트의 일반적인 특징으로 가장 알맞은 것을 고르시오.",
    choices: ["① 노드가 다음 노드의 주소를 저장할 수 있다", "② 모든 원소가 반드시 연속된 메모리에 있어야 한다", "③ 임의 위치 접근이 항상 O(1)이다", "④ 포인터나 참조가 필요 없다"],
    answer: "① 노드가 다음 노드의 주소를 저장할 수 있다",
    hint: "데이터와 연결 정보를 가진 노드로 구성됩니다.",
    explanation: "연결 리스트는 각 노드가 데이터와 다른 노드를 가리키는 연결 정보를 저장해 비연속 메모리에서도 순서를 구성합니다.",
    confusion: "배열은 인덱스로 빠르게 접근하지만 연결 리스트는 보통 앞에서부터 순차 탐색해야 합니다."
  },
  {
    id: "algo-bubble-01",
    kind: "concept",
    topic: "알고리즘",
    difficulty: "기초",
    tags: ["algorithm", "알고리즘", "sort", "calculation"],
    prompt: "배열 [4, 2, 3, 1]에 오름차순 버블 정렬의 첫 번째 전체 패스를 수행한 결과를 쓰시오.",
    answer: "[2, 3, 1, 4]",
    hint: "인접한 두 수를 왼쪽부터 비교해 큰 수를 오른쪽으로 이동시킵니다.",
    explanation: "4와 2, 4와 3, 4와 1을 차례로 교환하여 가장 큰 4가 마지막으로 이동합니다.",
    confusion: "첫 패스만으로 전체 배열이 정렬되는 것은 아니며 최댓값 하나의 위치가 확정됩니다."
  },
  {
    id: "algo-binary-search-01",
    kind: "concept",
    topic: "알고리즘",
    difficulty: "실전",
    tags: ["algorithm", "알고리즘", "search", "calculation"],
    prompt: "정렬된 배열 [1, 3, 5, 7, 9, 11, 13]에서 이진 탐색으로 11을 찾을 때 비교되는 값을 순서대로 쓰시오.",
    answer: "7, 11",
    hint: "먼저 가운데 값 7과 비교한 뒤 오른쪽 절반의 가운데를 봅니다.",
    explanation: "가운데 7보다 11이 크므로 오른쪽 구간 [9,11,13]을 선택하고 그 가운데 11을 찾아 종료합니다.",
    confusion: "이진 탐색은 데이터가 정렬되어 있어야 올바르게 범위를 절반씩 줄일 수 있습니다."
  },
  {
    id: "algo-big-o-01",
    kind: "choice",
    topic: "알고리즘",
    difficulty: "기초",
    tags: ["algorithm", "알고리즘", "complexity", "calculation"],
    prompt: "각각 n번 반복되는 두 반복문이 중첩되어 내부 연산이 실행될 때 시간복잡도를 고르시오.",
    choices: ["① O(1)", "② O(log n)", "③ O(n)", "④ O(n²)"],
    answer: "④ O(n²)",
    hint: "바깥 반복 한 번마다 안쪽 반복이 n번 실행됩니다.",
    explanation: "전체 실행 횟수는 n×n에 비례하므로 시간복잡도는 O(n²)입니다.",
    confusion: "서로 이어진 반복문은 보통 실행 횟수를 더하지만 중첩 반복문은 곱합니다."
  },
  {
    id: "algo-quick-01",
    kind: "choice",
    topic: "알고리즘",
    difficulty: "심화",
    tags: ["algorithm", "알고리즘", "sort", "quick-sort"],
    prompt: "퀵 정렬의 핵심 동작으로 가장 알맞은 것을 고르시오.",
    choices: ["① 피벗을 기준으로 작은 값과 큰 값을 분할한다", "② 항상 인접 원소만 한 번 비교한다", "③ 추가 조건 없이 최악에도 항상 O(n log n)이다", "④ 키를 해시 주소로 변환한다"],
    answer: "① 피벗을 기준으로 작은 값과 큰 값을 분할한다",
    hint: "분할 정복과 피벗을 사용합니다.",
    explanation: "퀵 정렬은 피벗을 선택하고 원소를 피벗보다 작은 그룹과 큰 그룹으로 분할한 뒤 재귀적으로 정렬합니다.",
    confusion: "피벗 선택과 입력 상태에 따라 최악의 시간복잡도는 O(n²)가 될 수 있습니다."
  },
  {
    id: "algo-merge-01",
    kind: "concept",
    topic: "알고리즘",
    difficulty: "실전",
    tags: ["algorithm", "알고리즘", "sort", "merge-sort"],
    prompt: "합병 정렬(Merge Sort)의 일반적인 최악 시간복잡도를 쓰시오.",
    answer: "O(n log n)",
    hint: "배열을 절반으로 나누는 단계와 각 단계의 병합 비용을 곱합니다.",
    explanation: "log n개의 분할 단계마다 전체 n개 원소를 병합하므로 최악 시간복잡도도 O(n log n)입니다.",
    confusion: "합병 정렬은 안정 정렬이지만 배열 구현에서는 병합을 위한 추가 메모리가 필요할 수 있습니다."
  },
  {
    id: "algo-dijkstra-01",
    kind: "choice",
    topic: "알고리즘",
    difficulty: "심화",
    tags: ["algorithm", "알고리즘", "graph", "shortest-path"],
    prompt: "일반적인 다익스트라 알고리즘을 그대로 적용하기 어려운 그래프를 고르시오.",
    choices: ["① 음수 가중치 간선이 있는 그래프", "② 모든 가중치가 양수인 그래프", "③ 정점이 하나인 그래프", "④ 무방향 양수 가중치 그래프"],
    answer: "① 음수 가중치 간선이 있는 그래프",
    hint: "한 번 확정한 최단거리가 나중에 더 작아질 가능성을 생각하세요.",
    explanation: "다익스트라는 선택한 최단거리가 확정된다는 가정에 의존하므로 음수 간선이 있으면 일반적으로 올바른 결과를 보장하지 않습니다.",
    confusion: "음수 간선을 다룰 때는 벨만-포드 같은 알고리즘을 고려할 수 있습니다."
  },
  {
    id: "algo-greedy-01",
    kind: "concept",
    topic: "알고리즘",
    difficulty: "실전",
    tags: ["algorithm", "알고리즘", "greedy"],
    prompt: "매 단계에서 현재 상황에 가장 좋아 보이는 선택을 하여 해를 구성하는 알고리즘 기법을 쓰시오.",
    answer: "그리디 알고리즘(Greedy Algorithm, 탐욕법)",
    hint: "지역적으로 최적인 선택을 반복합니다.",
    explanation: "그리디 알고리즘은 각 단계의 최선 선택을 되돌리지 않고 이어가며 문제에 따라 전체 최적해를 얻습니다.",
    confusion: "모든 문제에서 지역 최적 선택이 전역 최적해를 보장하지 않으므로 그리디 선택 속성을 확인해야 합니다."
  },
  {
    id: "algo-recursion-02",
    kind: "code",
    topic: "알고리즘",
    difficulty: "기초",
    tags: ["algorithm", "알고리즘", "recursion", "calculation", "code", "python"],
    prompt: ["다음 Python 코드의 출력값을 쓰시오.", "```python", "def f(n):", "    return 1 if n <= 1 else n * f(n - 1)", "print(f(4))", "```"].join("\n"),
    answer: "24",
    hint: "4×3×2×1을 계산합니다.",
    explanation: "재귀 호출이 f(1)에서 1을 반환하고 2, 3, 4를 차례로 곱해 24가 됩니다.",
    confusion: "재귀 함수에는 호출을 끝내는 기저 조건이 반드시 필요합니다."
  },
  {
    id: "algo-dp-01",
    kind: "choice",
    topic: "알고리즘",
    difficulty: "심화",
    tags: ["algorithm", "알고리즘", "dynamic-programming"],
    prompt: "동적 계획법(DP)의 대표적인 특징으로 가장 알맞은 것을 고르시오.",
    choices: ["① 중복되는 부분 문제의 결과를 저장해 재사용한다", "② 항상 현재의 최선만 선택한다", "③ 정렬되지 않은 배열에는 사용할 수 없다", "④ 재귀를 절대 사용할 수 없다"],
    answer: "① 중복되는 부분 문제의 결과를 저장해 재사용한다",
    hint: "메모이제이션과 테이블 작성 방식을 떠올리세요.",
    explanation: "동적 계획법은 중복 부분 문제와 최적 부분 구조를 이용해 계산 결과를 저장하고 반복 계산을 줄입니다.",
    confusion: "그리디는 각 단계의 최선 선택을 사용하고 DP는 여러 부분 문제의 결과를 비교·조합할 수 있습니다."
  },
  {
    id: "algo-selection-count-01",
    kind: "concept",
    topic: "알고리즘",
    difficulty: "실전",
    tags: ["algorithm", "알고리즘", "sort", "calculation"],
    prompt: "원소가 5개인 배열을 기본 선택 정렬로 정렬할 때 원소 대소 비교 횟수를 쓰시오.",
    answer: "10회",
    hint: "4+3+2+1을 계산합니다.",
    explanation: "첫 위치에서 4회, 다음 위치에서 3회, 이어서 2회와 1회를 비교해 총 10회입니다.",
    confusion: "기본 선택 정렬의 비교 횟수는 입력 순서와 무관하게 n(n-1)/2입니다."
  }
];
