/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 100ffd2c6a70120e20d5c184b4e20fc3)
interface __BaseEnv_Env {
	DB: D1Database;
	SLACK_SIGNING_SECRET: string;
	SLACK_BOT_TOKEN: string;
	SLACK_CHANNEL_ID: string;
	SLACK_SQLD_CHANNEL_ID: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
