import type { StudyQuestion } from "../types";

export const SQLD_BASIC_QUESTIONS: StudyQuestion[] = [
  {
    id: "sqld-basic-001",
    kind: "choice",
    topic: "SQL 기본",
    difficulty: "기초",
    tags: ["sqld", "sql", "sql-basic", "select", "frequent"],
    prompt: "SELECT 문의 논리적인 처리 순서로 옳은 것은 무엇입니까?",
    choices: ["① SELECT → FROM → WHERE → ORDER BY", "② FROM → WHERE → GROUP BY → HAVING → SELECT → ORDER BY", "③ FROM → SELECT → HAVING → WHERE → ORDER BY", "④ WHERE → FROM → SELECT → GROUP BY → ORDER BY"],
    answer: "② FROM → WHERE → GROUP BY → HAVING → SELECT → ORDER BY",
    hint: "먼저 대상 테이블을 정하고 행을 거른 뒤 그룹을 만듭니다.",
    explanation: "일반적인 논리 처리 순서는 FROM, WHERE, GROUP BY, HAVING, SELECT, ORDER BY입니다.",
    confusion: "SQL을 작성하는 문법 순서와 DBMS가 논리적으로 처리하는 순서는 다릅니다."
  },
  {
    id: "sqld-basic-002",
    kind: "choice",
    topic: "SELECT",
    difficulty: "기초",
    tags: ["sqld", "sql", "sql-basic", "select"],
    prompt: "조회 결과에서 완전히 동일한 행의 중복을 제거하는 키워드는 무엇입니까?",
    choices: ["① UNIQUE KEY", "② DISTINCT", "③ ONLY", "④ GROUP ROW"],
    answer: "② DISTINCT",
    hint: "SELECT 바로 뒤에 작성합니다.",
    explanation: "SELECT DISTINCT는 선택한 컬럼 조합이 동일한 결과 행을 하나로 줄입니다.",
    confusion: "DISTINCT는 각 컬럼을 따로 중복 제거하는 것이 아니라 SELECT 목록 전체의 조합을 기준으로 합니다."
  },
  {
    id: "sqld-basic-003",
    kind: "choice",
    topic: "SELECT",
    difficulty: "실전",
    tags: ["sqld", "sql", "sql-basic", "select", "alias"],
    prompt: "SELECT salary * 12 AS annual_salary FROM employee ORDER BY annual_salary;에 대한 설명으로 옳은 것은 무엇입니까?",
    choices: ["① ORDER BY에서는 별칭을 사용할 수 없다", "② annual_salary는 원본 테이블에 반드시 존재해야 한다", "③ SELECT에서 지정한 별칭으로 정렬할 수 있다", "④ AS는 테이블 별칭에만 사용할 수 있다"],
    answer: "③ SELECT에서 지정한 별칭으로 정렬할 수 있다",
    hint: "ORDER BY는 SELECT 목록이 만들어진 뒤 처리됩니다.",
    explanation: "ORDER BY에서는 SELECT 절에서 정의한 컬럼 별칭을 참조할 수 있습니다.",
    confusion: "WHERE는 SELECT보다 먼저 처리되므로 같은 SELECT 절에서 만든 별칭을 일반적으로 참조할 수 없습니다."
  },
  {
    id: "sqld-basic-004",
    kind: "choice",
    topic: "WHERE",
    difficulty: "기초",
    tags: ["sqld", "sql", "sql-basic", "where", "frequent"],
    prompt: "salary가 3000 이상 5000 이하인 행을 찾는 조건으로 옳은 것은 무엇입니까?",
    choices: ["① salary BETWEEN 3000 AND 5000", "② salary IN 3000 TO 5000", "③ salary > 3000 AND salary < 5000", "④ salary LIKE '3000-5000'"],
    answer: "① salary BETWEEN 3000 AND 5000",
    hint: "BETWEEN은 양쪽 경곗값을 포함합니다.",
    explanation: "BETWEEN 3000 AND 5000은 salary >= 3000 AND salary <= 5000과 같습니다.",
    confusion: "초과·미만 조건이 필요하면 BETWEEN 대신 비교 연산자를 직접 사용해야 합니다."
  },
  {
    id: "sqld-basic-005",
    kind: "choice",
    topic: "WHERE",
    difficulty: "기초",
    tags: ["sqld", "sql", "sql-basic", "where", "null", "frequent"],
    prompt: "commission 값이 NULL인 행을 찾는 조건은 무엇입니까?",
    choices: ["① commission = NULL", "② commission == NULL", "③ commission IS NULL", "④ commission EQUALS NULL"],
    answer: "③ commission IS NULL",
    hint: "NULL은 일반 비교 연산자의 대상이 되는 값이 아닙니다.",
    explanation: "NULL 여부는 IS NULL 또는 IS NOT NULL 조건으로 검사합니다.",
    confusion: "commission = NULL의 결과는 TRUE가 아니라 UNKNOWN이므로 WHERE 절에서 선택되지 않습니다."
  },
  {
    id: "sqld-basic-006",
    kind: "choice",
    topic: "WHERE",
    difficulty: "실전",
    tags: ["sqld", "sql", "sql-basic", "where", "operator"],
    prompt: "WHERE dept_id = 10 OR dept_id = 20 AND salary >= 5000의 해석으로 옳은 것은 무엇입니까?",
    choices: ["① (dept_id = 10 OR dept_id = 20) AND salary >= 5000", "② dept_id = 10 OR (dept_id = 20 AND salary >= 5000)", "③ dept_id IN (10, 20) OR salary >= 5000", "④ 항상 FALSE이다"],
    answer: "② dept_id = 10 OR (dept_id = 20 AND salary >= 5000)",
    hint: "AND가 OR보다 우선합니다.",
    explanation: "논리 연산자는 NOT, AND, OR 순으로 우선하므로 AND 조건이 먼저 묶입니다.",
    confusion: "의도를 명확하게 전달하려면 우선순위에 의존하기보다 괄호를 작성하는 편이 안전합니다."
  },
  {
    id: "sqld-basic-007",
    kind: "choice",
    topic: "WHERE",
    difficulty: "기초",
    tags: ["sqld", "sql", "sql-basic", "where"],
    prompt: "dept_id가 10, 20, 30 중 하나인 행을 찾는 가장 간결한 조건은 무엇입니까?",
    choices: ["① dept_id BETWEEN 10 AND 30", "② dept_id IN (10, 20, 30)", "③ dept_id LIKE '10,20,30'", "④ dept_id = ALL (10, 20, 30)"],
    answer: "② dept_id IN (10, 20, 30)",
    hint: "목록 안의 값 중 하나와 일치하는지 검사합니다.",
    explanation: "IN 목록은 여러 OR 동등 비교를 간결하게 표현합니다.",
    confusion: "BETWEEN 10 AND 30은 11이나 25 같은 중간값도 포함하므로 같은 조건이 아닙니다."
  },
  {
    id: "sqld-basic-008",
    kind: "choice",
    topic: "WHERE",
    difficulty: "심화",
    tags: ["sqld", "sql", "sql-basic", "where", "null", "frequent"],
    prompt: "WHERE employee_id NOT IN (100, 200, NULL)의 결과가 예상보다 나오지 않을 수 있는 이유는 무엇입니까?",
    choices: ["① NOT IN은 숫자에 사용할 수 없어서", "② 목록의 NULL 비교가 UNKNOWN을 만들어 전체 조건이 TRUE가 되지 않아서", "③ NULL이 자동으로 0으로 변환되어서", "④ NOT IN은 한 개 값만 허용해서"],
    answer: "② 목록의 NULL 비교가 UNKNOWN을 만들어 전체 조건이 TRUE가 되지 않아서",
    hint: "NOT IN은 목록의 모든 값과 다르다는 조건입니다.",
    explanation: "목록에 NULL이 있으면 어떤 값도 NULL과 다르다고 확정할 수 없어 조건 결과에 UNKNOWN이 포함됩니다.",
    confusion: "서브쿼리 결과에 NULL이 들어올 가능성이 있다면 NULL을 제외하거나 NOT EXISTS 사용을 검토해야 합니다."
  },
  {
    id: "sqld-basic-009",
    kind: "choice",
    topic: "WHERE",
    difficulty: "기초",
    tags: ["sqld", "sql", "sql-basic", "where", "like"],
    prompt: "name이 '김'으로 시작하는 행을 찾는 조건은 무엇입니까?",
    choices: ["① name LIKE '%김'", "② name LIKE '김%'", "③ name LIKE '_김'", "④ name = '김%'"],
    answer: "② name LIKE '김%'",
    hint: "%는 길이가 0 이상인 임의의 문자열을 뜻합니다.",
    explanation: "'김%' 패턴은 첫 글자가 김이고 뒤에 어떤 문자열이든 올 수 있는 값을 찾습니다.",
    confusion: "언더스코어(_)는 정확히 한 글자를, 퍼센트(%)는 0글자 이상의 문자열을 의미합니다."
  },
  {
    id: "sqld-basic-010",
    kind: "choice",
    topic: "함수",
    difficulty: "기초",
    tags: ["sqld", "sql", "sql-basic", "function", "null"],
    prompt: "COALESCE(commission, bonus, 0)의 반환값에 대한 설명으로 옳은 것은 무엇입니까?",
    choices: ["① 세 값을 모두 더한다", "② 왼쪽부터 처음 만나는 NULL이 아닌 값을 반환한다", "③ 가장 큰 값을 반환한다", "④ 항상 0을 반환한다"],
    answer: "② 왼쪽부터 처음 만나는 NULL이 아닌 값을 반환한다",
    hint: "후보 값을 왼쪽부터 차례대로 확인합니다.",
    explanation: "COALESCE는 인수 중 첫 번째 NULL이 아닌 값을 반환합니다.",
    confusion: "모든 인수가 NULL이면 COALESCE의 결과도 NULL입니다. 마지막에 0을 두면 그 경우 0이 됩니다."
  },
  {
    id: "sqld-basic-011",
    kind: "choice",
    topic: "집계 함수",
    difficulty: "기초",
    tags: ["sqld", "sql", "sql-basic", "aggregate", "frequent"],
    prompt: "전체 10행 중 commission이 NULL이 아닌 행이 6행일 때 COUNT(*)와 COUNT(commission)의 결과는 무엇입니까?",
    choices: ["① 10과 10", "② 6과 10", "③ 10과 6", "④ 6과 6"],
    answer: "③ 10과 6",
    hint: "별표는 행 자체를 세고 컬럼 인수는 NULL을 제외합니다.",
    explanation: "COUNT(*)는 모든 행을 세며 COUNT(commission)은 commission이 NULL이 아닌 행만 셉니다.",
    confusion: "COUNT(상수)는 상수가 NULL이 아닌 한 모든 행을 셉니다."
  },
  {
    id: "sqld-basic-012",
    kind: "choice",
    topic: "집계 함수",
    difficulty: "실전",
    tags: ["sqld", "sql", "sql-basic", "aggregate", "null"],
    prompt: "salary 값이 100, 200, NULL인 세 행에 대해 AVG(salary)의 결과는 무엇입니까?",
    choices: ["① 100", "② 150", "③ 200", "④ NULL"],
    answer: "② 150",
    hint: "AVG는 NULL인 행을 분모와 분자에서 제외합니다.",
    explanation: "AVG(salary)는 NULL을 제외한 100과 200의 평균이므로 150입니다.",
    confusion: "NULL을 0으로 포함하려면 AVG(COALESCE(salary, 0))처럼 명시해야 하며 결과가 달라집니다."
  },
  {
    id: "sqld-basic-013",
    kind: "choice",
    topic: "GROUP BY",
    difficulty: "기초",
    tags: ["sqld", "sql", "sql-basic", "group-by", "frequent"],
    prompt: "부서별 평균 급여를 구하는 SQL로 옳은 것은 무엇입니까?",
    choices: ["① SELECT dept_id, AVG(salary) FROM employee", "② SELECT dept_id, AVG(salary) FROM employee GROUP BY dept_id", "③ SELECT AVG(salary) FROM employee ORDER BY dept_id", "④ SELECT dept_id FROM employee HAVING AVG(salary)"],
    answer: "② SELECT dept_id, AVG(salary) FROM employee GROUP BY dept_id",
    hint: "집계 기준으로 출력할 일반 컬럼을 그룹화해야 합니다.",
    explanation: "부서번호로 행을 그룹화한 뒤 각 그룹의 AVG(salary)를 계산해야 합니다.",
    confusion: "집계 함수와 함께 SELECT하는 일반 컬럼은 원칙적으로 GROUP BY에 포함되어야 합니다."
  },
  {
    id: "sqld-basic-014",
    kind: "choice",
    topic: "HAVING",
    difficulty: "기초",
    tags: ["sqld", "sql", "sql-basic", "having", "frequent"],
    prompt: "사원 수가 5명 이상인 부서만 조회하려고 합니다. 그룹 결과를 거르는 절은 무엇입니까?",
    choices: ["① WHERE", "② HAVING", "③ ORDER BY", "④ DISTINCT"],
    answer: "② HAVING",
    hint: "COUNT 결과는 그룹이 만들어진 뒤 알 수 있습니다.",
    explanation: "HAVING은 GROUP BY로 만들어진 그룹에 집계 조건을 적용합니다.",
    confusion: "WHERE는 그룹화 전에 개별 행을 거르므로 집계 함수를 조건에 직접 사용할 수 없습니다."
  },
  {
    id: "sqld-basic-015",
    kind: "choice",
    topic: "GROUP BY",
    difficulty: "실전",
    tags: ["sqld", "sql", "sql-basic", "group-by"],
    prompt: "GROUP BY dept_id, job_id의 의미로 옳은 것은 무엇입니까?",
    choices: ["① dept_id 그룹과 job_id 그룹을 서로 따로 만든다", "② dept_id와 job_id의 조합이 같은 행끼리 그룹화한다", "③ 두 컬럼 중 하나만 같은 행을 그룹화한다", "④ 두 컬럼의 값을 더한 결과로 그룹화한다"],
    answer: "② dept_id와 job_id의 조합이 같은 행끼리 그룹화한다",
    hint: "여러 컬럼은 하나의 복합 그룹 기준입니다.",
    explanation: "GROUP BY에 여러 표현식을 나열하면 그 값들의 조합별로 그룹이 생성됩니다.",
    confusion: "각 컬럼별 소계까지 함께 원한다면 ROLLUP, CUBE 또는 GROUPING SETS를 검토합니다."
  },
  {
    id: "sqld-basic-016",
    kind: "choice",
    topic: "ORDER BY",
    difficulty: "기초",
    tags: ["sqld", "sql", "sql-basic", "order-by"],
    prompt: "ORDER BY dept_id ASC, salary DESC의 정렬 방식으로 옳은 것은 무엇입니까?",
    choices: ["① 급여 내림차순만 적용한다", "② 부서번호 오름차순으로 먼저 정렬하고 같은 부서 안에서 급여 내림차순으로 정렬한다", "③ 두 컬럼을 모두 내림차순 정렬한다", "④ 두 컬럼을 문자열로 합쳐 정렬한다"],
    answer: "② 부서번호 오름차순으로 먼저 정렬하고 같은 부서 안에서 급여 내림차순으로 정렬한다",
    hint: "앞에 적은 정렬 키가 우선합니다.",
    explanation: "ORDER BY는 나열한 표현식 순서대로 우선순위를 적용합니다.",
    confusion: "ASC가 기본값이므로 dept_id 뒤의 ASC는 생략할 수 있지만 salary의 DESC는 유지해야 합니다."
  },
  {
    id: "sqld-basic-017",
    kind: "choice",
    topic: "CASE",
    difficulty: "실전",
    tags: ["sqld", "sql", "sql-basic", "case"],
    prompt: "CASE WHEN score >= 60 THEN 'PASS' ELSE 'FAIL' END의 결과로 옳은 것은 무엇입니까?",
    choices: ["① score가 60 이상이면 PASS, 아니면 FAIL", "② score가 60이면 항상 NULL", "③ score가 60 미만이면 PASS", "④ 모든 행에서 FAIL"],
    answer: "① score가 60 이상이면 PASS, 아니면 FAIL",
    hint: "WHEN 조건이 참이면 THEN 값을 선택합니다.",
    explanation: "검색 CASE 표현식은 위에서부터 조건을 평가하고 처음 참인 THEN 결과를 반환하며 없으면 ELSE를 반환합니다.",
    confusion: "ELSE를 생략하고 어떤 WHEN도 참이 아니면 결과는 NULL입니다."
  },
  {
    id: "sqld-basic-018",
    kind: "choice",
    topic: "함수",
    difficulty: "기초",
    tags: ["sqld", "sql", "sql-basic", "function"],
    prompt: "문자열 양쪽 끝의 공백을 제거하는 표준 함수는 무엇입니까?",
    choices: ["① TRIM", "② ROUND", "③ LENGTH", "④ REPLACE ALL"],
    answer: "① TRIM",
    hint: "문자열의 시작과 끝을 다듬습니다.",
    explanation: "TRIM은 기본적으로 문자열 양끝의 공백을 제거합니다.",
    confusion: "문자열 중간의 공백까지 모두 제거하는 함수가 아니며, DBMS별 문법으로 제거할 문자를 지정할 수 있습니다."
  },
  {
    id: "sqld-basic-019",
    kind: "choice",
    topic: "함수",
    difficulty: "실전",
    tags: ["sqld", "sql", "sql-basic", "function", "calculation"],
    prompt: "ROUND(15.678, 1)의 일반적인 결과는 무엇입니까?",
    choices: ["① 15", "② 15.6", "③ 15.7", "④ 16.0"],
    answer: "③ 15.7",
    hint: "소수점 둘째 자리에서 반올림하여 첫째 자리까지 남깁니다.",
    explanation: "두 번째 인수 1은 소수점 첫째 자리까지 표시하라는 뜻이므로 15.678은 15.7이 됩니다.",
    confusion: "TRUNC는 지정 위치 아래를 버리고 ROUND는 반올림합니다."
  },
  {
    id: "sqld-basic-020",
    kind: "choice",
    topic: "함수",
    difficulty: "실전",
    tags: ["sqld", "sql", "sql-basic", "function"],
    prompt: "LOWER('SqlD')의 결과는 무엇입니까?",
    choices: ["① SQLD", "② sqld", "③ SqlD", "④ NULL"],
    answer: "② sqld",
    hint: "모든 영문자를 소문자로 변환합니다.",
    explanation: "LOWER는 문자열의 영문 대문자를 소문자로 변환합니다.",
    confusion: "대소문자 비교 결과는 데이터베이스의 문자 정렬 규칙에 따라서도 달라질 수 있습니다."
  },
  {
    id: "sqld-basic-021",
    kind: "choice",
    topic: "함수",
    difficulty: "심화",
    tags: ["sqld", "sql", "sql-basic", "function", "null"],
    prompt: "NULLIF(a, b)의 동작으로 옳은 것은 무엇입니까?",
    choices: ["① a와 b가 같으면 NULL, 다르면 a를 반환한다", "② a와 b가 같으면 b를 반환한다", "③ 두 값 중 큰 값을 반환한다", "④ NULL을 0으로 바꾼다"],
    answer: "① a와 b가 같으면 NULL, 다르면 a를 반환한다",
    hint: "두 값이 같은지 비교한 결과에 따라 첫 번째 값을 숨깁니다.",
    explanation: "NULLIF(a, b)는 a = b이면 NULL을, 그렇지 않으면 a를 반환합니다.",
    confusion: "COALESCE는 여러 값 중 첫 번째 NULL이 아닌 값을 찾는 함수로 목적이 다릅니다."
  },
  {
    id: "sqld-basic-022",
    kind: "choice",
    topic: "조인",
    difficulty: "기초",
    tags: ["sqld", "sql", "sql-basic", "join", "frequent"],
    prompt: "INNER JOIN의 결과에 포함되는 행은 무엇입니까?",
    choices: ["① 양쪽 테이블에서 조인 조건이 일치하는 행", "② 왼쪽 테이블의 모든 행", "③ 오른쪽 테이블의 모든 행", "④ 두 테이블의 모든 가능한 행 조합"],
    answer: "① 양쪽 테이블에서 조인 조건이 일치하는 행",
    hint: "양쪽에 짝이 있는 행만 남습니다.",
    explanation: "INNER JOIN은 조인 조건을 만족하는 양쪽 테이블의 행만 반환합니다.",
    confusion: "조건과 일치하지 않는 한쪽 행도 보존하려면 OUTER JOIN을 사용합니다."
  },
  {
    id: "sqld-basic-023",
    kind: "choice",
    topic: "조인",
    difficulty: "기초",
    tags: ["sqld", "sql", "sql-basic", "join", "outer-join", "frequent"],
    prompt: "A LEFT OUTER JOIN B ON A.id = B.id의 결과로 옳은 것은 무엇입니까?",
    choices: ["① B의 모든 행을 반드시 보존한다", "② A의 모든 행을 보존하고 B에 짝이 없으면 B 컬럼을 NULL로 채운다", "③ 일치하는 행만 반환한다", "④ 항상 카티션 곱을 만든다"],
    answer: "② A의 모든 행을 보존하고 B에 짝이 없으면 B 컬럼을 NULL로 채운다",
    hint: "LEFT는 왼쪽 테이블을 기준으로 보존한다는 뜻입니다.",
    explanation: "LEFT OUTER JOIN은 왼쪽 테이블의 모든 행을 반환하고 오른쪽에 일치 행이 없으면 오른쪽 컬럼을 NULL로 표시합니다.",
    confusion: "오른쪽 테이블 조건을 WHERE에 잘못 작성하면 NULL 보완 행이 제거되어 INNER JOIN처럼 동작할 수 있습니다."
  },
  {
    id: "sqld-basic-024",
    kind: "choice",
    topic: "조인",
    difficulty: "실전",
    tags: ["sqld", "sql", "sql-basic", "join"],
    prompt: "A 테이블이 3행, B 테이블이 4행일 때 조인 조건 없이 CROSS JOIN한 결과 행 수는 몇 개입니까?",
    choices: ["① 3", "② 4", "③ 7", "④ 12"],
    answer: "④ 12",
    hint: "각 A 행이 모든 B 행과 한 번씩 결합합니다.",
    explanation: "CROSS JOIN은 두 테이블의 카티션 곱을 생성하므로 3 × 4 = 12행입니다.",
    confusion: "의도하지 않은 조인 조건 누락도 큰 카티션 곱을 만들 수 있으므로 주의해야 합니다."
  },
  {
    id: "sqld-basic-025",
    kind: "choice",
    topic: "표준 조인",
    difficulty: "실전",
    tags: ["sqld", "sql", "sql-basic", "join", "standard-join"],
    prompt: "JOIN ... USING(dept_id)에 대한 설명으로 옳은 것은 무엇입니까?",
    choices: ["① 양쪽 테이블에 같은 이름의 dept_id 컬럼이 있어야 한다", "② 조인 조건을 작성할 수 없다", "③ 서로 다른 이름의 컬럼만 사용할 수 있다", "④ CROSS JOIN에서만 사용할 수 있다"],
    answer: "① 양쪽 테이블에 같은 이름의 dept_id 컬럼이 있어야 한다",
    hint: "USING 뒤에는 양쪽에서 공통으로 사용하는 컬럼명을 적습니다.",
    explanation: "USING은 양쪽 테이블에 동일한 이름으로 존재하는 조인 컬럼을 간단히 지정합니다.",
    confusion: "컬럼명이 다르거나 복잡한 조건이 필요하면 ON 절을 사용합니다."
  },
  {
    id: "sqld-basic-026",
    kind: "choice",
    topic: "표준 조인",
    difficulty: "심화",
    tags: ["sqld", "sql", "sql-basic", "join", "standard-join"],
    prompt: "NATURAL JOIN 사용 시 주의할 점으로 가장 적절한 것은 무엇입니까?",
    choices: ["① 같은 이름의 컬럼을 자동으로 조인 조건에 사용하므로 스키마 변경에 따라 결과가 달라질 수 있다", "② 반드시 CROSS JOIN보다 많은 행이 나온다", "③ 조인 결과에 NULL을 사용할 수 없다", "④ 숫자 컬럼만 조인할 수 있다"],
    answer: "① 같은 이름의 컬럼을 자동으로 조인 조건에 사용하므로 스키마 변경에 따라 결과가 달라질 수 있다",
    hint: "조인 컬럼을 SQL에 명시하지 않습니다.",
    explanation: "NATURAL JOIN은 양쪽의 같은 이름 컬럼을 자동으로 모두 조인 조건에 사용하므로 의도하지 않은 컬럼이 포함될 수 있습니다.",
    confusion: "명확성과 변경 안전성을 위해 실무에서는 ON이나 USING으로 조인 컬럼을 명시하는 경우가 많습니다."
  },
  {
    id: "sqld-basic-027",
    kind: "choice",
    topic: "조인",
    difficulty: "심화",
    tags: ["sqld", "sql", "sql-basic", "join", "outer-join", "frequent"],
    prompt: "다음 중 LEFT JOIN의 왼쪽 행을 모두 보존하는 조건 작성은 무엇입니까?",
    choices: ["① FROM A LEFT JOIN B ON A.id = B.id WHERE B.active = 'Y'", "② FROM A LEFT JOIN B ON A.id = B.id AND B.active = 'Y'", "③ FROM A, B WHERE A.id = B.id AND B.active = 'Y'", "④ FROM A INNER JOIN B ON A.id = B.id"],
    answer: "② FROM A LEFT JOIN B ON A.id = B.id AND B.active = 'Y'",
    hint: "오른쪽 테이블을 제한하는 조건을 조인 과정에 포함합니다.",
    explanation: "B.active 조건을 ON에 두면 조건에 맞는 B가 없어도 A 행은 NULL 보완되어 남습니다.",
    confusion: "WHERE B.active = 'Y'는 NULL 보완 행을 제거하여 결과적으로 A의 일부 행을 잃게 합니다."
  },
  {
    id: "sqld-basic-028",
    kind: "choice",
    topic: "조인",
    difficulty: "기초",
    tags: ["sqld", "sql", "sql-basic", "join"],
    prompt: "FULL OUTER JOIN의 결과로 가장 적절한 것은 무엇입니까?",
    choices: ["① 양쪽에서 일치하는 행만 반환한다", "② 왼쪽의 불일치 행만 반환한다", "③ 양쪽의 일치 행과 양쪽 각각의 불일치 행을 모두 반환한다", "④ 두 테이블의 행을 세로로 이어 붙인다"],
    answer: "③ 양쪽의 일치 행과 양쪽 각각의 불일치 행을 모두 반환한다",
    hint: "LEFT OUTER JOIN과 RIGHT OUTER JOIN의 보존 범위를 모두 가집니다.",
    explanation: "FULL OUTER JOIN은 일치 행뿐 아니라 양쪽 테이블의 매칭되지 않은 행도 NULL 보완하여 반환합니다.",
    confusion: "UNION은 두 SELECT 결과를 세로로 결합하며 FULL OUTER JOIN과 목적이 다릅니다."
  },
  {
    id: "sqld-basic-029",
    kind: "choice",
    topic: "SQL 기본",
    difficulty: "실전",
    tags: ["sqld", "sql", "sql-basic", "null", "calculation"],
    prompt: "price가 100이고 discount가 NULL일 때 price - discount의 결과는 무엇입니까?",
    choices: ["① 100", "② 0", "③ NULL", "④ 오류"],
    answer: "③ NULL",
    hint: "NULL이 포함된 일반 산술 연산의 결과를 생각하세요.",
    explanation: "NULL은 알 수 없는 값이므로 NULL과 수행한 산술 연산 결과도 NULL입니다.",
    confusion: "할인액이 없음을 0으로 처리하려면 price - COALESCE(discount, 0)처럼 변환해야 합니다."
  },
  {
    id: "sqld-basic-030",
    kind: "choice",
    topic: "WHERE",
    difficulty: "실전",
    tags: ["sqld", "sql", "sql-basic", "where", "null"],
    prompt: "WHERE NOT (status = 'DONE') 조건에서 status가 NULL인 행은 어떻게 됩니까?",
    choices: ["① 반드시 선택된다", "② 선택되지 않는다", "③ DONE으로 변경된다", "④ 빈 문자열로 비교된다"],
    answer: "② 선택되지 않는다",
    hint: "NULL 비교는 UNKNOWN이고 NOT UNKNOWN도 UNKNOWN입니다.",
    explanation: "status = 'DONE'이 UNKNOWN이면 NOT을 적용해도 UNKNOWN이며 WHERE는 TRUE인 행만 선택합니다.",
    confusion: "NULL까지 포함하려면 status <> 'DONE' OR status IS NULL처럼 의도를 명시해야 합니다."
  },
  {
    id: "sqld-basic-031",
    kind: "choice",
    topic: "GROUP BY",
    difficulty: "심화",
    tags: ["sqld", "sql", "sql-basic", "group-by", "null"],
    prompt: "GROUP BY dept_id를 수행할 때 dept_id가 NULL인 여러 행은 일반적으로 어떻게 처리됩니까?",
    choices: ["① 각 행이 서로 다른 그룹이 된다", "② 모두 하나의 NULL 그룹으로 묶인다", "③ GROUP BY에서 자동 삭제된다", "④ 오류가 발생한다"],
    answer: "② 모두 하나의 NULL 그룹으로 묶인다",
    hint: "그룹화에서는 NULL 값들을 같은 그룹으로 다룹니다.",
    explanation: "GROUP BY는 해당 표현식이 NULL인 행들을 하나의 그룹으로 묶습니다.",
    confusion: "일반 비교에서 NULL = NULL은 TRUE가 아니지만 그룹화와 DISTINCT에서는 NULL들을 같은 값처럼 묶습니다."
  },
  {
    id: "sqld-basic-032",
    kind: "choice",
    topic: "집계 함수",
    difficulty: "심화",
    tags: ["sqld", "sql", "sql-basic", "aggregate"],
    prompt: "COUNT(DISTINCT dept_id)의 의미는 무엇입니까?",
    choices: ["① 전체 행 수", "② NULL을 포함한 dept_id 컬럼 수", "③ NULL을 제외한 서로 다른 dept_id 값의 수", "④ 중복된 dept_id 값의 수"],
    answer: "③ NULL을 제외한 서로 다른 dept_id 값의 수",
    hint: "COUNT는 NULL을 제외하고 DISTINCT는 중복을 제거합니다.",
    explanation: "COUNT(DISTINCT expression)은 NULL이 아닌 고유한 표현식 값의 개수를 반환합니다.",
    confusion: "전체 행 수가 필요하면 COUNT(*)를 사용합니다."
  },
  {
    id: "sqld-basic-033",
    kind: "choice",
    topic: "HAVING",
    difficulty: "실전",
    tags: ["sqld", "sql", "sql-basic", "having"],
    prompt: "부서별 평균 급여가 4000 이상인 부서의 평균 급여를 구하는 SQL은 무엇입니까?",
    choices: ["① SELECT dept_id, AVG(salary) FROM employee WHERE AVG(salary) >= 4000 GROUP BY dept_id", "② SELECT dept_id, AVG(salary) FROM employee GROUP BY dept_id HAVING AVG(salary) >= 4000", "③ SELECT dept_id FROM employee HAVING salary >= 4000", "④ SELECT AVG(salary) FROM employee ORDER BY AVG(salary) >= 4000"],
    answer: "② SELECT dept_id, AVG(salary) FROM employee GROUP BY dept_id HAVING AVG(salary) >= 4000",
    hint: "평균은 그룹이 만들어진 후 계산됩니다.",
    explanation: "부서별로 그룹화한 뒤 HAVING에서 각 그룹의 평균 급여를 제한해야 합니다.",
    confusion: "WHERE에는 같은 쿼리 블록의 집계 함수를 직접 조건으로 사용할 수 없습니다."
  },
  {
    id: "sqld-basic-034",
    kind: "choice",
    topic: "SELECT",
    difficulty: "실전",
    tags: ["sqld", "sql", "sql-basic", "select"],
    prompt: "SELECT 절에 dept_id, job_id, COUNT(*)가 있고 GROUP BY dept_id만 작성했다면 일반적으로 발생하는 문제는 무엇입니까?",
    choices: ["① job_id가 집계되지도 GROUP BY에 포함되지도 않아 오류가 발생한다", "② COUNT(*)를 사용할 수 없어 오류가 발생한다", "③ dept_id가 자동으로 제거된다", "④ 항상 정상 실행되어 job_id의 최솟값을 반환한다"],
    answer: "① job_id가 집계되지도 GROUP BY에 포함되지도 않아 오류가 발생한다",
    hint: "한 부서 그룹 안에는 여러 job_id가 있을 수 있습니다.",
    explanation: "그룹별 결과에서 일반 컬럼을 SELECT하려면 그 컬럼이 GROUP BY에 포함되거나 집계 함수로 단일 값이 되어야 합니다.",
    confusion: "일부 DBMS의 느슨한 설정에서 임의 값이 나올 수 있지만 표준적이고 안전한 SQL은 아닙니다."
  },
  {
    id: "sqld-basic-035",
    kind: "choice",
    topic: "SQL 기본",
    difficulty: "심화",
    tags: ["sqld", "sql", "sql-basic", "select", "calculation", "frequent"],
    prompt: "salary 값이 1000, 2000, NULL인 테이블에서 SELECT SUM(salary), COUNT(salary), COUNT(*)를 실행한 결과는 무엇입니까?",
    choices: ["① 3000, 2, 3", "② 3000, 3, 3", "③ NULL, 2, 3", "④ 3000, 2, 2"],
    answer: "① 3000, 2, 3",
    hint: "SUM과 컬럼 COUNT는 NULL을 제외하지만 COUNT(*)는 행을 셉니다.",
    explanation: "SUM은 NULL을 제외해 3000이고 COUNT(salary)는 2, COUNT(*)는 전체 3행입니다.",
    confusion: "모든 salary가 NULL이면 SUM(salary)는 0이 아니라 NULL이고 COUNT(salary)는 0입니다."
  }
];
