import type { StudyQuestion } from "../types";

export const SQLD_ADVANCED_QUESTIONS: StudyQuestion[] = [
  {
    id: "sqld-advanced-001",
    kind: "choice",
    topic: "서브쿼리",
    difficulty: "기초",
    tags: ["sqld", "sql", "sql-advanced", "subquery", "frequent"],
    prompt: "스칼라 서브쿼리가 반환해야 하는 결과 형태는 무엇입니까?",
    choices: ["① 여러 컬럼의 여러 행", "② 한 컬럼의 한 행 이하", "③ 반드시 두 행", "④ 테이블 전체"],
    answer: "② 한 컬럼의 한 행 이하",
    hint: "하나의 값이 올 수 있는 자리에 사용합니다.",
    explanation: "스칼라 서브쿼리는 단일 값을 반환해야 하므로 한 컬럼의 최대 한 행을 반환합니다.",
    confusion: "결과가 0행이면 NULL로 취급되고 두 행 이상이면 단일 값으로 사용할 수 없어 오류가 발생합니다."
  },
  {
    id: "sqld-advanced-002",
    kind: "choice",
    topic: "서브쿼리",
    difficulty: "실전",
    tags: ["sqld", "sql", "sql-advanced", "subquery", "correlated"],
    prompt: "상관 서브쿼리에 대한 설명으로 옳은 것은 무엇입니까?",
    choices: ["① 바깥 쿼리의 컬럼을 참조할 수 있다", "② 항상 한 번만 실행된다", "③ FROM 절에서만 사용할 수 있다", "④ 집계 함수를 사용할 수 없다"],
    answer: "① 바깥 쿼리의 컬럼을 참조할 수 있다",
    hint: "내부 쿼리와 외부 쿼리가 값으로 연결됩니다.",
    explanation: "상관 서브쿼리는 바깥 쿼리의 현재 행 컬럼을 내부 조건에서 참조합니다.",
    confusion: "논리적으로 바깥 행마다 평가되는 형태지만 실제 실행 방식은 옵티마이저가 변환할 수 있습니다."
  },
  {
    id: "sqld-advanced-003",
    kind: "choice",
    topic: "서브쿼리",
    difficulty: "기초",
    tags: ["sqld", "sql", "sql-advanced", "subquery", "exists", "frequent"],
    prompt: "EXISTS 서브쿼리의 TRUE 여부를 결정하는 기준은 무엇입니까?",
    choices: ["① 반환 컬럼의 합계", "② 반환된 행이 하나 이상 존재하는지 여부", "③ 첫 번째 컬럼이 1인지 여부", "④ 서브쿼리의 컬럼 수"],
    answer: "② 반환된 행이 하나 이상 존재하는지 여부",
    hint: "SELECT 목록의 실제 값보다 행의 존재가 중요합니다.",
    explanation: "EXISTS는 서브쿼리 결과 행이 하나라도 있으면 TRUE를 반환합니다.",
    confusion: "EXISTS 안에서 SELECT 1이나 SELECT *를 사용해도 존재 여부 판단 자체는 같습니다."
  },
  {
    id: "sqld-advanced-004",
    kind: "choice",
    topic: "서브쿼리",
    difficulty: "실전",
    tags: ["sqld", "sql", "sql-advanced", "subquery", "exists", "null"],
    prompt: "관련 자식 행이 하나도 없는 부모 행을 찾을 때 NULL 문제를 피하기 좋은 방법은 무엇입니까?",
    choices: ["① NOT EXISTS", "② CROSS JOIN", "③ UNION ALL", "④ ROLLUP"],
    answer: "① NOT EXISTS",
    hint: "일치하는 자식 행의 부재를 직접 검사합니다.",
    explanation: "NOT EXISTS는 상관 조건을 만족하는 자식 행이 없을 때 TRUE가 되어 미참조 부모를 찾기 적합합니다.",
    confusion: "NOT IN 서브쿼리 결과에 NULL이 포함되면 UNKNOWN 때문에 예상과 다른 결과가 나올 수 있습니다."
  },
  {
    id: "sqld-advanced-005",
    kind: "choice",
    topic: "서브쿼리",
    difficulty: "기초",
    tags: ["sqld", "sql", "sql-advanced", "subquery"],
    prompt: "단일 행 서브쿼리와 함께 사용하기 적절한 연산자는 무엇입니까?",
    choices: ["① =", "② IN만 가능", "③ ANY만 가능", "④ ALL만 가능"],
    answer: "① =",
    hint: "비교 대상 값이 하나입니다.",
    explanation: "단일 행 서브쿼리는 =, <>, >, >=, <, <= 같은 단일 행 비교 연산자와 사용할 수 있습니다.",
    confusion: "서브쿼리가 여러 행을 반환할 수 있다면 IN, ANY, ALL 또는 EXISTS 같은 다중 행 연산자를 사용해야 합니다."
  },
  {
    id: "sqld-advanced-006",
    kind: "choice",
    topic: "서브쿼리",
    difficulty: "실전",
    tags: ["sqld", "sql", "sql-advanced", "subquery", "all", "calculation"],
    prompt: "salary > ALL (1000, 2000, 3000)을 만족하는 salary의 조건은 무엇입니까?",
    choices: ["① 1000보다 크면 된다", "② 2000보다 크면 된다", "③ 3000보다 커야 한다", "④ 세 값 중 하나와 같아야 한다"],
    answer: "③ 3000보다 커야 한다",
    hint: "목록의 모든 값보다 커야 합니다.",
    explanation: "> ALL은 비교 집합의 모든 값보다 커야 하므로 최댓값 3000보다 큰 값이 조건을 만족합니다.",
    confusion: "> ANY는 집합의 값 중 하나보다만 크면 되므로 일반적으로 최솟값보다 큰 조건과 대응합니다."
  },
  {
    id: "sqld-advanced-007",
    kind: "choice",
    topic: "서브쿼리",
    difficulty: "실전",
    tags: ["sqld", "sql", "sql-advanced", "subquery", "any", "calculation"],
    prompt: "score >= ANY (60, 80, 90)을 만족하는 score로 옳은 것은 무엇입니까?",
    choices: ["① 50", "② 60", "③ 59", "④ NULL만 가능"],
    answer: "② 60",
    hint: "목록 중 적어도 하나와의 비교가 참이면 됩니다.",
    explanation: "60은 목록의 60 이상이므로 >= ANY 조건을 만족합니다.",
    confusion: ">= ALL이었다면 가장 큰 값인 90 이상이어야 합니다."
  },
  {
    id: "sqld-advanced-008",
    kind: "choice",
    topic: "서브쿼리",
    difficulty: "심화",
    tags: ["sqld", "sql", "sql-advanced", "subquery", "inline-view"],
    prompt: "FROM 절에 작성해 하나의 테이블처럼 사용하는 서브쿼리를 일반적으로 무엇이라 합니까?",
    choices: ["① 스칼라 서브쿼리", "② 인라인 뷰", "③ 상수 서브쿼리", "④ 계층형 서브쿼리"],
    answer: "② 인라인 뷰",
    hint: "쿼리 결과 집합에 별칭을 붙여 외부 쿼리의 입력으로 사용합니다.",
    explanation: "FROM 절의 서브쿼리는 결과가 임시 테이블처럼 사용되므로 인라인 뷰라고 부릅니다.",
    confusion: "SELECT 목록의 단일 값 위치에 사용하는 것은 스칼라 서브쿼리입니다."
  },
  {
    id: "sqld-advanced-009",
    kind: "choice",
    topic: "집합 연산자",
    difficulty: "기초",
    tags: ["sqld", "sql", "sql-advanced", "set-operator", "frequent"],
    prompt: "UNION과 UNION ALL의 차이로 옳은 것은 무엇입니까?",
    choices: ["① UNION은 중복을 제거하고 UNION ALL은 중복을 유지한다", "② UNION ALL만 여러 SELECT를 결합할 수 있다", "③ UNION은 컬럼 수가 달라도 된다", "④ UNION ALL은 정렬을 반드시 수행한다"],
    answer: "① UNION은 중복을 제거하고 UNION ALL은 중복을 유지한다",
    hint: "ALL은 모든 결과 행을 그대로 보존합니다.",
    explanation: "UNION은 결합 결과의 중복 행을 제거하고 UNION ALL은 각 SELECT 결과를 그대로 이어 붙입니다.",
    confusion: "중복 제거가 필요 없으면 UNION ALL이 불필요한 중복 제거 작업을 피할 수 있습니다."
  },
  {
    id: "sqld-advanced-010",
    kind: "choice",
    topic: "집합 연산자",
    difficulty: "기초",
    tags: ["sqld", "sql", "sql-advanced", "set-operator"],
    prompt: "두 SELECT 결과에 공통으로 존재하는 행만 반환하는 집합 연산자는 무엇입니까?",
    choices: ["① UNION", "② INTERSECT", "③ EXCEPT", "④ CROSS JOIN"],
    answer: "② INTERSECT",
    hint: "두 집합의 교집합입니다.",
    explanation: "INTERSECT는 앞뒤 SELECT 결과에 모두 존재하는 행을 반환합니다.",
    confusion: "DBMS에 따라 차집합 연산자는 EXCEPT 또는 MINUS라는 이름을 사용합니다."
  },
  {
    id: "sqld-advanced-011",
    kind: "choice",
    topic: "집합 연산자",
    difficulty: "실전",
    tags: ["sqld", "sql", "sql-advanced", "set-operator"],
    prompt: "첫 번째 SELECT 결과에는 있고 두 번째 SELECT 결과에는 없는 행을 구하는 연산은 무엇입니까?",
    choices: ["① INTERSECT", "② UNION ALL", "③ EXCEPT 또는 MINUS", "④ NATURAL JOIN"],
    answer: "③ EXCEPT 또는 MINUS",
    hint: "첫 번째 집합에서 두 번째 집합을 뺍니다.",
    explanation: "차집합은 표준 SQL 계열에서 EXCEPT, Oracle에서는 MINUS로 표현합니다.",
    confusion: "연산 방향이 있으므로 앞뒤 SELECT의 순서를 바꾸면 결과도 달라집니다."
  },
  {
    id: "sqld-advanced-012",
    kind: "choice",
    topic: "집합 연산자",
    difficulty: "실전",
    tags: ["sqld", "sql", "sql-advanced", "set-operator"],
    prompt: "집합 연산자로 두 SELECT를 결합하기 위한 기본 조건으로 옳은 것은 무엇입니까?",
    choices: ["① 두 SELECT의 컬럼 수와 대응 컬럼의 데이터 유형이 호환되어야 한다", "② 두 테이블 이름이 같아야 한다", "③ 두 SELECT의 행 수가 같아야 한다", "④ 모든 컬럼에 기본키가 있어야 한다"],
    answer: "① 두 SELECT의 컬럼 수와 대응 컬럼의 데이터 유형이 호환되어야 한다",
    hint: "결과 행을 같은 열 구조로 세로 결합해야 합니다.",
    explanation: "집합 연산의 각 SELECT는 같은 수의 컬럼을 반환하고 위치별 데이터 타입이 서로 호환되어야 합니다.",
    confusion: "결과 컬럼명은 일반적으로 첫 번째 SELECT의 컬럼명 또는 별칭을 따릅니다."
  },
  {
    id: "sqld-advanced-013",
    kind: "choice",
    topic: "그룹 함수",
    difficulty: "실전",
    tags: ["sqld", "sql", "sql-advanced", "rollup", "frequent"],
    prompt: "GROUP BY ROLLUP(dept_id, job_id)이 생성하는 그룹으로 옳은 것은 무엇입니까?",
    choices: ["① (dept_id, job_id), (dept_id), 전체 합계", "② (dept_id), (job_id)만", "③ (job_id), 전체 합계만", "④ 상세 그룹만"],
    answer: "① (dept_id, job_id), (dept_id), 전체 합계",
    hint: "나열 순서의 오른쪽부터 단계적으로 제거합니다.",
    explanation: "ROLLUP(dept_id, job_id)은 상세 조합, dept_id 소계, 전체 합계를 계층적으로 생성합니다.",
    confusion: "job_id 단독 소계까지 필요하면 CUBE나 GROUPING SETS를 사용해야 합니다."
  },
  {
    id: "sqld-advanced-014",
    kind: "choice",
    topic: "그룹 함수",
    difficulty: "실전",
    tags: ["sqld", "sql", "sql-advanced", "cube"],
    prompt: "GROUP BY CUBE(a, b)가 만드는 그룹 조합은 무엇입니까?",
    choices: ["① (a,b)만", "② (a,b), (a), (b), 전체 합계", "③ (a), 전체 합계", "④ (b), 전체 합계"],
    answer: "② (a,b), (a), (b), 전체 합계",
    hint: "지정한 컬럼의 가능한 모든 소계 조합을 만듭니다.",
    explanation: "CUBE(a, b)는 두 컬럼 조합의 모든 부분집합에 대한 그룹을 생성합니다.",
    confusion: "ROLLUP은 계층 순서에 따른 소계를 만들고 CUBE는 가능한 조합 전체를 만듭니다."
  },
  {
    id: "sqld-advanced-015",
    kind: "choice",
    topic: "그룹 함수",
    difficulty: "심화",
    tags: ["sqld", "sql", "sql-advanced", "grouping-sets"],
    prompt: "GROUPING SETS((dept_id), (job_id), ())의 의미로 옳은 것은 무엇입니까?",
    choices: ["① 부서별, 직무별, 전체 합계를 각각 계산한다", "② 부서와 직무의 상세 조합만 계산한다", "③ 부서별 합계만 계산한다", "④ 빈 결과만 반환한다"],
    answer: "① 부서별, 직무별, 전체 합계를 각각 계산한다",
    hint: "빈 괄호는 전체 그룹을 의미합니다.",
    explanation: "GROUPING SETS는 필요한 그룹 조합을 명시하며 ()는 전체 합계를 나타냅니다.",
    confusion: "CUBE와 달리 원하지 않는 조합을 만들지 않고 필요한 집계 수준만 선택할 수 있습니다."
  },
  {
    id: "sqld-advanced-016",
    kind: "choice",
    topic: "그룹 함수",
    difficulty: "심화",
    tags: ["sqld", "sql", "sql-advanced", "grouping", "null"],
    prompt: "ROLLUP 결과의 NULL이 실제 데이터 NULL인지 소계 행 표시인지 구분하는 함수는 무엇입니까?",
    choices: ["① GROUPING", "② COALESCE", "③ COUNT", "④ NULLIF"],
    answer: "① GROUPING",
    hint: "집계로 생성된 컬럼이면 보통 1을 반환합니다.",
    explanation: "GROUPING(expression)은 ROLLUP이나 CUBE가 만든 집계 행의 해당 표현식이면 1, 일반 행이면 0을 반환합니다.",
    confusion: "COALESCE로 NULL 표시 문구는 바꿀 수 있지만 NULL의 발생 원인을 직접 구분하지는 못합니다."
  },
  {
    id: "sqld-advanced-017",
    kind: "choice",
    topic: "윈도우 함수",
    difficulty: "기초",
    tags: ["sqld", "sql", "sql-advanced", "window", "frequent"],
    prompt: "윈도우 함수와 GROUP BY 집계의 주요 차이로 옳은 것은 무엇입니까?",
    choices: ["① 윈도우 함수는 원래 행을 유지하면서 분석값을 덧붙일 수 있다", "② 윈도우 함수는 정렬할 수 없다", "③ GROUP BY는 집계 함수를 사용할 수 없다", "④ 윈도우 함수는 한 행만 반환한다"],
    answer: "① 윈도우 함수는 원래 행을 유지하면서 분석값을 덧붙일 수 있다",
    hint: "행 수가 줄어드는지 생각하세요.",
    explanation: "윈도우 함수는 결과 행을 그룹당 한 행으로 축약하지 않고 각 행에 그룹 분석값을 표시합니다.",
    confusion: "GROUP BY는 지정한 그룹별로 결과 행을 축약합니다."
  },
  {
    id: "sqld-advanced-018",
    kind: "choice",
    topic: "윈도우 함수",
    difficulty: "기초",
    tags: ["sqld", "sql", "sql-advanced", "window", "partition"],
    prompt: "SUM(salary) OVER (PARTITION BY dept_id)의 의미는 무엇입니까?",
    choices: ["① 전체 급여 합계를 한 행으로 반환한다", "② 각 행에 해당 부서의 급여 합계를 표시한다", "③ 부서별 행을 삭제한다", "④ 급여를 부서번호로 나눈다"],
    answer: "② 각 행에 해당 부서의 급여 합계를 표시한다",
    hint: "PARTITION BY가 분석 구간을 나눕니다.",
    explanation: "각 행은 유지되며 같은 dept_id 파티션의 salary 합계가 각 행에 표시됩니다.",
    confusion: "GROUP BY dept_id, SUM(salary)는 부서당 한 행을 반환합니다."
  },
  {
    id: "sqld-advanced-019",
    kind: "choice",
    topic: "윈도우 함수",
    difficulty: "실전",
    tags: ["sqld", "sql", "sql-advanced", "window", "rank", "frequent"],
    prompt: "점수가 100, 90, 90, 80일 때 RANK()로 내림차순 순위를 매긴 결과는 무엇입니까?",
    choices: ["① 1, 2, 2, 3", "② 1, 2, 2, 4", "③ 1, 2, 3, 4", "④ 1, 1, 2, 3"],
    answer: "② 1, 2, 2, 4",
    hint: "동점 다음 순위는 동점 인원만큼 건너뜁니다.",
    explanation: "RANK는 동점에 같은 순위를 부여하고 다음 순위를 건너뛰므로 1, 2, 2, 4가 됩니다.",
    confusion: "DENSE_RANK는 동점 다음 순위를 건너뛰지 않아 1, 2, 2, 3이 됩니다."
  },
  {
    id: "sqld-advanced-020",
    kind: "choice",
    topic: "윈도우 함수",
    difficulty: "실전",
    tags: ["sqld", "sql", "sql-advanced", "window", "dense-rank"],
    prompt: "점수가 100, 90, 90, 80일 때 DENSE_RANK() 결과는 무엇입니까?",
    choices: ["① 1, 2, 2, 3", "② 1, 2, 2, 4", "③ 1, 2, 3, 4", "④ 1, 1, 1, 2"],
    answer: "① 1, 2, 2, 3",
    hint: "동점은 같은 순위지만 다음 순위를 비우지 않습니다.",
    explanation: "DENSE_RANK는 동점에 같은 순위를 주고 다음 순위를 연속해서 부여합니다.",
    confusion: "ROW_NUMBER는 동점 여부와 관계없이 각 행에 서로 다른 연속 번호를 부여합니다."
  },
  {
    id: "sqld-advanced-021",
    kind: "choice",
    topic: "윈도우 함수",
    difficulty: "기초",
    tags: ["sqld", "sql", "sql-advanced", "window", "row-number"],
    prompt: "정렬 순서에 따라 각 행에 1부터 중복 없는 번호를 부여하는 함수는 무엇입니까?",
    choices: ["① RANK", "② DENSE_RANK", "③ ROW_NUMBER", "④ GROUPING"],
    answer: "③ ROW_NUMBER",
    hint: "동점이어도 행마다 다른 번호가 필요합니다.",
    explanation: "ROW_NUMBER는 지정한 정렬 순서대로 각 행에 고유한 연속 번호를 부여합니다.",
    confusion: "정렬 기준이 동률일 때 결과를 안정적으로 만들려면 유일한 추가 정렬 컬럼을 지정해야 합니다."
  },
  {
    id: "sqld-advanced-022",
    kind: "choice",
    topic: "윈도우 함수",
    difficulty: "실전",
    tags: ["sqld", "sql", "sql-advanced", "window", "lag"],
    prompt: "시간순 데이터에서 현재 행의 바로 이전 행 값을 가져오는 윈도우 함수는 무엇입니까?",
    choices: ["① LEAD", "② LAG", "③ FIRST", "④ PREV"],
    answer: "② LAG",
    hint: "뒤처진 값을 읽는다는 뜻의 이름입니다.",
    explanation: "LAG는 현재 행보다 앞선 행의 값을, LEAD는 뒤의 행 값을 참조합니다.",
    confusion: "어떤 행이 이전 행인지는 OVER 절의 ORDER BY로 결정합니다."
  },
  {
    id: "sqld-advanced-023",
    kind: "choice",
    topic: "윈도우 함수",
    difficulty: "실전",
    tags: ["sqld", "sql", "sql-advanced", "window", "lead"],
    prompt: "현재 행 다음에 오는 행의 값을 미리 조회하는 함수는 무엇입니까?",
    choices: ["① LAG", "② LEAD", "③ LAST_VALUE만 가능", "④ NEXT_ROW"],
    answer: "② LEAD",
    hint: "현재보다 앞서 있는 다음 값을 가져옵니다.",
    explanation: "LEAD는 윈도우 정렬 기준에서 현재 행 이후의 값을 참조합니다.",
    confusion: "행 순서를 지정하지 않으면 이전과 다음의 업무적 의미가 불분명해집니다."
  },
  {
    id: "sqld-advanced-024",
    kind: "choice",
    topic: "윈도우 함수",
    difficulty: "심화",
    tags: ["sqld", "sql", "sql-advanced", "window", "running-total", "calculation"],
    prompt: "날짜순 누적 합계를 구하는 표현으로 가장 적절한 것은 무엇입니까?",
    choices: ["① SUM(amount) OVER (ORDER BY sale_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW)", "② SUM(amount) GROUP BY sale_date DESC", "③ COUNT(amount) OVER ()", "④ amount + NEXT amount"],
    answer: "① SUM(amount) OVER (ORDER BY sale_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW)",
    hint: "첫 행부터 현재 행까지의 윈도우 프레임을 지정합니다.",
    explanation: "UNBOUNDED PRECEDING부터 CURRENT ROW까지의 SUM은 정렬 순서에 따른 누적 합계를 계산합니다.",
    confusion: "동일 날짜가 여러 행이면 원하는 동률 처리에 맞게 ROWS 또는 RANGE와 추가 정렬 기준을 선택해야 합니다."
  },
  {
    id: "sqld-advanced-025",
    kind: "choice",
    topic: "Top N 쿼리",
    difficulty: "실전",
    tags: ["sqld", "sql", "sql-advanced", "top-n", "frequent"],
    prompt: "부서별 급여 상위 3명을 구하는 방법으로 가장 적절한 것은 무엇입니까?",
    choices: ["① ROW_NUMBER() OVER (PARTITION BY dept_id ORDER BY salary DESC)를 구한 뒤 3 이하를 선택한다", "② 전체 결과에서 아무 행이나 3개 선택한다", "③ GROUP BY dept_id만 사용한다", "④ DISTINCT salary만 사용한다"],
    answer: "① ROW_NUMBER() OVER (PARTITION BY dept_id ORDER BY salary DESC)를 구한 뒤 3 이하를 선택한다",
    hint: "부서마다 번호를 다시 시작해야 합니다.",
    explanation: "PARTITION BY dept_id로 부서별 순번을 만들고 급여 내림차순 ROW_NUMBER가 3 이하인 행을 선택합니다.",
    confusion: "동점자를 모두 포함하려면 요구사항에 따라 RANK나 DENSE_RANK를 사용할 수 있습니다."
  },
  {
    id: "sqld-advanced-026",
    kind: "choice",
    topic: "Top N 쿼리",
    difficulty: "기초",
    tags: ["sqld", "sql", "sql-advanced", "top-n"],
    prompt: "ORDER BY score DESC FETCH FIRST 5 ROWS ONLY의 의미는 무엇입니까?",
    choices: ["① 점수가 낮은 5행", "② 점수가 높은 순으로 정렬한 첫 5행", "③ 임의의 5개 컬럼", "④ 다섯 번째 행만"],
    answer: "② 점수가 높은 순으로 정렬한 첫 5행",
    hint: "정렬 후 결과의 앞부분을 제한합니다.",
    explanation: "내림차순 정렬 결과에서 선두 5행만 반환하는 Top N 쿼리입니다.",
    confusion: "정렬 기준이 없으면 어떤 5행이 선택될지 보장하기 어렵습니다."
  },
  {
    id: "sqld-advanced-027",
    kind: "choice",
    topic: "Top N 쿼리",
    difficulty: "심화",
    tags: ["sqld", "sql", "sql-advanced", "top-n", "rank"],
    prompt: "상위 3등 안의 동점자를 모두 포함하려면 가장 적절한 순위 함수는 무엇입니까?",
    choices: ["① ROW_NUMBER", "② RANK", "③ COUNT", "④ NTILE(1)"],
    answer: "② RANK",
    hint: "동점자에게 같은 순위를 부여해야 합니다.",
    explanation: "RANK로 순위를 계산하고 3 이하를 선택하면 같은 점수의 동점자가 동일 순위로 함께 포함됩니다.",
    confusion: "ROW_NUMBER는 동점자에게도 다른 번호를 주므로 일부 동점자가 잘릴 수 있습니다."
  },
  {
    id: "sqld-advanced-028",
    kind: "choice",
    topic: "계층형 질의",
    difficulty: "기초",
    tags: ["sqld", "sql", "sql-advanced", "hierarchy", "self-join"],
    prompt: "사원 테이블에서 사원과 직속 상사를 같은 테이블끼리 연결할 때 사용하는 조인 형태는 무엇입니까?",
    choices: ["① 셀프 조인", "② CROSS JOIN만 가능", "③ FULL JOIN만 가능", "④ 집합 연산"],
    answer: "① 셀프 조인",
    hint: "같은 테이블에 서로 다른 별칭을 부여합니다.",
    explanation: "사원과 상사처럼 한 테이블 안의 행끼리 관계를 맺을 때 같은 테이블을 서로 다른 별칭으로 셀프 조인합니다.",
    confusion: "셀프 조인은 별도의 SQL 키워드가 아니라 같은 테이블을 두 번 참조하는 일반 조인입니다."
  },
  {
    id: "sqld-advanced-029",
    kind: "choice",
    topic: "계층형 질의",
    difficulty: "실전",
    tags: ["sqld", "sql", "sql-advanced", "hierarchy", "oracle"],
    prompt: "Oracle 계층형 질의에서 START WITH 절의 역할은 무엇입니까?",
    choices: ["① 계층 탐색을 시작할 루트 행을 지정한다", "② 결과 정렬 방향만 지정한다", "③ 반복을 종료할 행 수를 지정한다", "④ 컬럼 별칭을 지정한다"],
    answer: "① 계층 탐색을 시작할 루트 행을 지정한다",
    hint: "트리의 어느 노드부터 출발할지 정합니다.",
    explanation: "START WITH는 계층 전개의 시작점이 되는 루트 행 조건을 지정합니다.",
    confusion: "CONNECT BY는 부모와 자식의 연결 규칙을 정의합니다."
  },
  {
    id: "sqld-advanced-030",
    kind: "choice",
    topic: "계층형 질의",
    difficulty: "심화",
    tags: ["sqld", "sql", "sql-advanced", "hierarchy", "oracle"],
    prompt: "Oracle 계층형 질의에서 CONNECT_BY_ISLEAF가 1인 행은 무엇을 의미합니까?",
    choices: ["① 현재 결과의 루트 행", "② 현재 결과에서 자식이 없는 말단 행", "③ 순환이 발생한 행", "④ 항상 첫 번째 행"],
    answer: "② 현재 결과에서 자식이 없는 말단 행",
    hint: "leaf는 트리의 잎 노드입니다.",
    explanation: "CONNECT_BY_ISLEAF는 현재 계층 결과에서 더 내려갈 자식이 없는 행이면 1을 반환합니다.",
    confusion: "LEVEL은 루트부터 현재 행까지의 계층 깊이를 나타냅니다."
  },
  {
    id: "sqld-advanced-031",
    kind: "choice",
    topic: "PIVOT",
    difficulty: "실전",
    tags: ["sqld", "sql", "sql-advanced", "pivot"],
    prompt: "PIVOT 연산의 주된 목적은 무엇입니까?",
    choices: ["① 행의 구분값을 컬럼으로 전환해 집계 결과를 펼친다", "② 컬럼을 모두 삭제한다", "③ 테이블을 물리적으로 복제한다", "④ 트랜잭션을 취소한다"],
    answer: "① 행의 구분값을 컬럼으로 전환해 집계 결과를 펼친다",
    hint: "세로로 존재하는 분류 값을 가로 보고서 형태로 바꿉니다.",
    explanation: "PIVOT은 특정 컬럼의 값들을 새 컬럼 방향으로 펼치고 집계하여 교차표 형태를 만듭니다.",
    confusion: "단순 행·열 전환이 아니라 일반적으로 집계 함수와 함께 사용합니다."
  },
  {
    id: "sqld-advanced-032",
    kind: "choice",
    topic: "UNPIVOT",
    difficulty: "실전",
    tags: ["sqld", "sql", "sql-advanced", "unpivot"],
    prompt: "UNPIVOT 연산에 대한 설명으로 옳은 것은 무엇입니까?",
    choices: ["① 여러 컬럼 값을 행 방향으로 변환한다", "② 행을 컬럼으로만 변환한다", "③ 중복 행을 제거한다", "④ 인덱스를 생성한다"],
    answer: "① 여러 컬럼 값을 행 방향으로 변환한다",
    hint: "PIVOT의 반대 방향입니다.",
    explanation: "UNPIVOT은 컬럼으로 펼쳐진 값을 행 형태의 속성명과 값으로 변환합니다.",
    confusion: "UNPIVOT이 원래 PIVOT 이전의 상세 행을 완전히 복원하는 것은 아니며 집계로 사라진 정보는 되살릴 수 없습니다."
  },
  {
    id: "sqld-advanced-033",
    kind: "choice",
    topic: "정규 표현식",
    difficulty: "기초",
    tags: ["sqld", "sql", "sql-advanced", "regex"],
    prompt: "문자열이 지정한 정규 표현식 패턴과 일치하는지 검사하는 함수는 무엇입니까?",
    choices: ["① REGEXP_LIKE", "② REGEXP_REPLACE", "③ COALESCE", "④ GROUPING"],
    answer: "① REGEXP_LIKE",
    hint: "이름에 LIKE가 포함되어 있습니다.",
    explanation: "REGEXP_LIKE는 문자열이 정규 표현식 패턴과 일치하는지를 조건으로 검사합니다.",
    confusion: "REGEXP_REPLACE는 패턴에 일치하는 부분을 다른 문자열로 치환합니다."
  },
  {
    id: "sqld-advanced-034",
    kind: "choice",
    topic: "정규 표현식",
    difficulty: "실전",
    tags: ["sqld", "sql", "sql-advanced", "regex"],
    prompt: "문자열에서 숫자가 아닌 문자를 모두 제거하는 용도로 가장 적절한 함수는 무엇입니까?",
    choices: ["① REGEXP_REPLACE", "② RANK", "③ ROLLUP", "④ NULLIF"],
    answer: "① REGEXP_REPLACE",
    hint: "패턴에 맞는 부분을 빈 문자열로 치환합니다.",
    explanation: "REGEXP_REPLACE에서 숫자가 아닌 문자 패턴을 빈 문자열로 바꾸면 숫자만 남길 수 있습니다.",
    confusion: "단순 REPLACE는 고정된 문자열 치환에 적합하고 문자 종류 패턴에는 정규 표현식 함수가 유용합니다."
  },
  {
    id: "sqld-advanced-035",
    kind: "choice",
    topic: "윈도우 함수",
    difficulty: "심화",
    tags: ["sqld", "sql", "sql-advanced", "window", "ntile"],
    prompt: "정렬된 결과를 가능한 한 균등한 4개 그룹으로 나누고 그룹 번호를 부여하는 함수는 무엇입니까?",
    choices: ["① NTILE(4)", "② RANK(4)", "③ GROUPING(4)", "④ WIDTH(4)"],
    answer: "① NTILE(4)",
    hint: "타일을 나누듯 행을 지정한 개수의 버킷으로 분배합니다.",
    explanation: "NTILE(4)는 윈도우 정렬 순서에 따라 행을 4개 버킷으로 가능한 한 균등하게 나눕니다.",
    confusion: "행 수가 4로 나누어떨어지지 않으면 앞쪽 버킷이 한 행씩 더 가질 수 있습니다."
  }
];
