import type { StudyQuestion } from "../types";

export const SQLD_MANAGEMENT_QUESTIONS: StudyQuestion[] = [
  {
    id: "sqld-management-001",
    kind: "choice",
    topic: "관리 구문",
    difficulty: "기초",
    tags: ["sqld", "sql", "management", "dml", "frequent"],
    prompt: "테이블의 데이터를 조회·입력·수정·삭제하는 명령의 분류는 무엇입니까?",
    choices: ["① DDL", "② DML", "③ DCL", "④ TCL"],
    answer: "② DML",
    hint: "SELECT, INSERT, UPDATE, DELETE가 포함됩니다.",
    explanation: "DML은 테이블에 저장된 데이터를 조회하거나 변경하는 데이터 조작어입니다.",
    confusion: "DDL은 테이블 같은 객체 구조를 정의하고 DCL은 권한을 제어합니다."
  },
  {
    id: "sqld-management-002",
    kind: "choice",
    topic: "DML",
    difficulty: "기초",
    tags: ["sqld", "sql", "management", "dml"],
    prompt: "INSERT INTO employee (id, name) VALUES (1, 'Kim')에 대한 설명으로 옳은 것은 무엇입니까?",
    choices: ["① employee에 id와 name 값을 가진 한 행을 추가한다", "② employee의 모든 행을 삭제한다", "③ employee 테이블 구조를 변경한다", "④ id가 1인 행을 조회한다"],
    answer: "① employee에 id와 name 값을 가진 한 행을 추가한다",
    hint: "INSERT는 새로운 데이터를 입력합니다.",
    explanation: "지정한 컬럼 순서에 맞춰 값 한 행을 employee 테이블에 삽입합니다.",
    confusion: "생략한 컬럼은 기본값이 있으면 기본값, 없고 NULL을 허용하면 NULL이 저장될 수 있습니다."
  },
  {
    id: "sqld-management-003",
    kind: "choice",
    topic: "DML",
    difficulty: "실전",
    tags: ["sqld", "sql", "management", "dml", "frequent"],
    prompt: "UPDATE employee SET salary = salary * 1.1;을 WHERE 절 없이 실행하면 어떻게 됩니까?",
    choices: ["① 한 행만 수정된다", "② salary가 NULL인 행만 수정된다", "③ employee의 모든 행이 수정 대상이 된다", "④ 문법 오류가 발생한다"],
    answer: "③ employee의 모든 행이 수정 대상이 된다",
    hint: "대상 행을 제한하는 조건이 없습니다.",
    explanation: "WHERE 절이 없으면 테이블의 모든 행에 UPDATE가 적용됩니다.",
    confusion: "전체 변경이 의도된 경우도 있지만 실수 위험이 크므로 트랜잭션과 대상 건수 확인이 중요합니다."
  },
  {
    id: "sqld-management-004",
    kind: "choice",
    topic: "DML",
    difficulty: "실전",
    tags: ["sqld", "sql", "management", "dml", "merge"],
    prompt: "키가 일치하면 UPDATE하고 일치하지 않으면 INSERT하는 작업에 적합한 구문은 무엇입니까?",
    choices: ["① MERGE", "② REVOKE", "③ TRUNCATE", "④ SAVEPOINT"],
    answer: "① MERGE",
    hint: "두 데이터 집합을 비교해 일치 여부에 따라 동작을 나눕니다.",
    explanation: "MERGE는 기준 조건의 일치 여부에 따라 UPDATE와 INSERT 같은 작업을 한 구문에서 처리할 수 있습니다.",
    confusion: "세부 지원 문법은 DBMS마다 다를 수 있으므로 실제 환경의 MERGE 사양을 확인해야 합니다."
  },
  {
    id: "sqld-management-005",
    kind: "choice",
    topic: "TCL",
    difficulty: "기초",
    tags: ["sqld", "sql", "management", "tcl", "transaction", "frequent"],
    prompt: "현재 트랜잭션의 변경 내용을 영구적으로 반영하는 명령은 무엇입니까?",
    choices: ["① COMMIT", "② ROLLBACK", "③ SAVEPOINT", "④ REVOKE"],
    answer: "① COMMIT",
    hint: "트랜잭션을 성공 상태로 확정합니다.",
    explanation: "COMMIT은 현재 트랜잭션의 데이터 변경을 확정하여 다른 트랜잭션에서도 볼 수 있게 합니다.",
    confusion: "COMMIT 후에는 일반적인 ROLLBACK으로 해당 변경을 되돌릴 수 없습니다."
  },
  {
    id: "sqld-management-006",
    kind: "choice",
    topic: "TCL",
    difficulty: "실전",
    tags: ["sqld", "sql", "management", "tcl", "savepoint"],
    prompt: "트랜잭션 전체가 아니라 지정한 중간 지점 이후의 변경만 취소하려면 무엇을 사용합니까?",
    choices: ["① SAVEPOINT와 ROLLBACK TO SAVEPOINT", "② GRANT와 REVOKE", "③ CREATE와 DROP", "④ SELECT DISTINCT"],
    answer: "① SAVEPOINT와 ROLLBACK TO SAVEPOINT",
    hint: "먼저 되돌아갈 지점을 이름으로 표시합니다.",
    explanation: "SAVEPOINT로 트랜잭션 안의 중간 지점을 만들고 ROLLBACK TO로 그 이후 변경을 취소할 수 있습니다.",
    confusion: "일반 ROLLBACK은 보통 현재 트랜잭션 전체의 미확정 변경을 취소합니다."
  },
  {
    id: "sqld-management-007",
    kind: "choice",
    topic: "DDL",
    difficulty: "기초",
    tags: ["sqld", "sql", "management", "ddl"],
    prompt: "테이블의 구조를 생성·변경·삭제하는 명령의 분류는 무엇입니까?",
    choices: ["① DDL", "② DML", "③ DCL", "④ TCL"],
    answer: "① DDL",
    hint: "CREATE, ALTER, DROP이 대표적입니다.",
    explanation: "DDL은 데이터베이스 객체의 구조를 정의하는 데이터 정의어입니다.",
    confusion: "DELETE는 행 데이터를 지우는 DML이고 DROP은 객체 자체를 제거하는 DDL입니다."
  },
  {
    id: "sqld-management-008",
    kind: "choice",
    topic: "DDL",
    difficulty: "실전",
    tags: ["sqld", "sql", "management", "ddl", "truncate", "frequent"],
    prompt: "TRUNCATE TABLE에 대한 설명으로 가장 적절한 것은 무엇입니까?",
    choices: ["① 조건에 맞는 일부 행만 삭제한다", "② 테이블 구조는 남기고 전체 데이터를 빠르게 제거하는 DDL이다", "③ 테이블 구조까지 제거한다", "④ 조회 권한을 부여한다"],
    answer: "② 테이블 구조는 남기고 전체 데이터를 빠르게 제거하는 DDL이다",
    hint: "DROP과 달리 테이블 객체는 유지됩니다.",
    explanation: "TRUNCATE는 테이블 구조를 유지하면서 전체 행을 제거하는 DDL이며 일반적으로 WHERE 조건을 사용하지 않습니다.",
    confusion: "DELETE는 DML이라 조건 삭제가 가능하고 트랜잭션 처리 특성도 TRUNCATE와 다릅니다."
  },
  {
    id: "sqld-management-009",
    kind: "choice",
    topic: "DCL",
    difficulty: "기초",
    tags: ["sqld", "sql", "management", "dcl"],
    prompt: "사용자에게 테이블 조회 권한을 부여하는 명령은 무엇입니까?",
    choices: ["① GRANT SELECT", "② COMMIT SELECT", "③ ALTER SELECT", "④ MERGE SELECT"],
    answer: "① GRANT SELECT",
    hint: "권한을 준다는 뜻의 명령입니다.",
    explanation: "GRANT는 사용자나 역할에 객체 또는 시스템 권한을 부여하는 DCL입니다.",
    confusion: "이미 부여한 권한을 회수할 때는 REVOKE를 사용합니다."
  },
  {
    id: "sqld-management-010",
    kind: "choice",
    topic: "DDL",
    difficulty: "심화",
    tags: ["sqld", "sql", "management", "ddl", "oracle", "transaction"],
    prompt: "Oracle에서 DDL을 실행할 때의 트랜잭션 특성으로 옳은 것은 무엇입니까?",
    choices: ["① DDL 전후에 암시적 COMMIT이 발생할 수 있다", "② DDL은 언제나 일반 DML과 동일하게 ROLLBACK된다", "③ DDL은 트랜잭션과 전혀 관련이 없다", "④ DDL은 SAVEPOINT를 자동 생성한다"],
    answer: "① DDL 전후에 암시적 COMMIT이 발생할 수 있다",
    hint: "Oracle의 DDL은 미확정 DML에도 영향을 줄 수 있습니다.",
    explanation: "Oracle에서는 DDL 실행 전후에 암시적 COMMIT이 발생하므로 앞선 DML 변경이 확정될 수 있습니다.",
    confusion: "DDL의 트랜잭션 동작은 DBMS별로 차이가 있으므로 특정 제품의 규칙을 구분해야 합니다."
  }
];
