import type { StudyQuestion } from "../types";

export const SQLD_MODELING_QUESTIONS: StudyQuestion[] = [
  {
    id: "sqld-modeling-001",
    kind: "choice",
    topic: "데이터 모델링",
    difficulty: "기초",
    tags: ["sqld", "modeling", "frequent"],
    prompt: "업무에서 관리할 데이터의 전체 범위와 주요 관계를 가장 추상적으로 표현하는 모델은 무엇입니까?",
    choices: ["① 개념적 데이터 모델", "② 논리적 데이터 모델", "③ 물리적 데이터 모델", "④ 실행 데이터 모델"],
    answer: "① 개념적 데이터 모델",
    hint: "특정 DBMS나 컬럼 자료형을 정하기 전 단계입니다.",
    explanation: "개념적 모델은 전사 관점에서 핵심 엔터티와 관계를 높은 수준으로 표현합니다.",
    confusion: "논리적 모델은 속성·식별자·정규화를 구체화하고, 물리적 모델은 테이블·컬럼·인덱스 같은 구현 요소를 정합니다."
  },
  {
    id: "sqld-modeling-002",
    kind: "choice",
    topic: "데이터 모델링",
    difficulty: "기초",
    tags: ["sqld", "modeling"],
    prompt: "논리적 데이터 모델링 단계에서 수행하는 작업으로 가장 적절한 것은 무엇입니까?",
    choices: ["① 저장 장치의 블록 크기를 결정한다", "② 엔터티의 속성과 식별자를 정의하고 정규화한다", "③ 특정 DBMS의 인덱스 옵션을 지정한다", "④ 운영 서버의 메모리를 증설한다"],
    answer: "② 엔터티의 속성과 식별자를 정의하고 정규화한다",
    hint: "업무 구조는 구체화하지만 물리적인 저장 방식에는 독립적인 단계입니다.",
    explanation: "논리적 모델링에서는 엔터티, 속성, 관계, 식별자를 정의하고 데이터 중복을 줄이기 위한 정규화를 수행합니다.",
    confusion: "인덱스와 저장 공간 같은 DBMS 종속 요소는 물리적 모델링에서 다룹니다."
  },
  {
    id: "sqld-modeling-003",
    kind: "choice",
    topic: "엔터티",
    difficulty: "기초",
    tags: ["sqld", "modeling", "entity", "frequent"],
    prompt: "데이터 모델의 엔터티가 성립하기 위한 조건으로 옳지 않은 것은 무엇입니까?",
    choices: ["① 업무에서 관리할 필요가 있다", "② 식별할 수 있는 인스턴스가 존재한다", "③ 반드시 다른 엔터티와 두 개 이상의 관계를 맺어야 한다", "④ 업무 프로세스에서 이용된다"],
    answer: "③ 반드시 다른 엔터티와 두 개 이상의 관계를 맺어야 한다",
    hint: "관계 수를 고정하는 조건은 없습니다.",
    explanation: "엔터티는 업무상 관리 대상이고 식별 가능한 인스턴스와 속성을 가지며 업무에서 사용되어야 하지만 관계 개수가 반드시 두 개 이상일 필요는 없습니다.",
    confusion: "관계가 전혀 없는 엔터티는 누락된 관계가 없는지 검토해야 하지만, 관계 수 자체가 엔터티의 절대 성립 조건은 아닙니다."
  },
  {
    id: "sqld-modeling-004",
    kind: "choice",
    topic: "엔터티",
    difficulty: "실전",
    tags: ["sqld", "modeling", "entity"],
    prompt: "고객과 상품 사이의 주문 내역처럼 업무가 진행되면서 발생하고 지속적으로 데이터가 쌓이는 엔터티 유형은 무엇입니까?",
    choices: ["① 기본 엔터티", "② 중심 엔터티", "③ 행위 엔터티", "④ 외부 엔터티"],
    answer: "③ 행위 엔터티",
    hint: "두 개 이상의 주체가 수행한 업무의 결과를 기록합니다.",
    explanation: "행위 엔터티는 주문, 계약, 접수처럼 업무 활동의 결과로 생성되며 데이터 발생량이 많아지는 특성이 있습니다.",
    confusion: "기본 엔터티는 독립적으로 생성되고, 중심 엔터티는 기본 엔터티로부터 파생되어 주요 업무의 중심 역할을 합니다."
  },
  {
    id: "sqld-modeling-005",
    kind: "choice",
    topic: "속성",
    difficulty: "기초",
    tags: ["sqld", "modeling", "attribute", "frequent"],
    prompt: "한 엔터티의 각 인스턴스를 설명하며 더 이상 의미 있게 분리하기 어려운 최소 데이터 단위는 무엇입니까?",
    choices: ["① 관계", "② 속성", "③ 식별자", "④ 카디널리티"],
    answer: "② 속성",
    hint: "테이블로 구현하면 보통 컬럼에 대응합니다.",
    explanation: "속성은 엔터티 인스턴스의 성질을 나타내는 최소 데이터 단위이며 하나의 속성은 같은 종류의 값을 가집니다.",
    confusion: "식별자도 하나 이상의 속성으로 구성되지만, 모든 속성이 식별자인 것은 아닙니다."
  },
  {
    id: "sqld-modeling-006",
    kind: "choice",
    topic: "속성",
    difficulty: "기초",
    tags: ["sqld", "modeling", "attribute"],
    prompt: "속성이 가질 수 있는 값의 범위와 형식, 제약 조건을 정의한 것은 무엇입니까?",
    choices: ["① 도메인", "② 인스턴스", "③ 관계명", "④ 엔터티명"],
    answer: "① 도메인",
    hint: "예를 들어 점수는 0부터 100까지의 정수로 제한할 수 있습니다.",
    explanation: "도메인은 속성에 허용되는 데이터 타입, 크기, 값의 범위와 제약을 정의합니다.",
    confusion: "같은 도메인을 사용하는 속성이라도 업무 의미가 다르면 서로 다른 속성일 수 있습니다."
  },
  {
    id: "sqld-modeling-007",
    kind: "choice",
    topic: "속성",
    difficulty: "실전",
    tags: ["sqld", "modeling", "attribute"],
    prompt: "주문수량과 단가를 이용해 계산한 주문금액은 속성 분류상 무엇에 해당합니까?",
    choices: ["① 기본 속성", "② 설계 속성", "③ 파생 속성", "④ 식별 속성"],
    answer: "③ 파생 속성",
    hint: "다른 속성의 값으로 계산할 수 있습니다.",
    explanation: "파생 속성은 다른 속성으로부터 계산되거나 변환되어 만들어지는 값입니다.",
    confusion: "조회 성능 때문에 파생 값을 실제 저장할 수 있지만 원본 변경 시 함께 갱신해야 하므로 정합성 관리가 필요합니다."
  },
  {
    id: "sqld-modeling-008",
    kind: "choice",
    topic: "관계",
    difficulty: "기초",
    tags: ["sqld", "modeling", "relationship", "frequent"],
    prompt: "한 부서에 여러 사원이 소속될 수 있고 각 사원은 하나의 부서에만 소속되는 관계는 무엇입니까?",
    choices: ["① 1:1", "② 1:N", "③ N:M", "④ 재귀 관계"],
    answer: "② 1:N",
    hint: "부서 하나를 기준으로 사원이 여러 명입니다.",
    explanation: "부서 한 인스턴스가 여러 사원 인스턴스와 관계를 맺고 사원은 하나의 부서와 관계를 맺으므로 1:N입니다.",
    confusion: "관계를 읽는 방향에 따라 N:1로 표현할 수도 있지만 같은 관계를 의미합니다."
  },
  {
    id: "sqld-modeling-009",
    kind: "choice",
    topic: "관계",
    difficulty: "실전",
    tags: ["sqld", "modeling", "relationship"],
    prompt: "사원은 부서에 소속되지 않은 상태로도 먼저 등록할 수 있습니다. 사원에서 부서로 향하는 관계의 참여 조건은 무엇입니까?",
    choices: ["① 필수 참여", "② 선택 참여", "③ 배타 참여", "④ 식별 참여"],
    answer: "② 선택 참여",
    hint: "부서가 없어도 사원 인스턴스가 존재할 수 있습니다.",
    explanation: "관계에 참여하지 않아도 인스턴스가 존재할 수 있으므로 최소 카디널리티가 0인 선택 참여입니다.",
    confusion: "최대 카디널리티가 1인 것과 최소 카디널리티가 0인 것은 서로 다른 제약입니다."
  },
  {
    id: "sqld-modeling-010",
    kind: "choice",
    topic: "관계",
    difficulty: "실전",
    tags: ["sqld", "modeling", "relationship"],
    prompt: "학생과 과목 사이의 N:M 수강 관계를 관계형 테이블로 구현하는 가장 일반적인 방법은 무엇입니까?",
    choices: ["① 학생 테이블에 과목 컬럼을 여러 개 만든다", "② 과목 테이블에 학생 목록을 문자열로 저장한다", "③ 학생과 과목의 식별자를 가진 수강 엔터티를 만든다", "④ 두 테이블을 하나로 합친다"],
    answer: "③ 학생과 과목의 식별자를 가진 수강 엔터티를 만든다",
    hint: "관계 자체를 하나의 엔터티로 바꿉니다.",
    explanation: "N:M 관계는 교차 엔터티인 수강을 만들어 두 개의 1:N 관계로 해소합니다.",
    confusion: "반복 컬럼이나 구분자로 합친 문자열은 값의 원자성과 참조 무결성을 해칩니다."
  },
  {
    id: "sqld-modeling-011",
    kind: "choice",
    topic: "식별자",
    difficulty: "기초",
    tags: ["sqld", "modeling", "identifier", "frequent"],
    prompt: "주식별자가 갖춰야 할 특성으로 옳지 않은 것은 무엇입니까?",
    choices: ["① 각 인스턴스를 유일하게 구분한다", "② 꼭 필요한 최소 속성으로 구성한다", "③ 업무가 진행될 때마다 자주 변경된다", "④ 모든 인스턴스가 식별자 값을 가져야 한다"],
    answer: "③ 업무가 진행될 때마다 자주 변경된다",
    hint: "식별자 값은 안정적이어야 합니다.",
    explanation: "주식별자는 유일성, 최소성, 불변성, 존재성을 만족해야 하므로 자주 변경되는 값은 부적합합니다.",
    confusion: "후보식별자는 유일성과 최소성을 만족하며 그중 대표로 선택된 식별자가 주식별자입니다."
  },
  {
    id: "sqld-modeling-012",
    kind: "choice",
    topic: "식별자",
    difficulty: "실전",
    tags: ["sqld", "modeling", "identifier"],
    prompt: "업무적으로 의미 있는 회원 이메일 대신 시스템이 생성한 일련번호를 회원의 주식별자로 사용했습니다. 이 일련번호의 분류는 무엇입니까?",
    choices: ["① 본질식별자", "② 인조식별자", "③ 외부식별자", "④ 보조식별자"],
    answer: "② 인조식별자",
    hint: "업무에서 원래 존재한 값이 아니라 설계를 위해 새로 만들었습니다.",
    explanation: "인조식별자는 여러 본질 속성을 대체하거나 식별을 단순화하기 위해 인위적으로 만든 식별자입니다.",
    confusion: "인조식별자를 사용하더라도 이메일의 업무상 중복을 막아야 한다면 별도의 UNIQUE 제약이 필요합니다."
  },
  {
    id: "sqld-modeling-013",
    kind: "choice",
    topic: "식별자",
    difficulty: "심화",
    tags: ["sqld", "modeling", "identifier"],
    prompt: "부모 엔터티의 주식별자가 자식 엔터티의 주식별자 구성에 포함되는 관계는 무엇입니까?",
    choices: ["① 비식별 관계", "② 식별 관계", "③ 선택 관계", "④ 배타 관계"],
    answer: "② 식별 관계",
    hint: "자식의 존재와 식별이 부모에게 의존합니다.",
    explanation: "식별 관계에서는 부모 식별자가 자식의 주식별자로 전이되어 자식 식별자의 일부가 됩니다.",
    confusion: "비식별 관계에서도 부모 식별자는 외래키로 전이되지만 자식의 주식별자에는 포함되지 않습니다."
  },
  {
    id: "sqld-modeling-014",
    kind: "choice",
    topic: "정규화",
    difficulty: "기초",
    tags: ["sqld", "modeling", "normalization", "frequent"],
    prompt: "한 컬럼에 여러 전화번호를 쉼표로 연결해 저장했습니다. 가장 먼저 위반한 정규형은 무엇입니까?",
    choices: ["① 제1정규형", "② 제2정규형", "③ 제3정규형", "④ BCNF"],
    answer: "① 제1정규형",
    hint: "각 속성 값은 더 나눌 필요가 없는 하나의 값이어야 합니다.",
    explanation: "제1정규형은 모든 속성이 원자값을 가져야 하므로 여러 값을 한 컬럼에 저장하면 위반합니다.",
    confusion: "반복되는 전화번호는 별도 행이나 자식 엔터티로 분리하는 것이 일반적입니다."
  },
  {
    id: "sqld-modeling-015",
    kind: "choice",
    topic: "정규화",
    difficulty: "실전",
    tags: ["sqld", "modeling", "normalization", "frequent"],
    prompt: "수강(학생번호, 과목번호, 학생명, 성적)에서 주식별자가 (학생번호, 과목번호)이고 학생명은 학생번호에만 종속됩니다. 제거해야 할 종속성은 무엇입니까?",
    choices: ["① 이행 함수 종속", "② 부분 함수 종속", "③ 다치 종속", "④ 조인 종속"],
    answer: "② 부분 함수 종속",
    hint: "복합 식별자의 일부만으로 일반 속성이 결정됩니다.",
    explanation: "학생명이 복합 주식별자 전체가 아닌 학생번호 일부에만 종속되므로 제2정규형을 위해 분리해야 합니다.",
    confusion: "이행 함수 종속은 주식별자가 아닌 일반 속성이 다른 일반 속성을 결정하는 경우입니다."
  },
  {
    id: "sqld-modeling-016",
    kind: "choice",
    topic: "정규화",
    difficulty: "실전",
    tags: ["sqld", "modeling", "normalization", "frequent"],
    prompt: "사원번호가 부서번호를 결정하고 부서번호가 부서명을 결정합니다. 사원번호가 주식별자일 때 제3정규형을 위해 필요한 조치는 무엇입니까?",
    choices: ["① 부서번호와 부서명을 제거한다", "② 부서번호와 부서명을 별도 부서 엔터티로 분리한다", "③ 사원번호를 두 개 컬럼으로 나눈다", "④ 모든 컬럼을 하나의 문자열로 합친다"],
    answer: "② 부서번호와 부서명을 별도 부서 엔터티로 분리한다",
    hint: "일반 속성이 또 다른 일반 속성을 결정합니다.",
    explanation: "사원번호 → 부서번호 → 부서명의 이행 함수 종속을 제거하기 위해 부서번호와 부서명을 부서 엔터티로 분리합니다.",
    confusion: "제2정규형은 복합 식별자의 부분 종속을, 제3정규형은 일반 속성 사이의 이행 종속을 제거합니다."
  },
  {
    id: "sqld-modeling-017",
    kind: "choice",
    topic: "정규화",
    difficulty: "심화",
    tags: ["sqld", "modeling", "normalization"],
    prompt: "BCNF를 만족하는 릴레이션의 조건으로 가장 적절한 것은 무엇입니까?",
    choices: ["① 모든 속성이 문자형이다", "② 모든 결정자가 후보키이다", "③ 외래키가 존재하지 않는다", "④ NULL을 허용하지 않는다"],
    answer: "② 모든 결정자가 후보키이다",
    hint: "어떤 속성 집합이 다른 속성을 결정할 때 그 집합의 자격을 봅니다.",
    explanation: "BCNF는 릴레이션의 모든 결정자가 후보키여야 한다는 조건을 요구합니다.",
    confusion: "BCNF는 제3정규형보다 강한 조건이며 NULL 허용 여부와는 직접 관련이 없습니다."
  },
  {
    id: "sqld-modeling-018",
    kind: "choice",
    topic: "정규화",
    difficulty: "실전",
    tags: ["sqld", "modeling", "normalization"],
    prompt: "정규화를 수행했을 때 일반적으로 기대할 수 있는 효과로 가장 적절한 것은 무엇입니까?",
    choices: ["① 데이터 중복과 갱신 이상을 줄인다", "② 모든 조회에서 조인이 사라진다", "③ 테이블 수가 항상 감소한다", "④ 인덱스가 자동으로 생성된다"],
    answer: "① 데이터 중복과 갱신 이상을 줄인다",
    hint: "삽입·수정·삭제 때 생기는 불일치를 줄이는 과정입니다.",
    explanation: "정규화는 함수 종속을 바탕으로 데이터를 분리하여 중복과 삽입·갱신·삭제 이상을 줄입니다.",
    confusion: "정규화하면 테이블과 조인이 늘 수 있으며, 성능상 필요할 때 검토를 거쳐 반정규화를 적용할 수 있습니다."
  },
  {
    id: "sqld-modeling-019",
    kind: "choice",
    topic: "NULL 속성",
    difficulty: "기초",
    tags: ["sqld", "modeling", "null", "frequent"],
    prompt: "관계형 데이터 모델에서 NULL에 대한 설명으로 옳은 것은 무엇입니까?",
    choices: ["① 숫자 0과 같다", "② 길이가 0인 문자열과 항상 같다", "③ 값이 알려지지 않았거나 적용할 수 없음을 나타낸다", "④ 모든 비교에서 TRUE를 반환한다"],
    answer: "③ 값이 알려지지 않았거나 적용할 수 없음을 나타낸다",
    hint: "NULL은 특정 값이 아니라 값의 부재 상태입니다.",
    explanation: "NULL은 아직 알 수 없거나 해당되지 않는 값의 부재를 나타내며 0이나 빈 문자열과 다릅니다.",
    confusion: "NULL과의 일반 비교는 UNKNOWN이 되므로 SQL에서는 IS NULL 또는 IS NOT NULL을 사용합니다."
  },
  {
    id: "sqld-modeling-020",
    kind: "choice",
    topic: "데이터 모델과 SQL",
    difficulty: "심화",
    tags: ["sqld", "modeling", "transaction"],
    prompt: "데이터 모델을 업무 트랜잭션 관점에서 검토하는 주된 이유로 가장 적절한 것은 무엇입니까?",
    choices: ["① 화면 색상을 결정하기 위해", "② 트랜잭션이 사용하는 엔터티와 관계의 누락을 확인하기 위해", "③ DBMS 라이선스를 선택하기 위해", "④ 네트워크 대역폭을 계산하기 위해"],
    answer: "② 트랜잭션이 사용하는 엔터티와 관계의 누락을 확인하기 위해",
    hint: "업무가 실제로 데이터를 생성·조회·수정·삭제하는 경로를 모델과 대조합니다.",
    explanation: "트랜잭션과 데이터 모델을 함께 검토하면 CRUD 과정에서 필요한 엔터티, 속성, 관계가 빠졌는지 확인할 수 있습니다.",
    confusion: "데이터 모델은 정적인 구조만 그리는 작업이 아니라 실제 업무 처리와 일치하는지 검증해야 합니다."
  }
];
