import type { StudyQuestion } from "../types";

export const SQLD_EXAM_STYLE_SQL_QUESTIONS: StudyQuestion[] = [
  {
    id: "sqld-exam-sql-001",
    kind: "sql",
    topic: "집계 함수",
    difficulty: "실전",
    tags: ["sqld", "sql", "sql-basic", "exam-style", "aggregate", "null", "calculation", "frequent"],
    prompt: "재고 테이블의 가용수량 값이 15, 5, NULL일 때 다음 SQL의 결과로 옳은 것은 무엇입니까?\n```sql\nSELECT SUM(가용수량), COUNT(가용수량), COUNT(*) FROM 재고;\n```",
    choices: ["① 20, 2, 3", "② 20, 3, 3", "③ NULL, 2, 3", "④ 20, 2, 2"],
    answer: "① 20, 2, 3",
    hint: "SUM과 COUNT(컬럼)은 NULL을 제외하지만 COUNT(*)는 행을 셉니다.",
    explanation: "SUM은 15와 5를 더해 20이고 COUNT(가용수량)는 NULL이 아닌 2행, COUNT(*)는 전체 3행을 반환합니다.",
    confusion: "집계 함수는 일반적으로 NULL을 제외하지만 COUNT(*)는 특정 컬럼 값이 아니라 결과 행 자체를 셉니다."
  },
  {
    id: "sqld-exam-sql-002",
    kind: "sql",
    topic: "NULL 함수",
    difficulty: "실전",
    tags: ["sqld", "sql", "sql-basic", "exam-style", "null", "function", "calculation"],
    prompt: "price가 100이고 discount가 NULL일 때 Oracle에서 다음 SQL의 결과로 옳은 것은 무엇입니까?\n```sql\nSELECT price - discount, price - NVL(discount, 0) FROM 상품;\n```",
    choices: ["① NULL, 100", "② 100, 100", "③ 0, 100", "④ NULL, NULL"],
    answer: "① NULL, 100",
    hint: "NULL과의 산술 연산 결과와 NVL 치환 후 결과를 나누어 보세요.",
    explanation: "100-NULL은 NULL이며 NVL(discount, 0)은 NULL을 0으로 바꾸므로 두 번째 결과는 100입니다.",
    confusion: "NULL은 숫자 0이나 빈 문자열과 같은 값이 아니므로 산술식에 포함되면 결과가 NULL이 됩니다."
  },
  {
    id: "sqld-exam-sql-003",
    kind: "sql",
    topic: "WHERE",
    difficulty: "실전",
    tags: ["sqld", "sql", "sql-basic", "exam-style", "where", "operator", "frequent"],
    prompt: "다음 WHERE 조건과 논리적으로 같은 것은 무엇입니까?\n```sql\nWHERE grade = 'A' OR grade = 'B' AND score >= 80\n```",
    choices: ["① (grade = 'A' OR grade = 'B') AND score >= 80", "② grade = 'A' OR (grade = 'B' AND score >= 80)", "③ (grade = 'A' AND grade = 'B') OR score >= 80", "④ grade IN ('A', 'B') OR score >= 80"],
    answer: "② grade = 'A' OR (grade = 'B' AND score >= 80)",
    hint: "AND와 OR 중 먼저 평가되는 연산자를 찾으세요.",
    explanation: "AND의 우선순위가 OR보다 높으므로 grade='B'와 score 조건이 먼저 결합됩니다.",
    confusion: "업무 조건이 복잡할 때는 연산자 우선순위에 의존하지 말고 괄호로 의도를 분명히 하는 편이 안전합니다."
  },
  {
    id: "sqld-exam-sql-004",
    kind: "sql",
    topic: "SELECT",
    difficulty: "실전",
    tags: ["sqld", "sql", "sql-basic", "exam-style", "select", "alias", "oracle"],
    prompt: "employee(name, dept_id, salary, bonus) 테이블에 대해 Oracle에서 실행 시 오류가 발생하는 SQL은 무엇입니까?",
    choices: ["① SELECT name, salary + NVL(bonus, 0) AS total_pay FROM employee ORDER BY total_pay", "② SELECT name, salary FROM employee ORDER BY 2", "③ SELECT dept_id, SUM(salary) FROM employee GROUP BY dept_id", "④ SELECT name, salary + NVL(bonus, 0) AS total_pay FROM employee WHERE total_pay >= 5000"],
    answer: "④ SELECT name, salary + NVL(bonus, 0) AS total_pay FROM employee WHERE total_pay >= 5000",
    hint: "SELECT 별칭을 사용할 수 있는 절과 논리 처리 순서를 생각하세요.",
    explanation: "WHERE는 SELECT보다 먼저 처리되므로 같은 SELECT 목록에서 만든 total_pay 별칭을 참조할 수 없습니다.",
    confusion: "ORDER BY는 SELECT 결과가 만들어진 뒤 처리되므로 SELECT 별칭이나 컬럼 위치를 사용할 수 있습니다."
  },
  {
    id: "sqld-exam-sql-005",
    kind: "sql",
    topic: "CASE",
    difficulty: "실전",
    tags: ["sqld", "sql", "sql-basic", "exam-style", "case", "null"],
    prompt: "score 값이 각각 90, 70, NULL인 세 행에 다음 표현식을 적용한 결과로 옳은 것은 무엇입니까?\n```sql\nCASE WHEN score >= 80 THEN 'A'\n     WHEN score >= 60 THEN 'B'\n     ELSE 'C' END\n```",
    choices: ["① A, B, C", "② A, B, NULL", "③ A, A, C", "④ B, B, C"],
    answer: "① A, B, C",
    hint: "NULL과의 비교는 TRUE가 아니므로 ELSE까지 내려갑니다.",
    explanation: "90은 첫 조건, 70은 두 번째 조건을 만족하고 NULL 비교는 모두 UNKNOWN이므로 ELSE의 C가 반환됩니다.",
    confusion: "CASE는 위에서부터 처음 TRUE가 된 분기를 선택하며 조건이 모두 FALSE 또는 UNKNOWN이면 ELSE를 사용합니다."
  },
  {
    id: "sqld-exam-sql-006",
    kind: "sql",
    topic: "NULL 함수",
    difficulty: "실전",
    tags: ["sqld", "sql", "sql-basic", "exam-style", "null", "function", "oracle"],
    prompt: "Oracle에서 다음 식의 결과로 옳은 것은 무엇입니까?\n```sql\nNVL(NULL, 0) + COALESCE(NULL, 5, 9)\n```",
    choices: ["① 0", "② 5", "③ 9", "④ NULL"],
    answer: "② 5",
    hint: "각 함수가 선택하는 NULL이 아닌 값을 먼저 구하세요.",
    explanation: "NVL(NULL,0)은 0이고 COALESCE(NULL,5,9)는 첫 번째 NULL이 아닌 값 5이므로 합은 5입니다.",
    confusion: "COALESCE는 인수를 왼쪽부터 평가해 처음 만난 NULL이 아닌 값을 반환합니다."
  },
  {
    id: "sqld-exam-sql-007",
    kind: "sql",
    topic: "NULL 함수",
    difficulty: "실전",
    tags: ["sqld", "sql", "sql-basic", "exam-style", "null", "function"],
    prompt: "다음 두 표현식의 결과를 순서대로 나열한 것은 무엇입니까?\n```sql\nNULLIF(10, 10), COALESCE(NULL, 7, 9)\n```",
    choices: ["① 10, 7", "② NULL, 7", "③ NULL, 9", "④ 0, 7"],
    answer: "② NULL, 7",
    hint: "NULLIF는 두 값이 같을 때 NULL을 반환합니다.",
    explanation: "NULLIF(10,10)은 두 값이 같으므로 NULL이고 COALESCE는 첫 번째 NULL이 아닌 7을 반환합니다.",
    confusion: "NULLIF(a,b)는 a와 b가 다르면 a를 반환하며 두 값을 뺀 결과를 반환하는 함수가 아닙니다."
  },
  {
    id: "sqld-exam-sql-008",
    kind: "sql",
    topic: "문자 함수",
    difficulty: "실전",
    tags: ["sqld", "sql", "sql-basic", "exam-style", "function", "string", "oracle"],
    prompt: "Oracle에서 다음 표현식의 결과로 옳은 것은 무엇입니까?\n```sql\nSUBSTR('SQLD2026', 5, 4)\n```",
    choices: ["① SQLD", "② 2026", "③ D202", "④ 026"],
    answer: "② 2026",
    hint: "Oracle 문자열 위치는 1부터 시작합니다.",
    explanation: "다섯 번째 문자 2부터 네 글자를 추출하므로 결과는 2026입니다.",
    confusion: "SUBSTR의 두 번째 인수는 시작 위치이고 세 번째 인수는 추출할 길이입니다."
  },
  {
    id: "sqld-exam-sql-009",
    kind: "sql",
    topic: "날짜 함수",
    difficulty: "실전",
    tags: ["sqld", "sql", "sql-basic", "exam-style", "function", "date", "oracle"],
    prompt: "Oracle에서 다음 표현식의 결과 날짜로 옳은 것은 무엇입니까?\n```sql\nTO_DATE('2026-03-07', 'YYYY-MM-DD') + 1\n```",
    choices: ["① 2026-03-07 00:00:01", "② 2026-03-08", "③ 2026-04-07", "④ 오류"],
    answer: "② 2026-03-08",
    hint: "Oracle DATE에 숫자 1을 더할 때의 단위를 생각하세요.",
    explanation: "Oracle에서 DATE 값에 1을 더하면 하루가 더해지므로 2026년 3월 8일이 됩니다.",
    confusion: "시간을 더하려면 하루를 기준으로 분수 값을 사용하며 1/24는 한 시간입니다."
  },
  {
    id: "sqld-exam-sql-010",
    kind: "sql",
    topic: "GROUP BY",
    difficulty: "실전",
    tags: ["sqld", "sql", "sql-basic", "exam-style", "group-by", "having", "aggregate", "frequent"],
    prompt: "부서별 평균 급여가 4000 이상인 부서의 부서번호와 평균 급여를 조회하는 SQL로 옳은 것은 무엇입니까?",
    choices: ["① SELECT dept_id, AVG(salary) FROM employee WHERE AVG(salary) >= 4000 GROUP BY dept_id", "② SELECT dept_id, AVG(salary) FROM employee GROUP BY dept_id HAVING AVG(salary) >= 4000", "③ SELECT dept_id, AVG(salary) FROM employee HAVING salary >= 4000", "④ SELECT AVG(salary) FROM employee GROUP BY salary >= 4000"],
    answer: "② SELECT dept_id, AVG(salary) FROM employee GROUP BY dept_id HAVING AVG(salary) >= 4000",
    hint: "개별 행 조건과 그룹 집계 결과 조건을 구분하세요.",
    explanation: "부서번호로 그룹화한 뒤 AVG 결과에 HAVING 조건을 적용해야 합니다.",
    confusion: "WHERE는 그룹화 전 개별 행을 거르므로 집계 함수를 직접 조건으로 사용할 수 없습니다."
  },
  {
    id: "sqld-exam-sql-011",
    kind: "sql",
    topic: "JOIN",
    difficulty: "심화",
    tags: ["sqld", "sql", "sql-basic", "exam-style", "join", "calculation", "frequent"],
    prompt: "A 테이블의 id가 1, 1, 2이고 B 테이블의 id가 1, 1, 3일 때 다음 SQL의 결과 행 수는 몇 개입니까?\n```sql\nSELECT * FROM A JOIN B ON A.id = B.id;\n```",
    choices: ["① 2행", "② 3행", "③ 4행", "④ 6행"],
    answer: "③ 4행",
    hint: "id=1인 각 행이 상대 테이블의 일치 행 몇 개와 결합되는지 계산하세요.",
    explanation: "A의 id=1 두 행 각각이 B의 id=1 두 행과 결합되어 2×2인 4행이 생성됩니다.",
    confusion: "조인 키가 유일하지 않으면 일치하는 행의 조합 수만큼 결과가 늘어납니다."
  },
  {
    id: "sqld-exam-sql-012",
    kind: "sql",
    topic: "OUTER JOIN",
    difficulty: "심화",
    tags: ["sqld", "sql", "sql-basic", "exam-style", "join", "outer-join", "null"],
    prompt: "A의 모든 행을 유지하면서 active='Y'인 B만 연결하려고 한다. 요구사항을 만족하는 SQL은 무엇입니까?",
    choices: ["① SELECT * FROM A LEFT JOIN B ON A.id=B.id WHERE B.active='Y'", "② SELECT * FROM A LEFT JOIN B ON A.id=B.id AND B.active='Y'", "③ SELECT * FROM A JOIN B ON A.id=B.id AND B.active='Y'", "④ SELECT * FROM A RIGHT JOIN B ON A.id=B.id WHERE A.id IS NOT NULL"],
    answer: "② SELECT * FROM A LEFT JOIN B ON A.id=B.id AND B.active='Y'",
    hint: "B에 대한 조건을 조인 조건에 둘 때와 WHERE에 둘 때 보존되는 행을 비교하세요.",
    explanation: "B.active 조건을 ON에 두면 일치하는 활성 B만 연결하면서 B가 없는 A 행도 NULL 확장되어 남습니다.",
    confusion: "B 조건을 WHERE에 두면 NULL 확장된 행이 제거되어 LEFT JOIN이 사실상 INNER JOIN처럼 동작할 수 있습니다."
  },
  {
    id: "sqld-exam-sql-013",
    kind: "sql",
    topic: "표준 조인",
    difficulty: "실전",
    tags: ["sqld", "sql", "sql-basic", "exam-style", "join", "natural-join"],
    prompt: "NATURAL JOIN에 대한 설명으로 옳지 않은 것은 무엇입니까?",
    choices: ["① 양쪽 테이블의 같은 이름 컬럼을 조인 조건으로 사용한다", "② 동일 이름 컬럼이 추가되면 조인 결과가 달라질 수 있다", "③ 조인 컬럼을 테이블 별칭으로 한정해 ON 절에 다시 작성해야 한다", "④ 같은 이름 컬럼이 여러 개면 모두 조인 조건에 참여한다"],
    answer: "③ 조인 컬럼을 테이블 별칭으로 한정해 ON 절에 다시 작성해야 한다",
    hint: "NATURAL JOIN은 조인 조건을 자동으로 구성합니다.",
    explanation: "NATURAL JOIN은 동일 이름 컬럼을 자동 조인 조건으로 사용하며 별도의 ON 절을 함께 작성하지 않습니다.",
    confusion: "예상치 못한 같은 이름 컬럼까지 조건에 포함될 수 있으므로 운영 SQL에서는 명시적 ON 조건이 더 안전한 경우가 많습니다."
  },
  {
    id: "sqld-exam-sql-014",
    kind: "sql",
    topic: "CROSS JOIN",
    difficulty: "실전",
    tags: ["sqld", "sql", "sql-basic", "exam-style", "join", "cross-join", "calculation"],
    prompt: "A가 5행이고 B가 3행이며 조인 조건이 없을 때 `SELECT COUNT(*) FROM A CROSS JOIN B`의 결과는 무엇입니까?",
    choices: ["① 3", "② 5", "③ 8", "④ 15"],
    answer: "④ 15",
    hint: "각 A 행이 모든 B 행과 한 번씩 결합됩니다.",
    explanation: "CROSS JOIN은 두 집합의 카티션 곱이므로 결과 행 수는 5×3인 15입니다.",
    confusion: "조인 조건이 빠진 일반 조인도 의도하지 않은 카티션 곱을 만들 수 있습니다."
  },
  {
    id: "sqld-exam-sql-015",
    kind: "sql",
    topic: "서브쿼리",
    difficulty: "실전",
    tags: ["sqld", "sql", "sql-advanced", "exam-style", "subquery", "scalar-subquery", "frequent"],
    prompt: "다음 SQL의 스칼라 서브쿼리가 두 행을 반환할 때 발생하는 결과로 옳은 것은 무엇입니까?\n```sql\nSELECT name, (SELECT dept_name FROM department d WHERE d.location='SEOUL')\nFROM employee;\n```",
    choices: ["① 첫 번째 부서명만 자동 선택한다", "② 부서명을 쉼표로 합친다", "③ 단일 행 서브쿼리가 여러 행을 반환했다는 오류가 발생한다", "④ employee 행이 두 배로 증가한다"],
    answer: "③ 단일 행 서브쿼리가 여러 행을 반환했다는 오류가 발생한다",
    hint: "SELECT 목록의 한 값 자리에 올 수 있는 행 수를 생각하세요.",
    explanation: "스칼라 서브쿼리는 한 컬럼의 최대 한 행만 반환해야 하므로 두 행 이상이면 오류가 발생합니다.",
    confusion: "스칼라 서브쿼리가 0행을 반환하면 일반적으로 NULL로 취급됩니다."
  },
  {
    id: "sqld-exam-sql-016",
    kind: "sql",
    topic: "서브쿼리",
    difficulty: "심화",
    tags: ["sqld", "sql", "sql-advanced", "exam-style", "subquery", "correlated", "exists"],
    prompt: "한 번이라도 주문한 고객만 조회하는 SQL로 가장 적절한 것은 무엇입니까?",
    choices: ["① SELECT * FROM customer c WHERE EXISTS (SELECT 1 FROM orders o WHERE o.customer_id=c.customer_id)", "② SELECT * FROM customer c WHERE NOT EXISTS (SELECT 1 FROM orders o WHERE o.customer_id=c.customer_id)", "③ SELECT * FROM customer CROSS JOIN orders", "④ SELECT DISTINCT * FROM customer WHERE customer_id IS NULL"],
    answer: "① SELECT * FROM customer c WHERE EXISTS (SELECT 1 FROM orders o WHERE o.customer_id=c.customer_id)",
    hint: "현재 고객과 일치하는 주문 행의 존재 여부를 검사하세요.",
    explanation: "상관 EXISTS는 각 고객과 customer_id가 같은 주문이 하나 이상 있을 때 TRUE가 됩니다.",
    confusion: "EXISTS에서는 SELECT 목록의 값보다 조건을 만족하는 행이 존재하는지가 중요합니다."
  },
  {
    id: "sqld-exam-sql-017",
    kind: "sql",
    topic: "서브쿼리",
    difficulty: "심화",
    tags: ["sqld", "sql", "sql-advanced", "exam-style", "subquery", "not-in", "null", "frequent"],
    prompt: "employee_id가 NULL이 아닌 사원 테이블에서 다음 조건의 서브쿼리 결과가 (10, 20, NULL)일 때 일반적으로 조회되는 행에 대한 설명으로 옳은 것은 무엇입니까?\n```sql\nWHERE employee_id NOT IN (SELECT manager_id FROM employee)\n```",
    choices: ["① 10과 20을 제외한 모든 행", "② employee_id가 NULL인 행만", "③ 조건이 TRUE가 되는 행이 없어 결과가 나오지 않는다", "④ 모든 행"],
    answer: "③ 조건이 TRUE가 되는 행이 없어 결과가 나오지 않는다",
    hint: "NOT IN은 목록의 모든 값과 다름이 TRUE여야 합니다.",
    explanation: "목록의 NULL과 비교한 결과가 UNKNOWN이 포함되어 NOT IN 조건 전체가 TRUE가 되지 않습니다.",
    confusion: "NULL 가능성이 있는 서브쿼리에는 NULL을 제거하거나 상관 NOT EXISTS 사용을 검토해야 합니다."
  },
  {
    id: "sqld-exam-sql-018",
    kind: "sql",
    topic: "다중 행 연산자",
    difficulty: "심화",
    tags: ["sqld", "sql", "sql-advanced", "exam-style", "subquery", "any", "all", "calculation"],
    prompt: "비교 집합이 (20, 40, 60)일 때 조건에 대한 설명으로 옳은 것은 무엇입니까?",
    choices: ["① x > ALL이면 x가 20보다 크면 된다", "② x > ANY이면 x가 60보다 커야 한다", "③ x > ALL이면 x가 60보다 커야 한다", "④ x = ANY이면 세 값 모두와 같아야 한다"],
    answer: "③ x > ALL이면 x가 60보다 커야 한다",
    hint: "ALL은 모든 값, ANY는 하나 이상의 값과 비교합니다.",
    explanation: "> ALL은 집합의 모든 값보다 커야 하므로 최댓값 60보다 커야 합니다.",
    confusion: "> ANY는 하나의 값보다만 크면 되므로 NULL이 없을 때 최솟값 20보다 큰 조건과 대응합니다."
  },
  {
    id: "sqld-exam-sql-019",
    kind: "sql",
    topic: "집합 연산자",
    difficulty: "실전",
    tags: ["sqld", "sql", "sql-advanced", "exam-style", "set-operator", "union", "frequent"],
    prompt: "다음 집합 연산 SQL에 대한 설명으로 옳은 것은 무엇입니까?\n```sql\nSELECT employee_id AS id FROM current_employee\nUNION\nSELECT retired_id FROM retired_employee;\n```",
    choices: ["① 중복을 유지하며 결과 컬럼명은 retired_id이다", "② 중복을 제거하며 결과 컬럼명은 id이다", "③ 두 SELECT의 행 수가 같아야 한다", "④ 두 테이블의 컬럼명이 반드시 같아야 한다"],
    answer: "② 중복을 제거하며 결과 컬럼명은 id이다",
    hint: "UNION의 중복 처리와 최종 컬럼명의 기준을 나누어 생각하세요.",
    explanation: "UNION은 중복 행을 제거하고 결과 컬럼명은 첫 번째 SELECT의 컬럼명 또는 별칭을 따릅니다.",
    confusion: "집합 연산에서는 컬럼 이름보다 컬럼 수와 위치별 데이터 타입의 호환성이 중요합니다."
  },
  {
    id: "sqld-exam-sql-020",
    kind: "sql",
    topic: "집합 연산자",
    difficulty: "실전",
    tags: ["sqld", "sql", "sql-advanced", "exam-style", "set-operator", "minus", "oracle"],
    prompt: "Oracle에서 A에는 1, 2, 3이 있고 B에는 2, 3, 4가 있을 때 다음 SQL의 결과는 무엇입니까?\n```sql\nSELECT id FROM A MINUS SELECT id FROM B;\n```",
    choices: ["① 1", "② 4", "③ 2, 3", "④ 1, 4"],
    answer: "① 1",
    hint: "첫 번째 결과 집합에서 두 번째 결과 집합에 존재하는 값을 제거하세요.",
    explanation: "MINUS는 첫 번째 집합에만 있는 행을 반환하므로 결과는 1입니다.",
    confusion: "집합 연산의 차집합은 방향이 있으므로 두 SELECT의 순서를 바꾸면 결과가 달라집니다."
  },
  {
    id: "sqld-exam-sql-021",
    kind: "sql",
    topic: "그룹 함수",
    difficulty: "실전",
    tags: ["sqld", "sql", "sql-advanced", "exam-style", "rollup", "group-by", "frequent"],
    prompt: "`GROUP BY ROLLUP(region, product)`가 생성하는 집계 수준으로 옳은 것은 무엇입니까?",
    choices: ["① (region, product), (region), 전체 합계", "② (region, product), (product), 전체 합계", "③ (region), (product)만", "④ (region, product)만"],
    answer: "① (region, product), (region), 전체 합계",
    hint: "ROLLUP은 오른쪽 컬럼부터 차례대로 제거합니다.",
    explanation: "ROLLUP(region, product)은 상세 조합, region 소계, 전체 합계를 계층적으로 생성합니다.",
    confusion: "product 단독 소계까지 필요하면 CUBE나 GROUPING SETS를 검토해야 합니다."
  },
  {
    id: "sqld-exam-sql-022",
    kind: "sql",
    topic: "그룹 함수",
    difficulty: "심화",
    tags: ["sqld", "sql", "sql-advanced", "exam-style", "grouping", "rollup", "null"],
    prompt: "ROLLUP 결과에서 `GROUPING(region)`이 1인 행에 대한 설명으로 옳은 것은 무엇입니까?",
    choices: ["① 원본 데이터의 region 값이 우연히 NULL인 일반 행이다", "② ROLLUP이 region을 집계 수준에서 제외해 만든 행이다", "③ region 값이 중복된 상세 행이다", "④ 집계 함수 실행 오류가 발생한 행이다"],
    answer: "② ROLLUP이 region을 집계 수준에서 제외해 만든 행이다",
    hint: "GROUPING은 원본 NULL과 집계 표시 NULL을 구분합니다.",
    explanation: "GROUPING(region)=1은 해당 NULL 표시가 소계나 전체 합계를 만들며 region이 집계에서 제외되어 생성됐음을 뜻합니다.",
    confusion: "COALESCE로 표시값만 바꾸면 원본 NULL인지 집계 NULL인지 구분할 수 없습니다."
  },
  {
    id: "sqld-exam-sql-023",
    kind: "sql",
    topic: "윈도우 함수",
    difficulty: "실전",
    tags: ["sqld", "sql", "sql-advanced", "exam-style", "window", "partition", "calculation", "frequent"],
    prompt: "사원 데이터가 (부서10, 급여100), (부서10, 급여200), (부서20, 급여50)일 때 다음 식이 각 행에 표시하는 값은 무엇입니까?\n```sql\nSUM(salary) OVER (PARTITION BY dept_id)\n```",
    choices: ["① 100, 200, 50", "② 300, 300, 50", "③ 350, 350, 350", "④ 300, 200, 50"],
    answer: "② 300, 300, 50",
    hint: "행을 줄이지 않고 같은 부서의 합계를 각 행에 붙입니다.",
    explanation: "부서10 파티션의 합계 300이 두 행에 표시되고 부서20 파티션의 합계 50이 해당 행에 표시됩니다.",
    confusion: "윈도우 집계는 GROUP BY와 달리 원래 결과 행 수를 유지합니다."
  },
  {
    id: "sqld-exam-sql-024",
    kind: "sql",
    topic: "순위 함수",
    difficulty: "실전",
    tags: ["sqld", "sql", "sql-advanced", "exam-style", "window", "rank", "dense-rank", "calculation"],
    prompt: "점수가 95, 90, 90, 80일 때 내림차순 `RANK()`와 `DENSE_RANK()` 결과를 순서대로 옳게 나열한 것은 무엇입니까?",
    choices: ["① RANK 1,2,2,4 / DENSE_RANK 1,2,2,3", "② RANK 1,2,2,3 / DENSE_RANK 1,2,2,4", "③ 둘 다 1,2,3,4", "④ 둘 다 1,2,2,4"],
    answer: "① RANK 1,2,2,4 / DENSE_RANK 1,2,2,3",
    hint: "동점 다음 순위를 건너뛰는 함수가 무엇인지 구분하세요.",
    explanation: "RANK는 동점 인원만큼 다음 순위를 건너뛰고 DENSE_RANK는 동점 뒤에도 연속 순위를 부여합니다.",
    confusion: "ROW_NUMBER는 동점이어도 각 행에 서로 다른 번호를 부여합니다."
  },
  {
    id: "sqld-exam-sql-025",
    kind: "sql",
    topic: "윈도우 프레임",
    difficulty: "심화",
    tags: ["sqld", "sql", "sql-advanced", "exam-style", "window", "rows", "range"],
    prompt: "윈도우 함수의 `ROWS`와 `RANGE` 프레임에 대한 설명으로 옳은 것은 무엇입니까?",
    choices: ["① ROWS는 물리적 행 위치를, RANGE는 ORDER BY 값의 범위를 기준으로 한다", "② RANGE는 항상 현재 행 한 개만 포함한다", "③ ROWS는 ORDER BY를 사용할 수 없다", "④ 두 프레임은 동점값이 있어도 항상 같은 결과를 낸다"],
    answer: "① ROWS는 물리적 행 위치를, RANGE는 ORDER BY 값의 범위를 기준으로 한다",
    hint: "동일한 정렬값을 가진 행이 프레임에 함께 들어올 수 있는 방식을 생각하세요.",
    explanation: "ROWS는 현재 행의 물리적 위치를 기준으로 하고 RANGE는 정렬값의 논리적 범위를 기준으로 하므로 동점 행에서 결과가 달라질 수 있습니다.",
    confusion: "누적 합계의 동점 처리까지 명확히 하려면 원하는 프레임을 명시하는 것이 좋습니다."
  },
  {
    id: "sqld-exam-sql-026",
    kind: "sql",
    topic: "윈도우 함수",
    difficulty: "실전",
    tags: ["sqld", "sql", "sql-advanced", "exam-style", "window", "lag", "calculation"],
    prompt: "날짜순 매출이 100, 130, 120일 때 첫 행의 기본값을 0으로 지정한 `LAG(amount, 1, 0)` 결과는 무엇입니까?",
    choices: ["① 0, 100, 130", "② 130, 120, 0", "③ 100, 130, 120", "④ NULL, 130, 120"],
    answer: "① 0, 100, 130",
    hint: "각 행에서 바로 이전 행의 값을 가져옵니다.",
    explanation: "첫 행은 이전 값이 없어 기본값 0, 두 번째와 세 번째 행은 각각 이전 매출 100과 130을 반환합니다.",
    confusion: "LEAD는 반대로 현재 행보다 뒤에 있는 행의 값을 참조합니다."
  },
  {
    id: "sqld-exam-sql-027",
    kind: "sql",
    topic: "Top N",
    difficulty: "심화",
    tags: ["sqld", "sql", "sql-advanced", "exam-style", "top-n", "rownum", "oracle", "frequent"],
    prompt: "Oracle에서 급여가 높은 사원 3명을 정확히 조회하는 SQL로 가장 적절한 것은 무엇입니까?",
    choices: ["① SELECT * FROM employee WHERE ROWNUM <= 3 ORDER BY salary DESC", "② SELECT * FROM (SELECT * FROM employee ORDER BY salary DESC) WHERE ROWNUM <= 3", "③ SELECT * FROM employee WHERE ROWNUM = 3 ORDER BY salary DESC", "④ SELECT * FROM employee ORDER BY ROWNUM DESC WHERE salary <= 3"],
    answer: "② SELECT * FROM (SELECT * FROM employee ORDER BY salary DESC) WHERE ROWNUM <= 3",
    hint: "정렬과 ROWNUM 제한 중 어느 작업을 먼저 수행해야 하는지 보세요.",
    explanation: "인라인 뷰에서 먼저 급여 내림차순으로 정렬한 뒤 바깥 쿼리에서 ROWNUM으로 3행을 제한해야 합니다.",
    confusion: "같은 SELECT 블록에서 ROWNUM을 먼저 제한하고 ORDER BY하면 전체 급여 상위 3명이 아닐 수 있습니다."
  },
  {
    id: "sqld-exam-sql-028",
    kind: "sql",
    topic: "계층형 질의",
    difficulty: "심화",
    tags: ["sqld", "sql", "sql-advanced", "exam-style", "hierarchy", "connect-by", "oracle", "frequent"],
    prompt: "조직노드(노드ID, 상위노드ID)에서 최상위 노드부터 하위 노드 방향으로 전개하는 Oracle 계층형 질의의 CONNECT BY 조건으로 옳은 것은 무엇입니까?",
    choices: ["① CONNECT BY PRIOR 노드ID = 상위노드ID", "② CONNECT BY 노드ID = 상위노드ID", "③ CONNECT BY PRIOR 상위노드ID = 상위노드ID", "④ CONNECT BY 노드ID = PRIOR 노드ID"],
    answer: "① CONNECT BY PRIOR 노드ID = 상위노드ID",
    hint: "부모 행의 노드ID가 자식 행의 상위노드ID와 같아야 합니다.",
    explanation: "PRIOR가 붙은 부모의 노드ID와 현재 자식 행의 상위노드ID를 연결하면 위에서 아래로 계층이 전개됩니다.",
    confusion: "PRIOR의 위치를 바꾸면 탐색 방향이 달라질 수 있으므로 부모와 자식 컬럼을 먼저 구분해야 합니다."
  },
  {
    id: "sqld-exam-sql-029",
    kind: "choice",
    topic: "계층형 질의",
    difficulty: "심화",
    tags: ["sqld", "sql", "sql-advanced", "exam-style", "hierarchy", "oracle"],
    prompt: "Oracle 계층형 질의의 의사컬럼과 연산자에 대한 설명 중 옳은 것만을 모두 고른 것은 무엇입니까?\n가. 루트 행의 LEVEL은 1이다.\n나. CONNECT_BY_ISLEAF는 현재 결과에서 자식이 없는 행이면 1이다.\n다. CONNECT_BY_ROOT는 현재 행이 속한 계층의 루트 값을 구할 때 사용한다.",
    choices: ["① 가", "② 가, 나", "③ 나, 다", "④ 가, 나, 다"],
    answer: "④ 가, 나, 다",
    hint: "루트의 깊이, 말단 행 표시, 루트 값 참조를 각각 확인하세요.",
    explanation: "LEVEL은 루트에서 1로 시작하고 ISLEAF는 말단 행을 표시하며 CONNECT_BY_ROOT는 각 행의 루트 값을 반환합니다.",
    confusion: "CONNECT_BY_ISCYCLE은 NOCYCLE과 함께 순환이 감지된 행을 표시하는 용도입니다."
  },
  {
    id: "sqld-exam-sql-030",
    kind: "sql",
    topic: "셀프 조인",
    difficulty: "실전",
    tags: ["sqld", "sql", "sql-advanced", "exam-style", "join", "self-join"],
    prompt: "사원과 직속 관리자의 이름을 함께 조회하는 SQL로 가장 적절한 것은 무엇입니까? 사원 테이블의 컬럼은 employee_id, manager_id, name이다.",
    choices: ["① SELECT e.name, m.name FROM employee e LEFT JOIN employee m ON e.manager_id=m.employee_id", "② SELECT e.name, m.name FROM employee e CROSS JOIN employee m", "③ SELECT name, manager_id FROM employee GROUP BY manager_id", "④ SELECT e.name FROM employee e UNION employee m"],
    answer: "① SELECT e.name, m.name FROM employee e LEFT JOIN employee m ON e.manager_id=m.employee_id",
    hint: "같은 테이블에 사원 역할과 관리자 역할의 별칭을 각각 부여하세요.",
    explanation: "사원 e의 manager_id와 관리자 역할 m의 employee_id를 셀프 조인하면 두 이름을 한 행에 표시할 수 있습니다.",
    confusion: "LEFT JOIN을 사용하면 관리자가 없는 최고 관리자도 결과에 남길 수 있습니다."
  },
  {
    id: "sqld-exam-sql-031",
    kind: "sql",
    topic: "DML",
    difficulty: "실전",
    tags: ["sqld", "sql", "management", "exam-style", "dml", "update", "case", "frequent"],
    prompt: "EMP 테이블에서 grade='A'인 사원의 salary는 10%, 나머지 사원은 5% 인상하는 SQL로 옳은 것은 무엇입니까?",
    choices: ["① UPDATE emp SET salary = salary * CASE WHEN grade='A' THEN 1.10 ELSE 1.05 END", "② UPDATE emp SET salary = CASE grade='A' THEN 10 ELSE 5 END", "③ ALTER TABLE emp SET salary = salary + 10", "④ MERGE emp WHERE grade='A' SET salary=1.10"],
    answer: "① UPDATE emp SET salary = salary * CASE WHEN grade='A' THEN 1.10 ELSE 1.05 END",
    hint: "기존 급여에 등급별 인상 배수를 곱해야 합니다.",
    explanation: "검색 CASE로 등급에 따라 1.10 또는 1.05를 선택해 현재 salary에 곱히면 모든 행을 조건별로 인상할 수 있습니다.",
    confusion: "WHERE가 없으므로 모든 행이 수정 대상이며 CASE가 각 행의 인상률을 결정합니다."
  },
  {
    id: "sqld-exam-sql-032",
    kind: "choice",
    topic: "DML",
    difficulty: "실전",
    tags: ["sqld", "sql", "management", "exam-style", "dml", "merge"],
    prompt: "원본 데이터의 키가 대상 테이블에 존재하면 UPDATE하고 존재하지 않으면 INSERT하려고 한다. 가장 적절한 명령은 무엇입니까?",
    choices: ["① MERGE", "② TRUNCATE", "③ GRANT", "④ ROLLBACK"],
    answer: "① MERGE",
    hint: "일치 여부에 따라 두 DML 작업을 나누는 구문입니다.",
    explanation: "MERGE는 조인 조건의 일치 여부에 따라 WHEN MATCHED에서 UPDATE, WHEN NOT MATCHED에서 INSERT를 수행할 수 있습니다.",
    confusion: "MERGE의 구체적인 지원 문법과 동작은 DBMS별 차이가 있을 수 있습니다."
  },
  {
    id: "sqld-exam-sql-033",
    kind: "sql",
    topic: "TCL",
    difficulty: "심화",
    tags: ["sqld", "sql", "management", "exam-style", "tcl", "savepoint", "transaction"],
    prompt: "다음 명령 수행 후 `ROLLBACK TO s1`을 실행했을 때 남는 변경으로 옳은 것은 무엇입니까?\n```sql\nINSERT INTO T VALUES (1);\nSAVEPOINT s1;\nINSERT INTO T VALUES (2);\nROLLBACK TO s1;\n```",
    choices: ["① 두 INSERT가 모두 취소된다", "② 값 1의 INSERT만 남고 값 2의 INSERT는 취소된다", "③ 값 2의 INSERT만 남는다", "④ 자동 COMMIT되어 둘 다 영구 반영된다"],
    answer: "② 값 1의 INSERT만 남고 값 2의 INSERT는 취소된다",
    hint: "SAVEPOINT 이전 변경과 이후 변경을 나누어 보세요.",
    explanation: "ROLLBACK TO s1은 저장점 이후에 수행한 값 2의 INSERT만 취소하고 이전의 값 1 INSERT는 현재 트랜잭션에 남깁니다.",
    confusion: "남은 변경을 영구 반영하려면 이후 COMMIT이 필요하며 전체 ROLLBACK을 하면 값 1 변경도 취소됩니다."
  },
  {
    id: "sqld-exam-sql-034",
    kind: "choice",
    topic: "DDL",
    difficulty: "실전",
    tags: ["sqld", "sql", "management", "exam-style", "ddl", "transaction", "oracle"],
    prompt: "Oracle에서 DDL 명령의 트랜잭션 특성에 대한 설명으로 옳은 것은 무엇입니까?",
    choices: ["① DDL은 항상 사용자가 COMMIT할 때까지 반영되지 않는다", "② DDL 수행 전후에 암시적 COMMIT이 발생할 수 있다", "③ DDL은 SAVEPOINT 이후에만 실행할 수 있다", "④ DDL은 데이터 구조를 변경하지 않는다"],
    answer: "② DDL 수행 전후에 암시적 COMMIT이 발생할 수 있다",
    hint: "Oracle에서 CREATE, ALTER, DROP 실행이 기존 트랜잭션에 미치는 영향을 생각하세요.",
    explanation: "Oracle에서는 DDL 실행 전후에 암시적 COMMIT이 발생할 수 있어 이전 DML도 함께 확정될 수 있습니다.",
    confusion: "트랜잭션 처리 방식은 DBMS마다 차이가 있으므로 특정 DBMS 기준을 확인해야 합니다."
  },
  {
    id: "sqld-exam-sql-035",
    kind: "choice",
    topic: "DDL/DML",
    difficulty: "실전",
    tags: ["sqld", "sql", "management", "exam-style", "ddl", "dml", "truncate", "delete", "drop", "frequent"],
    prompt: "DELETE, TRUNCATE, DROP에 대한 설명 중 옳지 않은 것은 무엇입니까?",
    choices: ["① DELETE는 WHERE 절로 일부 행을 삭제할 수 있다", "② TRUNCATE는 테이블 구조를 유지하면서 전체 데이터를 제거한다", "③ DROP은 테이블 정의와 데이터를 함께 제거한다", "④ TRUNCATE는 항상 WHERE 절로 삭제 범위를 지정한다"],
    answer: "④ TRUNCATE는 항상 WHERE 절로 삭제 범위를 지정한다",
    hint: "행 단위 삭제 조건을 지원하는 명령을 구분하세요.",
    explanation: "TRUNCATE는 WHERE 절 없이 테이블 전체 데이터를 제거하며 테이블 구조는 유지합니다.",
    confusion: "DELETE는 DML이고 TRUNCATE와 DROP은 일반적으로 DDL로 분류됩니다."
  },
  {
    id: "sqld-exam-sql-036",
    kind: "sql",
    topic: "DCL",
    difficulty: "실전",
    tags: ["sqld", "sql", "management", "exam-style", "dcl", "grant", "privilege"],
    prompt: "사용자 U1에게 EMP 테이블 조회 권한을 부여하면서 U1이 다른 사용자에게도 그 권한을 부여할 수 있게 하는 명령으로 옳은 것은 무엇입니까?",
    choices: ["① GRANT SELECT ON emp TO u1 WITH GRANT OPTION", "② GRANT SELECT ON emp TO u1 WITH ADMIN OPTION", "③ REVOKE SELECT ON emp FROM u1", "④ GRANT CONNECT TO emp FROM u1"],
    answer: "① GRANT SELECT ON emp TO u1 WITH GRANT OPTION",
    hint: "객체 권한을 다른 사용자에게 다시 부여할 수 있게 하는 옵션입니다.",
    explanation: "객체 권한인 SELECT를 재부여할 수 있게 하려면 WITH GRANT OPTION을 사용합니다.",
    confusion: "WITH ADMIN OPTION은 일반적으로 시스템 권한이나 역할의 재부여와 관련해 사용됩니다."
  },
  {
    id: "sqld-exam-sql-037",
    kind: "choice",
    topic: "PIVOT",
    difficulty: "실전",
    tags: ["sqld", "sql", "sql-advanced", "exam-style", "pivot"],
    prompt: "월별 매출 행을 1월, 2월, 3월 컬럼으로 펼쳐 상품별 합계를 표시하려고 한다. 가장 적절한 연산은 무엇입니까?",
    choices: ["① PIVOT", "② UNPIVOT", "③ MINUS", "④ CONNECT BY"],
    answer: "① PIVOT",
    hint: "행에 있는 구분값을 열 방향으로 펼치는 연산입니다.",
    explanation: "PIVOT은 월처럼 행 값으로 존재하는 구분값을 컬럼으로 전환하고 지정한 집계를 계산합니다.",
    confusion: "UNPIVOT은 여러 컬럼에 펼쳐진 값을 다시 행 방향으로 변환합니다."
  },
  {
    id: "sqld-exam-sql-038",
    kind: "sql",
    topic: "정규 표현식",
    difficulty: "심화",
    tags: ["sqld", "sql", "sql-advanced", "exam-style", "regex", "oracle"],
    prompt: "Oracle에서 문자열 'AB-123-CD'에서 연속된 숫자 부분 '123'만 추출하는 표현으로 가장 적절한 것은 무엇입니까?",
    choices: ["① REGEXP_SUBSTR('AB-123-CD', '[0-9]+')", "② REGEXP_REPLACE('AB-123-CD', '[0-9]+', '')", "③ REGEXP_LIKE('AB-123-CD', '[0-9]+')", "④ SUBSTR('AB-123-CD', 1, 2)"],
    answer: "① REGEXP_SUBSTR('AB-123-CD', '[0-9]+')",
    hint: "패턴과 일치하는 부분 문자열을 반환하는 함수를 찾으세요.",
    explanation: "REGEXP_SUBSTR는 정규식과 일치하는 부분 문자열을 반환하므로 연속 숫자 123을 추출합니다.",
    confusion: "REGEXP_LIKE는 일치 여부를 검사하고 REGEXP_REPLACE는 일치 부분을 다른 문자열로 치환합니다."
  },
  {
    id: "sqld-exam-sql-039",
    kind: "choice",
    topic: "제약 조건",
    difficulty: "실전",
    tags: ["sqld", "sql", "management", "exam-style", "constraint", "foreign-key", "null"],
    prompt: "외래키 제약조건에 대한 설명으로 옳은 것은 무엇입니까?",
    choices: ["① 외래키 값은 반드시 자식 테이블에서 유일해야 한다", "② 외래키는 허용된 경우 NULL일 수 있으며, NULL이 아니면 참조 대상 키 값과 일치해야 한다", "③ 외래키는 항상 자식 테이블의 주식별자 전체가 된다", "④ 외래키가 있으면 부모 행을 아무 조건 없이 삭제할 수 있다"],
    answer: "② 외래키는 허용된 경우 NULL일 수 있으며, NULL이 아니면 참조 대상 키 값과 일치해야 한다",
    hint: "참조 무결성이 요구하는 값의 존재 여부를 생각하세요.",
    explanation: "외래키는 선택 관계 등에서 NULL을 허용할 수 있고 값이 존재하면 부모의 기본키 또는 유일키 값 중 하나를 참조해야 합니다.",
    confusion: "외래키 자체는 중복될 수 있으므로 한 부모를 여러 자식 행이 참조할 수 있습니다."
  },
  {
    id: "sqld-exam-sql-040",
    kind: "sql",
    topic: "집합 연산자",
    difficulty: "심화",
    tags: ["sqld", "sql", "sql-advanced", "exam-style", "set-operator", "order-by"],
    prompt: "집합 연산자를 사용한 SQL의 ORDER BY 작성에 대한 설명으로 가장 적절한 것은 무엇입니까?",
    choices: ["① 각 SELECT마다 반드시 ORDER BY를 작성한다", "② 전체 집합 연산 결과를 정렬하는 ORDER BY는 마지막 SELECT 뒤에 한 번 작성한다", "③ ORDER BY는 UNION ALL에서만 사용할 수 있다", "④ ORDER BY에는 첫 번째 SELECT의 컬럼이나 별칭을 사용할 수 없다"],
    answer: "② 전체 집합 연산 결과를 정렬하는 ORDER BY는 마지막 SELECT 뒤에 한 번 작성한다",
    hint: "여러 SELECT가 결합된 뒤 최종 결과를 정렬하는 위치를 생각하세요.",
    explanation: "집합 연산 전체 결과에 대한 ORDER BY는 마지막 SELECT 뒤에 작성하며 결과 컬럼 기준으로 정렬합니다.",
    confusion: "DBMS별로 서브쿼리 내부 정렬 허용 범위는 다를 수 있지만 집합 연산의 최종 정렬은 끝에 작성하는 것이 기본입니다."
  }
];
