import type { StudyQuestion } from "../questions";

// 신기술은 제품 버전 암기보다 오래 유지되는 구조와 핵심 개념을 중심으로 구성한다.
export const EMERGING_QUESTIONS: StudyQuestion[] = [
  {
    id: "emerging-container-01",
    kind: "choice",
    topic: "신기술",
    difficulty: "기초",
    tags: ["emerging", "신기술", "cloud", "container"],
    prompt: "컨테이너와 가상머신(VM)의 차이로 가장 알맞은 것을 고르시오.",
    choices: ["① 컨테이너는 일반적으로 호스트 OS 커널을 공유한다", "② 컨테이너마다 반드시 전체 게스트 OS가 필요하다", "③ VM은 하이퍼바이저를 사용할 수 없다", "④ 컨테이너는 프로세스 격리를 제공하지 않는다"],
    answer: "① 컨테이너는 일반적으로 호스트 OS 커널을 공유한다",
    hint: "전체 운영체제를 포함하는 방식과 애플리케이션 실행환경을 격리하는 방식을 비교하세요.",
    explanation: "컨테이너는 보통 호스트 커널을 공유하면서 프로세스와 파일시스템 등을 격리하므로 전체 게스트 OS를 실행하는 VM보다 가볍습니다.",
    confusion: "컨테이너도 격리를 제공하지만 VM과 동일한 격리 경계를 갖는다는 뜻은 아닙니다."
  },
  {
    id: "emerging-k8s-pod-01",
    kind: "concept",
    topic: "신기술",
    difficulty: "기초",
    tags: ["emerging", "신기술", "kubernetes", "cloud"],
    prompt: "Kubernetes에서 하나 이상의 컨테이너를 함께 실행하는 가장 작은 배포 단위를 쓰시오.",
    answer: "Pod(파드)",
    hint: "같은 네트워크와 저장소 자원을 공유할 수 있는 단위입니다.",
    explanation: "Pod는 Kubernetes가 생성하고 관리하는 가장 작은 실행 단위이며 내부 컨테이너들은 네트워크와 일부 저장소를 공유할 수 있습니다.",
    confusion: "컨테이너 자체와 Pod는 같은 개념이 아니며 하나의 Pod에 여러 컨테이너가 포함될 수 있습니다."
  },
  {
    id: "emerging-k8s-deploy-01",
    kind: "choice",
    topic: "신기술",
    difficulty: "실전",
    tags: ["emerging", "신기술", "kubernetes", "deployment"],
    prompt: "Kubernetes에서 애플리케이션의 복제본 수와 롤링 업데이트를 선언적으로 관리하는 대표 객체를 고르시오.",
    choices: ["① Deployment", "② ConfigMap", "③ Namespace", "④ Secret"],
    answer: "① Deployment",
    hint: "ReplicaSet을 관리하며 원하는 배포 상태를 유지하는 객체입니다.",
    explanation: "Deployment는 Pod 복제본의 원하는 상태를 선언하고 롤아웃·롤백과 롤링 업데이트를 관리합니다.",
    confusion: "Service는 Pod 집합에 안정적인 네트워크 접근점을 제공하고 Deployment는 워크로드 상태를 관리합니다."
  },
  {
    id: "emerging-serverless-01",
    kind: "concept",
    topic: "신기술",
    difficulty: "기초",
    tags: ["emerging", "신기술", "serverless", "cloud"],
    prompt: "개발자가 서버 인프라를 직접 관리하지 않고 이벤트 단위로 코드를 실행하며 사용량에 따라 확장되는 클라우드 실행 모델을 쓰시오.",
    answer: "서버리스 컴퓨팅(Serverless Computing)",
    hint: "서버가 실제로 없다는 뜻이 아니라 서버 운영 책임이 서비스 제공자에게 추상화됩니다.",
    explanation: "서버리스는 인프라 프로비저닝과 확장을 플랫폼이 담당하고 개발자는 함수나 애플리케이션 로직에 집중하는 실행 모델입니다.",
    confusion: "서버리스에도 실제 서버는 존재하며 사용자가 서버를 직접 관리하지 않는다는 의미입니다."
  },
  {
    id: "emerging-msa-01",
    kind: "choice",
    topic: "신기술",
    difficulty: "실전",
    tags: ["emerging", "신기술", "msa", "architecture"],
    prompt: "마이크로서비스 아키텍처(MSA)의 일반적인 특징으로 가장 알맞은 것을 고르시오.",
    choices: ["① 서비스별 독립 배포가 가능하도록 작은 서비스로 분리한다", "② 모든 기능이 하나의 프로세스와 데이터베이스만 사용해야 한다", "③ 서비스 사이 통신이 존재하지 않는다", "④ 분산 시스템의 복잡성이 줄어들기만 한다"],
    answer: "① 서비스별 독립 배포가 가능하도록 작은 서비스로 분리한다",
    hint: "업무 기능별 자율성과 독립 배포를 생각하세요.",
    explanation: "MSA는 업무 기능을 작은 서비스로 나누고 각 서비스를 독립적으로 개발·배포·확장할 수 있게 설계합니다.",
    confusion: "독립성의 장점과 함께 네트워크 통신, 데이터 일관성, 관측성 같은 분산 시스템 복잡성도 증가합니다."
  },
  {
    id: "emerging-cicd-01",
    kind: "concept",
    topic: "신기술",
    difficulty: "기초",
    tags: ["emerging", "신기술", "devops", "ci-cd"],
    prompt: "코드 변경을 자주 통합해 자동 빌드·테스트하는 CI와 배포 과정을 자동화하는 CD를 합쳐 부르는 용어를 쓰시오.",
    answer: "CI/CD",
    hint: "지속적 통합과 지속적 제공 또는 배포의 약어입니다.",
    explanation: "CI/CD 파이프라인은 변경사항의 통합·검증·배포를 자동화해 빠르고 반복 가능한 전달을 지원합니다.",
    confusion: "Continuous Delivery는 배포 가능한 상태까지 자동화하고 실제 운영 배포에 승인을 둘 수 있으며 Continuous Deployment는 운영 반영까지 자동화합니다."
  },
  {
    id: "emerging-iac-01",
    kind: "choice",
    topic: "신기술",
    difficulty: "기초",
    tags: ["emerging", "신기술", "iac", "devops"],
    prompt: "서버·네트워크·클라우드 자원 구성을 코드 파일로 정의하고 버전 관리하는 방식을 고르시오.",
    choices: ["① IaC", "② ETL", "③ OLAP", "④ RPA"],
    answer: "① IaC",
    hint: "Infrastructure as Code의 약어입니다.",
    explanation: "IaC는 인프라 구성을 코드로 선언하거나 자동화하여 반복 가능성과 일관성, 변경 이력 관리를 높입니다.",
    confusion: "CI/CD는 전달 파이프라인이고 IaC는 인프라 상태와 구성을 코드로 관리하는 방식입니다."
  },
  {
    id: "emerging-blue-green-01",
    kind: "concept",
    topic: "신기술",
    difficulty: "실전",
    tags: ["emerging", "신기술", "deployment", "devops"],
    prompt: "기존 운영 환경과 새 버전 환경을 동시에 준비한 뒤 트래픽을 새 환경으로 전환하는 배포 전략을 쓰시오.",
    answer: "블루-그린 배포(Blue-Green Deployment)",
    hint: "두 개의 동일한 운영 환경을 색상으로 구분합니다.",
    explanation: "블루-그린 배포는 현재 환경과 새 환경을 병렬로 운영 준비하고 트래픽 대상을 전환해 중단과 롤백 시간을 줄입니다.",
    confusion: "카나리 배포는 새 버전을 일부 사용자나 트래픽에 먼저 노출해 점진적으로 확대합니다."
  },
  {
    id: "emerging-zero-trust-01",
    kind: "choice",
    topic: "신기술",
    difficulty: "실전",
    tags: ["emerging", "신기술", "security", "zero-trust"],
    prompt: "제로 트러스트 보안의 핵심 원칙으로 가장 알맞은 것을 고르시오.",
    choices: ["① 네트워크 위치만으로 신뢰하지 않고 요청마다 검증한다", "② 내부망 사용자는 항상 신뢰한다", "③ 최초 로그인 뒤에는 권한을 확인하지 않는다", "④ 모든 사용자에게 같은 권한을 부여한다"],
    answer: "① 네트워크 위치만으로 신뢰하지 않고 요청마다 검증한다",
    hint: "명시적으로 검증하고 최소 권한을 적용합니다.",
    explanation: "제로 트러스트는 내부·외부 위치를 자동 신뢰하지 않고 사용자·기기·요청 맥락을 지속적으로 확인해 접근을 허용합니다.",
    confusion: "제로 트러스트는 아무도 접근시키지 않는다는 뜻이 아니라 신뢰를 미리 가정하지 않는 접근 모델입니다."
  },
  {
    id: "emerging-edge-01",
    kind: "concept",
    topic: "신기술",
    difficulty: "기초",
    tags: ["emerging", "신기술", "edge", "iot"],
    prompt: "데이터가 생성되는 장치나 사용자 가까운 위치에서 데이터를 처리해 지연과 전송량을 줄이는 컴퓨팅 방식을 쓰시오.",
    answer: "엣지 컴퓨팅(Edge Computing)",
    hint: "중앙 클라우드로 모든 데이터를 보내기 전에 가까운 지점에서 처리합니다.",
    explanation: "엣지 컴퓨팅은 데이터 발생 지점 가까이에서 연산을 수행해 응답 지연과 네트워크 대역폭 사용을 줄일 수 있습니다.",
    confusion: "클라우드를 완전히 대체하기보다 중앙 클라우드와 역할을 나누어 함께 사용하는 경우가 많습니다."
  },
  {
    id: "emerging-blockchain-01",
    kind: "choice",
    topic: "신기술",
    difficulty: "기초",
    tags: ["emerging", "신기술", "blockchain", "distributed"],
    prompt: "블록체인의 일반적인 특징으로 가장 알맞은 것을 고르시오.",
    choices: ["① 여러 참여자가 합의한 원장을 분산 보관할 수 있다", "② 한 관리자의 로컬 파일만 사용한다", "③ 기록된 블록은 아무 검증 없이 자유롭게 변경된다", "④ 모든 블록체인은 공개형이어야 한다"],
    answer: "① 여러 참여자가 합의한 원장을 분산 보관할 수 있다",
    hint: "분산 원장과 합의 과정을 떠올리세요.",
    explanation: "블록체인은 거래 기록을 블록으로 연결하고 여러 참여자가 합의한 원장을 분산 유지하는 기술입니다.",
    confusion: "블록체인에는 공개형뿐 아니라 참여자를 제한하는 허가형 구조도 있습니다."
  },
  {
    id: "emerging-cap-01",
    kind: "concept",
    topic: "신기술",
    difficulty: "심화",
    tags: ["emerging", "신기술", "distributed", "database"],
    prompt: "분산 시스템의 CAP 이론에서 C, A, P가 각각 의미하는 것을 쓰시오.",
    answer: "Consistency(일관성), Availability(가용성), Partition Tolerance(분할 내성)",
    hint: "같은 데이터 보기, 응답 가능성, 네트워크 단절 견딤의 세 성질입니다.",
    explanation: "CAP는 네트워크 분할이 발생한 상황에서 강한 일관성과 가용성을 동시에 완전히 보장하기 어렵다는 분산 시스템의 trade-off를 설명합니다.",
    confusion: "항상 세 요소 중 정확히 둘만 선택한다는 단순 암기보다 분할 상황에서 C와 A 사이의 선택을 이해하는 것이 중요합니다."
  },
  {
    id: "emerging-event-driven-01",
    kind: "choice",
    topic: "신기술",
    difficulty: "실전",
    tags: ["emerging", "신기술", "event", "architecture"],
    prompt: "서비스가 이벤트를 발행하고 다른 서비스가 이를 구독해 비동기로 처리하는 구조를 고르시오.",
    choices: ["① 이벤트 기반 아키텍처", "② 단일 계층 아키텍처", "③ 공유 메모리 구조", "④ 순차 파일 구조"],
    answer: "① 이벤트 기반 아키텍처",
    hint: "생산자와 소비자를 이벤트 브로커 등으로 느슨하게 연결합니다.",
    explanation: "이벤트 기반 아키텍처는 상태 변화나 사건을 이벤트로 발행하고 구독자가 비동기로 반응하게 해 구성요소의 결합도를 낮춥니다.",
    confusion: "비동기 처리는 확장성에 유리하지만 이벤트 순서, 중복 처리, 최종 일관성을 고려해야 합니다."
  },
  {
    id: "emerging-rag-01",
    kind: "concept",
    topic: "신기술",
    difficulty: "실전",
    tags: ["emerging", "신기술", "ai", "rag"],
    prompt: "생성형 AI가 답변 전에 외부 문서에서 관련 정보를 검색하고 그 내용을 입력에 포함해 생성 정확도를 높이는 방식을 쓰시오.",
    answer: "RAG(Retrieval-Augmented Generation, 검색 증강 생성)",
    hint: "검색(Retrieval)과 생성(Generation)을 결합합니다.",
    explanation: "RAG는 질문과 관련된 외부 지식을 검색해 모델의 문맥으로 제공한 뒤 그 근거를 활용해 답변을 생성합니다.",
    confusion: "RAG는 모델 자체 가중치를 다시 학습하는 파인튜닝과 다르며 검색 결과가 부정확하면 답변도 잘못될 수 있습니다."
  },
  {
    id: "emerging-hallucination-01",
    kind: "choice",
    topic: "신기술",
    difficulty: "기초",
    tags: ["emerging", "신기술", "ai", "generative-ai"],
    prompt: "생성형 AI가 사실과 다르거나 근거가 없는 내용을 그럴듯하게 만들어 내는 현상을 고르시오.",
    choices: ["① 환각(Hallucination)", "② 정규화", "③ 오버로딩", "④ 캐시 적중"],
    answer: "① 환각(Hallucination)",
    hint: "모델 출력의 사실성이 보장되지 않는 문제입니다.",
    explanation: "AI 환각은 모델이 학습 패턴을 바탕으로 유창하지만 사실이 아닌 내용을 생성하는 현상입니다.",
    confusion: "높은 문장 자연스러움이 사실 정확성을 의미하지 않으므로 출처 확인과 검증 절차가 필요합니다."
  }
];
